/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationLogin } from "../../funcs/authenticationLogin.js";
import { LoginRequestBody$inboundSchema } from "../../models/operations/login.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LoginRequestBody$inboundSchema,
};

export const tool$authenticationLogin: ToolDefinition<typeof args> = {
  name: "authentication-login",
  description: `Login

Verifies the wallet signature and returns a JWT token valid for 30 days.

**Error Codes:** \`VALIDATION_ERROR\`, \`INVALID_SIGNATURE\`, \`USER_NOT_FOUND\`, \`NONCE_NOT_FOUND\`, \`INACTIVE_NONCE\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authenticationLogin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
