/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationLogout } from "../../funcs/authenticationLogout.js";
import { LogoutRequestBody$inboundSchema } from "../../models/operations/logout.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LogoutRequestBody$inboundSchema.optional(),
};

export const tool$authenticationLogout: ToolDefinition<typeof args> = {
  name: "authentication-logout",
  description: `Logout

Deactivates the current nonce. Optionally deactivate all nonces to logout from all devices.

**Error Codes:** \`INVALID_TOKEN\`, \`EXPIRED_TOKEN\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authenticationLogout(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
