/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationCreateNonce } from "../../funcs/authenticationCreateNonce.js";
import { CreateNonceRequestBody$inboundSchema } from "../../models/operations/createnonce.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateNonceRequestBody$inboundSchema,
};

export const tool$authenticationCreateNonce: ToolDefinition<typeof args> = {
  name: "authentication-create-nonce",
  description: `Create Nonce

Returns a nonce that the user must sign with their wallet. Creates the user if they do not exist.

**Error Codes:** \`VALIDATION_ERROR\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authenticationCreateNonce(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
