/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { organizationActivateRaise } from "../../funcs/organizationActivateRaise.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.number().int(),
};

export const tool$organizationActivateRaise: ToolDefinition<typeof args> = {
  name: "organization-activate-raise",
  description: `Activate raise

Admin-only endpoint to activate the raise for ICO organizations. Raise starts immediately with duration from system settings.

**Error Codes:** \`VALIDATION_ERROR\`, \`INVALID_STATUS_TRANSITION\`, \`ORGANIZATION_NOT_FOUND\`, \`RAISE_NOT_FOUND\`, \`NOT_AUTHORIZED\`, \`INVALID_TOKEN\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationActivateRaise(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
