/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { organizationChangeOrganizationStatus } from "../../funcs/organizationChangeOrganizationStatus.js";
import { ChangeOrganizationStatusRequestBody$inboundSchema } from "../../models/operations/changeorganizationstatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.number().int(),
  requestBody: ChangeOrganizationStatusRequestBody$inboundSchema,
};

export const tool$organizationChangeOrganizationStatus: ToolDefinition<
  typeof args
> = {
  name: "organization-change-organization-status",
  description: `Change organization status

Admin-only endpoint to approve, reject, or activate organizations.

**Error Codes:** \`VALIDATION_ERROR\`, \`INVALID_STATUS_TRANSITION\`, \`ORGANIZATION_NOT_FOUND\`, \`NOT_AUTHORIZED\`, \`INVALID_TOKEN\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationChangeOrganizationStatus(
      client,
      args.id,
      args.requestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
