/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { proposalListProposalTrades } from "../../funcs/proposalListProposalTrades.js";
import { Side$inboundSchema } from "../../models/operations/listproposaltrades.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$inboundSchema.optional(),
};

export const tool$proposalListProposalTrades: ToolDefinition<typeof args> = {
  name: "proposal-list-proposal-trades",
  description: `List proposal trades

Returns a paginated list of trades for a proposal's decision markets.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await proposalListProposalTrades(
      client,
      args.id,
      args.page,
      args.limit,
      args.side,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
