/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { proposalInitializeProposal } from "../../funcs/proposalInitializeProposal.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.number().int(),
};

export const tool$proposalInitializeProposal: ToolDefinition<typeof args> = {
  name: "proposal-initialize-proposal",
  description: `Initialize proposal

Submits a draft proposal to the staking phase.

**Error Codes:** \`PROPOSAL_NOT_FOUND\`, \`INVALID_STATUS_TRANSITION\`, \`PROPOSAL_ALREADY_ACTIVE\`, \`NOT_AUTHORIZED\`, \`INVALID_TOKEN\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await proposalInitializeProposal(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
