/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { adminChangeUserRole } from "../funcs/adminChangeUserRole.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ChangeUserRoleRequestBody,
  ChangeUserRoleResponse,
} from "../models/operations/changeuserrole.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AdminChangeUserRoleMutationVariables = {
  id: number;
  requestBody: ChangeUserRoleRequestBody;
  options?: RequestOptions;
};

export type AdminChangeUserRoleMutationData = ChangeUserRoleResponse;

/**
 * Change user role
 *
 * @remarks
 * Admin-only endpoint to promote or demote users.
 *
 * **Error Codes:** `VALIDATION_ERROR`, `USER_NOT_FOUND`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
 */
export function useAdminChangeUserRoleMutation(
  options?: MutationHookOptions<
    AdminChangeUserRoleMutationData,
    Error,
    AdminChangeUserRoleMutationVariables
  >,
): UseMutationResult<
  AdminChangeUserRoleMutationData,
  Error,
  AdminChangeUserRoleMutationVariables
> {
  const client = useArchDAOContext();
  return useMutation({
    ...buildAdminChangeUserRoleMutation(client, options),
    ...options,
  });
}

export function mutationKeyAdminChangeUserRole(): MutationKey {
  return ["@archdao/archdao-client", "Admin", "changeUserRole"];
}

export function buildAdminChangeUserRoleMutation(
  client$: ArchDAOCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AdminChangeUserRoleMutationVariables,
  ) => Promise<AdminChangeUserRoleMutationData>;
} {
  return {
    mutationKey: mutationKeyAdminChangeUserRole(),
    mutationFn: function adminChangeUserRoleMutationFn({
      id,
      requestBody,
      options,
    }): Promise<AdminChangeUserRoleMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(adminChangeUserRole(
        client$,
        id,
        requestBody,
        mergedOptions,
      ));
    },
  };
}
