/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { authenticationLogin } from "../funcs/authenticationLogin.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { LoginRequestBody, LoginResponse } from "../models/operations/login.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AuthenticationLoginMutationVariables = {
  request: LoginRequestBody;
  options?: RequestOptions;
};

export type AuthenticationLoginMutationData = LoginResponse;

/**
 * Login
 *
 * @remarks
 * Verifies the wallet signature and returns a JWT token valid for 30 days.
 *
 * **Error Codes:** `VALIDATION_ERROR`, `INVALID_SIGNATURE`, `USER_NOT_FOUND`, `NONCE_NOT_FOUND`, `INACTIVE_NONCE`
 */
export function useAuthenticationLoginMutation(
  options?: MutationHookOptions<
    AuthenticationLoginMutationData,
    Error,
    AuthenticationLoginMutationVariables
  >,
): UseMutationResult<
  AuthenticationLoginMutationData,
  Error,
  AuthenticationLoginMutationVariables
> {
  const client = useArchDAOContext();
  return useMutation({
    ...buildAuthenticationLoginMutation(client, options),
    ...options,
  });
}

export function mutationKeyAuthenticationLogin(): MutationKey {
  return ["@archdao/archdao-client", "Authentication", "login"];
}

export function buildAuthenticationLoginMutation(
  client$: ArchDAOCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AuthenticationLoginMutationVariables,
  ) => Promise<AuthenticationLoginMutationData>;
} {
  return {
    mutationKey: mutationKeyAuthenticationLogin(),
    mutationFn: function authenticationLoginMutationFn({
      request,
      options,
    }): Promise<AuthenticationLoginMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(authenticationLogin(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
