/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { authenticationLogout } from "../funcs/authenticationLogout.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  LogoutRequestBody,
  LogoutResponse,
} from "../models/operations/logout.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AuthenticationLogoutMutationVariables = {
  request?: LogoutRequestBody | undefined;
  options?: RequestOptions;
};

export type AuthenticationLogoutMutationData = LogoutResponse;

/**
 * Logout
 *
 * @remarks
 * Deactivates the current nonce. Optionally deactivate all nonces to logout from all devices.
 *
 * **Error Codes:** `INVALID_TOKEN`, `EXPIRED_TOKEN`
 */
export function useAuthenticationLogoutMutation(
  options?: MutationHookOptions<
    AuthenticationLogoutMutationData,
    Error,
    AuthenticationLogoutMutationVariables
  >,
): UseMutationResult<
  AuthenticationLogoutMutationData,
  Error,
  AuthenticationLogoutMutationVariables
> {
  const client = useArchDAOContext();
  return useMutation({
    ...buildAuthenticationLogoutMutation(client, options),
    ...options,
  });
}

export function mutationKeyAuthenticationLogout(): MutationKey {
  return ["@archdao/archdao-client", "Authentication", "logout"];
}

export function buildAuthenticationLogoutMutation(
  client$: ArchDAOCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AuthenticationLogoutMutationVariables,
  ) => Promise<AuthenticationLogoutMutationData>;
} {
  return {
    mutationKey: mutationKeyAuthenticationLogout(),
    mutationFn: function authenticationLogoutMutationFn({
      request,
      options,
    }): Promise<AuthenticationLogoutMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(authenticationLogout(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
