/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { organizationEditOrganization } from "../funcs/organizationEditOrganization.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  EditOrganizationRequestBody,
  EditOrganizationResponse,
} from "../models/operations/editorganization.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type OrganizationEditOrganizationMutationVariables = {
  id: number;
  requestBody?: EditOrganizationRequestBody | undefined;
  options?: RequestOptions;
};

export type OrganizationEditOrganizationMutationData = EditOrganizationResponse;

/**
 * Edit organization
 *
 * @remarks
 * Admin-only endpoint to edit organization details.
 *
 * **Error Codes:** `VALIDATION_ERROR`, `ORGANIZATION_NOT_FOUND`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
 */
export function useOrganizationEditOrganizationMutation(
  options?: MutationHookOptions<
    OrganizationEditOrganizationMutationData,
    Error,
    OrganizationEditOrganizationMutationVariables
  >,
): UseMutationResult<
  OrganizationEditOrganizationMutationData,
  Error,
  OrganizationEditOrganizationMutationVariables
> {
  const client = useArchDAOContext();
  return useMutation({
    ...buildOrganizationEditOrganizationMutation(client, options),
    ...options,
  });
}

export function mutationKeyOrganizationEditOrganization(): MutationKey {
  return ["@archdao/archdao-client", "Organization", "editOrganization"];
}

export function buildOrganizationEditOrganizationMutation(
  client$: ArchDAOCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: OrganizationEditOrganizationMutationVariables,
  ) => Promise<OrganizationEditOrganizationMutationData>;
} {
  return {
    mutationKey: mutationKeyOrganizationEditOrganization(),
    mutationFn: function organizationEditOrganizationMutationFn({
      id,
      requestBody,
      options,
    }): Promise<OrganizationEditOrganizationMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(organizationEditOrganization(
        client$,
        id,
        requestBody,
        mergedOptions,
      ));
    },
  };
}
