/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { organizationChangeOrganizationStatus } from "../funcs/organizationChangeOrganizationStatus.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ChangeOrganizationStatusRequestBody,
  ChangeOrganizationStatusResponse,
} from "../models/operations/changeorganizationstatus.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type OrganizationChangeOrganizationStatusMutationVariables = {
  id: number;
  requestBody: ChangeOrganizationStatusRequestBody;
  options?: RequestOptions;
};

export type OrganizationChangeOrganizationStatusMutationData =
  ChangeOrganizationStatusResponse;

/**
 * Change organization status
 *
 * @remarks
 * Admin-only endpoint to approve, reject, or activate organizations.
 *
 * **Error Codes:** `VALIDATION_ERROR`, `INVALID_STATUS_TRANSITION`, `ORGANIZATION_NOT_FOUND`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
 */
export function useOrganizationChangeOrganizationStatusMutation(
  options?: MutationHookOptions<
    OrganizationChangeOrganizationStatusMutationData,
    Error,
    OrganizationChangeOrganizationStatusMutationVariables
  >,
): UseMutationResult<
  OrganizationChangeOrganizationStatusMutationData,
  Error,
  OrganizationChangeOrganizationStatusMutationVariables
> {
  const client = useArchDAOContext();
  return useMutation({
    ...buildOrganizationChangeOrganizationStatusMutation(client, options),
    ...options,
  });
}

export function mutationKeyOrganizationChangeOrganizationStatus(): MutationKey {
  return [
    "@archdao/archdao-client",
    "Organization",
    "changeOrganizationStatus",
  ];
}

export function buildOrganizationChangeOrganizationStatusMutation(
  client$: ArchDAOCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: OrganizationChangeOrganizationStatusMutationVariables,
  ) => Promise<OrganizationChangeOrganizationStatusMutationData>;
} {
  return {
    mutationKey: mutationKeyOrganizationChangeOrganizationStatus(),
    mutationFn: function organizationChangeOrganizationStatusMutationFn({
      id,
      requestBody,
      options,
    }): Promise<OrganizationChangeOrganizationStatusMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(organizationChangeOrganizationStatus(
        client$,
        id,
        requestBody,
        mergedOptions,
      ));
    },
  };
}
