/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { ArchDAOCore } from "../core.js";
import { proposalListProposals } from "../funcs/proposalListProposals.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ListProposalsRequest,
  ListProposalsResponseBody,
  ListProposalsSecurity,
} from "../models/operations/listproposals.js";
import { unwrapAsync } from "../types/fp.js";
import { useArchDAOContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type ProposalListProposalsQueryData = ListProposalsResponseBody;

/**
 * List proposals
 *
 * @remarks
 * Returns proposals with visibility rules. Unauthenticated users see public proposals (staking, active, resolved, executed). Authenticated users also see their own drafts. Admins see all.
 *
 * **Searchable fields:** `title`
 *
 * **Default search field:** `title`
 */
export function useProposalListProposals(
  request: ListProposalsRequest,
  security?: ListProposalsSecurity | undefined,
  options?: QueryHookOptions<ProposalListProposalsQueryData>,
): UseQueryResult<ProposalListProposalsQueryData, Error> {
  const client = useArchDAOContext();
  return useQuery({
    ...buildProposalListProposalsQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * List proposals
 *
 * @remarks
 * Returns proposals with visibility rules. Unauthenticated users see public proposals (staking, active, resolved, executed). Authenticated users also see their own drafts. Admins see all.
 *
 * **Searchable fields:** `title`
 *
 * **Default search field:** `title`
 */
export function useProposalListProposalsSuspense(
  request: ListProposalsRequest,
  security?: ListProposalsSecurity | undefined,
  options?: SuspenseQueryHookOptions<ProposalListProposalsQueryData>,
): UseSuspenseQueryResult<ProposalListProposalsQueryData, Error> {
  const client = useArchDAOContext();
  return useSuspenseQuery({
    ...buildProposalListProposalsQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function prefetchProposalListProposals(
  queryClient: QueryClient,
  client$: ArchDAOCore,
  request: ListProposalsRequest,
  security?: ListProposalsSecurity | undefined,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildProposalListProposalsQuery(
      client$,
      request,
      security,
    ),
  });
}

export function setProposalListProposalsData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      page?: number | undefined;
      limit?: number | undefined;
      search?: string | undefined;
      fields?: string | undefined;
      status?: string | undefined;
      organizationId?: string | undefined;
    },
  ],
  data: ProposalListProposalsQueryData,
): ProposalListProposalsQueryData | undefined {
  const key = queryKeyProposalListProposals(...queryKeyBase);

  return client.setQueryData<ProposalListProposalsQueryData>(key, data);
}

export function invalidateProposalListProposals(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      page?: number | undefined;
      limit?: number | undefined;
      search?: string | undefined;
      fields?: string | undefined;
      status?: string | undefined;
      organizationId?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@archdao/archdao-client",
      "Proposal",
      "listProposals",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllProposalListProposals(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@archdao/archdao-client", "Proposal", "listProposals"],
  });
}

export function buildProposalListProposalsQuery(
  client$: ArchDAOCore,
  request: ListProposalsRequest,
  security?: ListProposalsSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ProposalListProposalsQueryData>;
} {
  return {
    queryKey: queryKeyProposalListProposals({
      page: request.page,
      limit: request.limit,
      search: request.search,
      fields: request.fields,
      status: request.status,
      organizationId: request.organizationId,
    }),
    queryFn: async function proposalListProposalsQueryFn(
      ctx,
    ): Promise<ProposalListProposalsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(proposalListProposals(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyProposalListProposals(
  parameters: {
    page?: number | undefined;
    limit?: number | undefined;
    search?: string | undefined;
    fields?: string | undefined;
    status?: string | undefined;
    organizationId?: string | undefined;
  },
): QueryKey {
  return ["@archdao/archdao-client", "Proposal", "listProposals", parameters];
}
