/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ArchDAOCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$adminChangeUserRole } from "./tools/adminChangeUserRole.js";
import { tool$adminListAuditLogs } from "./tools/adminListAuditLogs.js";
import { tool$adminListUsers } from "./tools/adminListUsers.js";
import { tool$authenticationCreateNonce } from "./tools/authenticationCreateNonce.js";
import { tool$authenticationGetSelf } from "./tools/authenticationGetSelf.js";
import { tool$authenticationLogin } from "./tools/authenticationLogin.js";
import { tool$authenticationLogout } from "./tools/authenticationLogout.js";
import { tool$organizationActivateRaise } from "./tools/organizationActivateRaise.js";
import { tool$organizationChangeOrganizationStatus } from "./tools/organizationChangeOrganizationStatus.js";
import { tool$organizationCreateOrganization } from "./tools/organizationCreateOrganization.js";
import { tool$organizationEditOrganization } from "./tools/organizationEditOrganization.js";
import { tool$proposalCancelProposal } from "./tools/proposalCancelProposal.js";
import { tool$proposalCreateProposal } from "./tools/proposalCreateProposal.js";
import { tool$proposalInitializeProposal } from "./tools/proposalInitializeProposal.js";
import { tool$proposalListProposalStakes } from "./tools/proposalListProposalStakes.js";
import { tool$proposalListProposalTrades } from "./tools/proposalListProposalTrades.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "ArchDAO",
    version: "1.2.0",
  });

  const client = new ArchDAOCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$authenticationCreateNonce);
  tool(tool$authenticationLogin);
  tool(tool$authenticationLogout);
  tool(tool$authenticationGetSelf);
  tool(tool$organizationCreateOrganization);
  tool(tool$organizationEditOrganization);
  tool(tool$organizationChangeOrganizationStatus);
  tool(tool$organizationActivateRaise);
  tool(tool$proposalCreateProposal);
  tool(tool$proposalCancelProposal);
  tool(tool$proposalInitializeProposal);
  tool(tool$proposalListProposalStakes);
  tool(tool$proposalListProposalTrades);
  tool(tool$adminListUsers);
  tool(tool$adminChangeUserRole);
  tool(tool$adminListAuditLogs);

  return server;
}
