/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminChangeUserRole } from "../funcs/adminChangeUserRole.js";
import { adminListAuditLogs } from "../funcs/adminListAuditLogs.js";
import { adminListUsers } from "../funcs/adminListUsers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import {
  ChangeUserRoleRequestBody,
  ChangeUserRoleResponse,
} from "../models/operations/changeuserrole.js";
import {
  ListAuditLogsRequest,
  ListAuditLogsResponse,
} from "../models/operations/listauditlogs.js";
import {
  ListUsersRequest,
  ListUsersResponse,
} from "../models/operations/listusers.js";
import { unwrapAsync } from "../types/fp.js";

export class Admin extends ClientSDK {
  /**
   * List users
   *
   * @remarks
   * Admin-only endpoint to list all users with optional filters.
   *
   * **Searchable fields:** `address`, `name`
   *
   * **Default search field:** `address`
   */
  async listUsers(
    request: ListUsersRequest,
    options?: RequestOptions,
  ): Promise<ListUsersResponse> {
    return unwrapAsync(adminListUsers(
      this,
      request,
      options,
    ));
  }

  /**
   * Change user role
   *
   * @remarks
   * Admin-only endpoint to promote or demote users.
   *
   * **Error Codes:** `VALIDATION_ERROR`, `USER_NOT_FOUND`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
   */
  async changeUserRole(
    id: number,
    requestBody: ChangeUserRoleRequestBody,
    options?: RequestOptions,
  ): Promise<ChangeUserRoleResponse> {
    return unwrapAsync(adminChangeUserRole(
      this,
      id,
      requestBody,
      options,
    ));
  }

  /**
   * List audit logs
   *
   * @remarks
   * Admin-only endpoint to view audit trail of admin actions.
   */
  async listAuditLogs(
    request: ListAuditLogsRequest,
    options?: RequestOptions,
  ): Promise<ListAuditLogsResponse> {
    return unwrapAsync(adminListAuditLogs(
      this,
      request,
      options,
    ));
  }
}
