/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminChangeUserRole } from "../funcs/adminChangeUserRole.js";
import { adminListAuditLogs } from "../funcs/adminListAuditLogs.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Admin extends ClientSDK {
  /**
   * Change user role
   *
   * @remarks
   * Admin-only. Promote or demote users.
   */
  async changeUserRole(
    request: operations.ChangeUserRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.ChangeUserRoleResponseBody> {
    return unwrapAsync(adminChangeUserRole(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit logs
   *
   * @remarks
   * Admin-only. View audit trail of admin actions.
   */
  async listAuditLogs(
    request: operations.ListAuditLogsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAuditLogsResponseBody> {
    return unwrapAsync(adminListAuditLogs(
      this,
      request,
      options,
    ));
  }
}
