/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationCreateNonce } from "../funcs/authenticationCreateNonce.js";
import { authenticationGetSelf } from "../funcs/authenticationGetSelf.js";
import { authenticationLogin } from "../funcs/authenticationLogin.js";
import { authenticationLogout } from "../funcs/authenticationLogout.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { NonceResponse } from "../models/components/nonceresponse.js";
import { Ok } from "../models/components/ok.js";
import { TokenResponse } from "../models/components/tokenresponse.js";
import { UserWithNoncesResponse } from "../models/components/userwithnoncesresponse.js";
import { CreateNonceRequestBody } from "../models/operations/createnonce.js";
import { LoginRequestBody } from "../models/operations/login.js";
import { LogoutRequestBody } from "../models/operations/logout.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Create Nonce
   *
   * @remarks
   * Returns a nonce that the user must sign with their wallet. Creates the user if they do not exist.
   *
   * **Error Codes:** `VALIDATION_ERROR`
   */
  async createNonce(
    request: CreateNonceRequestBody,
    options?: RequestOptions,
  ): Promise<NonceResponse> {
    return unwrapAsync(authenticationCreateNonce(
      this,
      request,
      options,
    ));
  }

  /**
   * Login
   *
   * @remarks
   * Verifies the wallet signature and returns a JWT token valid for 30 days.
   *
   * **Error Codes:** `VALIDATION_ERROR`, `INVALID_SIGNATURE`, `USER_NOT_FOUND`, `NONCE_NOT_FOUND`, `INACTIVE_NONCE`
   */
  async login(
    request: LoginRequestBody,
    options?: RequestOptions,
  ): Promise<TokenResponse> {
    return unwrapAsync(authenticationLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Logout
   *
   * @remarks
   * Deactivates the current nonce. Optionally deactivate all nonces to logout from all devices.
   *
   * **Error Codes:** `INVALID_TOKEN`, `EXPIRED_TOKEN`
   */
  async logout(
    request?: LogoutRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<Ok> {
    return unwrapAsync(authenticationLogout(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Self
   *
   * @remarks
   * Returns the authenticated user's information including active sessions.
   *
   * **Error Codes:** `INVALID_TOKEN`, `EXPIRED_TOKEN`
   */
  async getSelf(
    options?: RequestOptions,
  ): Promise<UserWithNoncesResponse> {
    return unwrapAsync(authenticationGetSelf(
      this,
      options,
    ));
  }
}
