/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authCreateNonce } from "../funcs/authCreateNonce.js";
import { authListNonces } from "../funcs/authListNonces.js";
import { authLogin } from "../funcs/authLogin.js";
import { authLogout } from "../funcs/authLogout.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Create nonce
   *
   * @remarks
   * Returns a nonce for the user to sign. Creates the user if they don't exist.
   */
  async createNonce(
    request: operations.CreateNonceRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateNonceResponseBody> {
    return unwrapAsync(authCreateNonce(
      this,
      request,
      options,
    ));
  }

  /**
   * Login
   *
   * @remarks
   * Verifies wallet signature and returns a JWT token (30 day expiry).
   */
  async login(
    request: operations.LoginRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LoginResponseBody> {
    return unwrapAsync(authLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Logout
   *
   * @remarks
   * Deactivates the current nonce. Set `all: true` to logout from all devices.
   */
  async logout(
    request?: operations.LogoutRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.LogoutResponseBody> {
    return unwrapAsync(authLogout(
      this,
      request,
      options,
    ));
  }

  /**
   * List active sessions
   *
   * @remarks
   * Returns the authenticated user's active nonces (sessions).
   */
  async listNonces(
    options?: RequestOptions,
  ): Promise<operations.ListNoncesResponseBody> {
    return unwrapAsync(authListNonces(
      this,
      options,
    ));
  }
}
