/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationGetMe } from "../funcs/authenticationGetMe.js";
import { authenticationGetNonce } from "../funcs/authenticationGetNonce.js";
import { authenticationLogin } from "../funcs/authenticationLogin.js";
import { authenticationLogout } from "../funcs/authenticationLogout.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Get a new nonce for wallet signing
   *
   * @remarks
   * Returns a nonce that the user must sign with their wallet. Creates the user if they do not exist.
   */
  async getNonce(
    request: operations.GetNonceRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GetNonceResponseBody> {
    return unwrapAsync(authenticationGetNonce(
      this,
      request,
      options,
    ));
  }

  /**
   * Login with wallet signature
   *
   * @remarks
   * Verifies the wallet signature and returns a JWT token valid for 30 days.
   */
  async login(
    request: operations.LoginRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LoginResponseBody> {
    return unwrapAsync(authenticationLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Logout user
   *
   * @remarks
   * Deactivates the current nonce. Optionally deactivate all nonces to logout from all devices.
   */
  async logout(
    request?: operations.LogoutRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<components.SuccessResponse> {
    return unwrapAsync(authenticationLogout(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current user info
   *
   * @remarks
   * Returns the authenticated user's information including active sessions.
   */
  async getMe(
    options?: RequestOptions,
  ): Promise<operations.GetMeResponseBody> {
    return unwrapAsync(authenticationGetMe(
      this,
      options,
    ));
  }
}
