/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationActivateRaise } from "../funcs/organizationActivateRaise.js";
import { organizationChangeOrganizationStatus } from "../funcs/organizationChangeOrganizationStatus.js";
import { organizationCreateOrganization } from "../funcs/organizationCreateOrganization.js";
import { organizationEditOrganization } from "../funcs/organizationEditOrganization.js";
import { organizationGetOrganization } from "../funcs/organizationGetOrganization.js";
import { organizationListOrganizations } from "../funcs/organizationListOrganizations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organization extends ClientSDK {
  /**
   * List organizations
   *
   * @remarks
   * Returns a paginated list of organizations. Visibility varies by authentication status and role.
   *
   * **Searchable fields:** `name`, `description`
   *
   * **Default search field:** `name`
   */
  async listOrganizations(
    request: operations.ListOrganizationsRequest,
    security?: operations.ListOrganizationsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListOrganizationsResponseBody> {
    return unwrapAsync(organizationListOrganizations(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * Create organization
   *
   * @remarks
   * Creates a new organization (external or ICO type). Uses multipart/form-data for image uploads.
   */
  async createOrganization(
    request: operations.CreateOrganizationRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateOrganizationResponseBody> {
    return unwrapAsync(organizationCreateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Get organization by slug
   *
   * @remarks
   * Returns full organization details including proposals.
   */
  async getOrganization(
    request: operations.GetOrganizationRequest,
    security?: operations.GetOrganizationSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationResponseBody> {
    return unwrapAsync(organizationGetOrganization(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * Edit organization
   *
   * @remarks
   * Admin-only endpoint to edit organization details.
   */
  async editOrganization(
    request: operations.EditOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.EditOrganizationResponseBody> {
    return unwrapAsync(organizationEditOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Change organization status
   *
   * @remarks
   * Admin-only endpoint to approve, reject, or activate organizations.
   */
  async changeOrganizationStatus(
    request: operations.ChangeOrganizationStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.ChangeOrganizationStatusResponseBody> {
    return unwrapAsync(organizationChangeOrganizationStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate raise
   *
   * @remarks
   * Admin-only endpoint to activate the raise for ICO organizations. Raise starts immediately with duration from system settings.
   */
  async activateRaise(
    request: operations.ActivateRaiseRequest,
    options?: RequestOptions,
  ): Promise<operations.ActivateRaiseResponseBody> {
    return unwrapAsync(organizationActivateRaise(
      this,
      request,
      options,
    ));
  }
}
