/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proposalCancelProposal } from "../funcs/proposalCancelProposal.js";
import { proposalCreateProposal } from "../funcs/proposalCreateProposal.js";
import { proposalGetProposal } from "../funcs/proposalGetProposal.js";
import { proposalInitializeProposal } from "../funcs/proposalInitializeProposal.js";
import { proposalListProposals } from "../funcs/proposalListProposals.js";
import { proposalListProposalStakes } from "../funcs/proposalListProposalStakes.js";
import { proposalListProposalTrades } from "../funcs/proposalListProposalTrades.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Proposal extends ClientSDK {
  /**
   * List proposals
   *
   * @remarks
   * Returns proposals with visibility rules. Unauthenticated users see public proposals (staking, active, resolved, executed). Authenticated users also see their own drafts. Admins see all.
   *
   * **Searchable fields:** `title`
   *
   * **Default search field:** `title`
   */
  async listProposals(
    request: operations.ListProposalsRequest,
    security?: operations.ListProposalsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListProposalsResponseBody> {
    return unwrapAsync(proposalListProposals(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * Create proposal
   *
   * @remarks
   * Creates a new proposal in draft status.
   *
   * **Error Codes:** `VALIDATION_ERROR`, `INVALID_ACTION_DATA`, `EMPTY_ACTIONS`, `ORGANIZATION_NOT_FOUND`, `INSUFFICIENT_TOKEN_BALANCE`, `INVALID_TOKEN`
   */
  async createProposal(
    request: components.CreateProposalRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateProposalResponseBody> {
    return unwrapAsync(proposalCreateProposal(
      this,
      request,
      options,
    ));
  }

  /**
   * Get proposal details
   *
   * @remarks
   * Returns full proposal details. Draft proposals are only visible to authorized users.
   *
   * **Error Codes:** `PROPOSAL_NOT_FOUND`, `NOT_AUTHORIZED`
   */
  async getProposal(
    request: operations.GetProposalRequest,
    security?: operations.GetProposalSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetProposalResponseBody> {
    return unwrapAsync(proposalGetProposal(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * Cancel proposal
   *
   * @remarks
   * Cancels a proposal. Only allowed before trading begins (draft or staking status).
   *
   * **Error Codes:** `PROPOSAL_NOT_FOUND`, `INVALID_STATUS_TRANSITION`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
   */
  async cancelProposal(
    request: operations.CancelProposalRequest,
    options?: RequestOptions,
  ): Promise<operations.CancelProposalResponseBody> {
    return unwrapAsync(proposalCancelProposal(
      this,
      request,
      options,
    ));
  }

  /**
   * Initialize proposal
   *
   * @remarks
   * Submits a draft proposal to the staking phase.
   *
   * **Error Codes:** `PROPOSAL_NOT_FOUND`, `INVALID_STATUS_TRANSITION`, `PROPOSAL_ALREADY_ACTIVE`, `NOT_AUTHORIZED`, `INVALID_TOKEN`
   */
  async initializeProposal(
    request: operations.InitializeProposalRequest,
    options?: RequestOptions,
  ): Promise<operations.InitializeProposalResponseBody> {
    return unwrapAsync(proposalInitializeProposal(
      this,
      request,
      options,
    ));
  }

  /**
   * List proposal stakes
   *
   * @remarks
   * Returns a paginated list of stakes for a proposal.
   */
  async listProposalStakes(
    request: operations.ListProposalStakesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListProposalStakesResponseBody> {
    return unwrapAsync(proposalListProposalStakes(
      this,
      request,
      options,
    ));
  }

  /**
   * List proposal trades
   *
   * @remarks
   * Returns a paginated list of trades for a proposal's decision markets.
   */
  async listProposalTrades(
    request: operations.ListProposalTradesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListProposalTradesResponseBody> {
    return unwrapAsync(proposalListProposalTrades(
      this,
      request,
      options,
    ));
  }
}
