/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { raiseGetRaise } from "../funcs/raiseGetRaise.js";
import { raiseListContributions } from "../funcs/raiseListContributions.js";
import { raiseListRaises } from "../funcs/raiseListRaises.js";
import { raiseUpdateRaise } from "../funcs/raiseUpdateRaise.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Raise extends ClientSDK {
  /**
   * List raises
   *
   * @remarks
   * Returns paginated list of raises.
   */
  async listRaises(
    request: operations.ListRaisesRequest,
    security?: operations.ListRaisesSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListRaisesResponseBody> {
    return unwrapAsync(raiseListRaises(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * Get raise
   *
   * @remarks
   * Returns raise details including allocations.
   */
  async getRaise(
    id: number,
    security?: operations.GetRaiseSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetRaiseResponseBody> {
    return unwrapAsync(raiseGetRaise(
      this,
      id,
      security,
      options,
    ));
  }

  /**
   * Update raise
   *
   * @remarks
   * Owner can set acceptedAmount during finalizing. Admin can also update status.
   */
  async updateRaise(
    request: operations.UpdateRaiseRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateRaiseResponseBody> {
    return unwrapAsync(raiseUpdateRaise(
      this,
      request,
      options,
    ));
  }

  /**
   * List contributions
   *
   * @remarks
   * Returns paginated list of contributions for a raise.
   */
  async listContributions(
    request: operations.ListContributionsRequest,
    security?: operations.ListContributionsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListContributionsResponseBody> {
    return unwrapAsync(raiseListContributions(
      this,
      request,
      security,
      options,
    ));
  }
}
