/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Admin } from "./admin.js";
import { Authentication } from "./authentication.js";
import { Organization } from "./organization.js";
import { Proposal } from "./proposal.js";

export class Archdao extends ClientSDK {
  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }

  private _organization?: Organization;
  get organization(): Organization {
    return (this._organization ??= new Organization(this._options));
  }

  private _proposal?: Proposal;
  get proposal(): Proposal {
    return (this._proposal ??= new Proposal(this._options));
  }

  private _admin?: Admin;
  get admin(): Admin {
    return (this._admin ??= new Admin(this._options));
  }
}
