/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Admin } from "./admin.js";
import { Auth } from "./auth.js";
import { Organization } from "./organization.js";
import { Proposal } from "./proposal.js";
import { Raise } from "./raise.js";
import { User } from "./user.js";

export class ArchDAO extends ClientSDK {
  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _user?: User;
  get user(): User {
    return (this._user ??= new User(this._options));
  }

  private _organization?: Organization;
  get organization(): Organization {
    return (this._organization ??= new Organization(this._options));
  }

  private _raise?: Raise;
  get raise(): Raise {
    return (this._raise ??= new Raise(this._options));
  }

  private _proposal?: Proposal;
  get proposal(): Proposal {
    return (this._proposal ??= new Proposal(this._options));
  }

  private _admin?: Admin;
  get admin(): Admin {
    return (this._admin ??= new Admin(this._options));
  }
}
