/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "../components/contactinformation.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "../components/link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "../components/organizationstatus.js";
import {
  OrganizationType,
  OrganizationType$inboundSchema,
  OrganizationType$outboundSchema,
} from "../components/organizationtype.js";
import {
  Raise,
  Raise$inboundSchema,
  Raise$Outbound,
  Raise$outboundSchema,
} from "../components/raise.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "../components/token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "../components/treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "../components/user.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ActivateRaiseRequest = {
  id: number;
};

export type ActivateRaiseData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  type?: OrganizationType | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  raise?: Raise | undefined;
};

/**
 * Success response wrapper
 */
export type ActivateRaiseResponseBody = {
  success: true;
  data?: ActivateRaiseData | undefined;
};

export type ActivateRaiseResponse = Err | ActivateRaiseResponseBody;

/** @internal */
export const ActivateRaiseRequest$inboundSchema: z.ZodType<
  ActivateRaiseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type ActivateRaiseRequest$Outbound = {
  id: number;
};

/** @internal */
export const ActivateRaiseRequest$outboundSchema: z.ZodType<
  ActivateRaiseRequest$Outbound,
  z.ZodTypeDef,
  ActivateRaiseRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivateRaiseRequest$ {
  /** @deprecated use `ActivateRaiseRequest$inboundSchema` instead. */
  export const inboundSchema = ActivateRaiseRequest$inboundSchema;
  /** @deprecated use `ActivateRaiseRequest$outboundSchema` instead. */
  export const outboundSchema = ActivateRaiseRequest$outboundSchema;
  /** @deprecated use `ActivateRaiseRequest$Outbound` instead. */
  export type Outbound = ActivateRaiseRequest$Outbound;
}

export function activateRaiseRequestToJSON(
  activateRaiseRequest: ActivateRaiseRequest,
): string {
  return JSON.stringify(
    ActivateRaiseRequest$outboundSchema.parse(activateRaiseRequest),
  );
}

export function activateRaiseRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActivateRaiseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateRaiseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateRaiseRequest' from JSON`,
  );
}

/** @internal */
export const ActivateRaiseData$inboundSchema: z.ZodType<
  ActivateRaiseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  type: OrganizationType$inboundSchema.optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  raise: Raise$inboundSchema.optional(),
});

/** @internal */
export type ActivateRaiseData$Outbound = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  raise?: Raise$Outbound | undefined;
};

/** @internal */
export const ActivateRaiseData$outboundSchema: z.ZodType<
  ActivateRaiseData$Outbound,
  z.ZodTypeDef,
  ActivateRaiseData
> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  type: OrganizationType$outboundSchema.optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  raise: Raise$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivateRaiseData$ {
  /** @deprecated use `ActivateRaiseData$inboundSchema` instead. */
  export const inboundSchema = ActivateRaiseData$inboundSchema;
  /** @deprecated use `ActivateRaiseData$outboundSchema` instead. */
  export const outboundSchema = ActivateRaiseData$outboundSchema;
  /** @deprecated use `ActivateRaiseData$Outbound` instead. */
  export type Outbound = ActivateRaiseData$Outbound;
}

export function activateRaiseDataToJSON(
  activateRaiseData: ActivateRaiseData,
): string {
  return JSON.stringify(
    ActivateRaiseData$outboundSchema.parse(activateRaiseData),
  );
}

export function activateRaiseDataFromJSON(
  jsonString: string,
): SafeParseResult<ActivateRaiseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateRaiseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateRaiseData' from JSON`,
  );
}

/** @internal */
export const ActivateRaiseResponseBody$inboundSchema: z.ZodType<
  ActivateRaiseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => ActivateRaiseData$inboundSchema).optional(),
});

/** @internal */
export type ActivateRaiseResponseBody$Outbound = {
  success: true;
  data?: ActivateRaiseData$Outbound | undefined;
};

/** @internal */
export const ActivateRaiseResponseBody$outboundSchema: z.ZodType<
  ActivateRaiseResponseBody$Outbound,
  z.ZodTypeDef,
  ActivateRaiseResponseBody
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => ActivateRaiseData$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivateRaiseResponseBody$ {
  /** @deprecated use `ActivateRaiseResponseBody$inboundSchema` instead. */
  export const inboundSchema = ActivateRaiseResponseBody$inboundSchema;
  /** @deprecated use `ActivateRaiseResponseBody$outboundSchema` instead. */
  export const outboundSchema = ActivateRaiseResponseBody$outboundSchema;
  /** @deprecated use `ActivateRaiseResponseBody$Outbound` instead. */
  export type Outbound = ActivateRaiseResponseBody$Outbound;
}

export function activateRaiseResponseBodyToJSON(
  activateRaiseResponseBody: ActivateRaiseResponseBody,
): string {
  return JSON.stringify(
    ActivateRaiseResponseBody$outboundSchema.parse(activateRaiseResponseBody),
  );
}

export function activateRaiseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ActivateRaiseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateRaiseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateRaiseResponseBody' from JSON`,
  );
}

/** @internal */
export const ActivateRaiseResponse$inboundSchema: z.ZodType<
  ActivateRaiseResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => ActivateRaiseResponseBody$inboundSchema),
]);

/** @internal */
export type ActivateRaiseResponse$Outbound =
  | Err$Outbound
  | ActivateRaiseResponseBody$Outbound;

/** @internal */
export const ActivateRaiseResponse$outboundSchema: z.ZodType<
  ActivateRaiseResponse$Outbound,
  z.ZodTypeDef,
  ActivateRaiseResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => ActivateRaiseResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivateRaiseResponse$ {
  /** @deprecated use `ActivateRaiseResponse$inboundSchema` instead. */
  export const inboundSchema = ActivateRaiseResponse$inboundSchema;
  /** @deprecated use `ActivateRaiseResponse$outboundSchema` instead. */
  export const outboundSchema = ActivateRaiseResponse$outboundSchema;
  /** @deprecated use `ActivateRaiseResponse$Outbound` instead. */
  export type Outbound = ActivateRaiseResponse$Outbound;
}

export function activateRaiseResponseToJSON(
  activateRaiseResponse: ActivateRaiseResponse,
): string {
  return JSON.stringify(
    ActivateRaiseResponse$outboundSchema.parse(activateRaiseResponse),
  );
}

export function activateRaiseResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActivateRaiseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateRaiseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateRaiseResponse' from JSON`,
  );
}
