/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Organization,
  Organization$inboundSchema,
  Organization$Outbound,
  Organization$outboundSchema,
} from "../components/organization.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "../components/organizationstatus.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ChangeOrganizationStatusRequestBody = {
  status: OrganizationStatus;
  /**
   * Optional reason for status change
   */
  reason?: string | undefined;
};

export type ChangeOrganizationStatusRequest = {
  id: number;
  requestBody: ChangeOrganizationStatusRequestBody;
};

/**
 * Success response wrapper
 */
export type ChangeOrganizationStatusResponseBody = {
  success: true;
  data?: Organization | undefined;
};

/** @internal */
export const ChangeOrganizationStatusRequestBody$inboundSchema: z.ZodType<
  ChangeOrganizationStatusRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: OrganizationStatus$inboundSchema,
  reason: z.string().optional(),
});

/** @internal */
export type ChangeOrganizationStatusRequestBody$Outbound = {
  status: string;
  reason?: string | undefined;
};

/** @internal */
export const ChangeOrganizationStatusRequestBody$outboundSchema: z.ZodType<
  ChangeOrganizationStatusRequestBody$Outbound,
  z.ZodTypeDef,
  ChangeOrganizationStatusRequestBody
> = z.object({
  status: OrganizationStatus$outboundSchema,
  reason: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChangeOrganizationStatusRequestBody$ {
  /** @deprecated use `ChangeOrganizationStatusRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    ChangeOrganizationStatusRequestBody$inboundSchema;
  /** @deprecated use `ChangeOrganizationStatusRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    ChangeOrganizationStatusRequestBody$outboundSchema;
  /** @deprecated use `ChangeOrganizationStatusRequestBody$Outbound` instead. */
  export type Outbound = ChangeOrganizationStatusRequestBody$Outbound;
}

export function changeOrganizationStatusRequestBodyToJSON(
  changeOrganizationStatusRequestBody: ChangeOrganizationStatusRequestBody,
): string {
  return JSON.stringify(
    ChangeOrganizationStatusRequestBody$outboundSchema.parse(
      changeOrganizationStatusRequestBody,
    ),
  );
}

export function changeOrganizationStatusRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ChangeOrganizationStatusRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChangeOrganizationStatusRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangeOrganizationStatusRequestBody' from JSON`,
  );
}

/** @internal */
export const ChangeOrganizationStatusRequest$inboundSchema: z.ZodType<
  ChangeOrganizationStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  RequestBody: z.lazy(() => ChangeOrganizationStatusRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type ChangeOrganizationStatusRequest$Outbound = {
  id: number;
  RequestBody: ChangeOrganizationStatusRequestBody$Outbound;
};

/** @internal */
export const ChangeOrganizationStatusRequest$outboundSchema: z.ZodType<
  ChangeOrganizationStatusRequest$Outbound,
  z.ZodTypeDef,
  ChangeOrganizationStatusRequest
> = z.object({
  id: z.number().int(),
  requestBody: z.lazy(() => ChangeOrganizationStatusRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChangeOrganizationStatusRequest$ {
  /** @deprecated use `ChangeOrganizationStatusRequest$inboundSchema` instead. */
  export const inboundSchema = ChangeOrganizationStatusRequest$inboundSchema;
  /** @deprecated use `ChangeOrganizationStatusRequest$outboundSchema` instead. */
  export const outboundSchema = ChangeOrganizationStatusRequest$outboundSchema;
  /** @deprecated use `ChangeOrganizationStatusRequest$Outbound` instead. */
  export type Outbound = ChangeOrganizationStatusRequest$Outbound;
}

export function changeOrganizationStatusRequestToJSON(
  changeOrganizationStatusRequest: ChangeOrganizationStatusRequest,
): string {
  return JSON.stringify(
    ChangeOrganizationStatusRequest$outboundSchema.parse(
      changeOrganizationStatusRequest,
    ),
  );
}

export function changeOrganizationStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<ChangeOrganizationStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChangeOrganizationStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangeOrganizationStatusRequest' from JSON`,
  );
}

/** @internal */
export const ChangeOrganizationStatusResponseBody$inboundSchema: z.ZodType<
  ChangeOrganizationStatusResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: Organization$inboundSchema.optional(),
});

/** @internal */
export type ChangeOrganizationStatusResponseBody$Outbound = {
  success: true;
  data?: Organization$Outbound | undefined;
};

/** @internal */
export const ChangeOrganizationStatusResponseBody$outboundSchema: z.ZodType<
  ChangeOrganizationStatusResponseBody$Outbound,
  z.ZodTypeDef,
  ChangeOrganizationStatusResponseBody
> = z.object({
  success: z.literal(true),
  data: Organization$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChangeOrganizationStatusResponseBody$ {
  /** @deprecated use `ChangeOrganizationStatusResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ChangeOrganizationStatusResponseBody$inboundSchema;
  /** @deprecated use `ChangeOrganizationStatusResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ChangeOrganizationStatusResponseBody$outboundSchema;
  /** @deprecated use `ChangeOrganizationStatusResponseBody$Outbound` instead. */
  export type Outbound = ChangeOrganizationStatusResponseBody$Outbound;
}

export function changeOrganizationStatusResponseBodyToJSON(
  changeOrganizationStatusResponseBody: ChangeOrganizationStatusResponseBody,
): string {
  return JSON.stringify(
    ChangeOrganizationStatusResponseBody$outboundSchema.parse(
      changeOrganizationStatusResponseBody,
    ),
  );
}

export function changeOrganizationStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ChangeOrganizationStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChangeOrganizationStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangeOrganizationStatusResponseBody' from JSON`,
  );
}
