/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateNonceRequestBody = {
  /**
   * The EVM wallet address
   */
  address: string;
};

export type Data = {
  nonce?: number | undefined;
};

/**
 * Success response wrapper
 */
export type CreateNonceResponseBody = {
  success: true;
  data?: Data | undefined;
};

export type CreateNonceResponse = Err | CreateNonceResponseBody;

/** @internal */
export const CreateNonceRequestBody$inboundSchema: z.ZodType<
  CreateNonceRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
});

/** @internal */
export type CreateNonceRequestBody$Outbound = {
  address: string;
};

/** @internal */
export const CreateNonceRequestBody$outboundSchema: z.ZodType<
  CreateNonceRequestBody$Outbound,
  z.ZodTypeDef,
  CreateNonceRequestBody
> = z.object({
  address: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateNonceRequestBody$ {
  /** @deprecated use `CreateNonceRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateNonceRequestBody$inboundSchema;
  /** @deprecated use `CreateNonceRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateNonceRequestBody$outboundSchema;
  /** @deprecated use `CreateNonceRequestBody$Outbound` instead. */
  export type Outbound = CreateNonceRequestBody$Outbound;
}

export function createNonceRequestBodyToJSON(
  createNonceRequestBody: CreateNonceRequestBody,
): string {
  return JSON.stringify(
    CreateNonceRequestBody$outboundSchema.parse(createNonceRequestBody),
  );
}

export function createNonceRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateNonceRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateNonceRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateNonceRequestBody' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    nonce: z.number().int().optional(),
  });

/** @internal */
export type Data$Outbound = {
  nonce?: number | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    nonce: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const CreateNonceResponseBody$inboundSchema: z.ZodType<
  CreateNonceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$inboundSchema).optional(),
});

/** @internal */
export type CreateNonceResponseBody$Outbound = {
  success: true;
  data?: Data$Outbound | undefined;
};

/** @internal */
export const CreateNonceResponseBody$outboundSchema: z.ZodType<
  CreateNonceResponseBody$Outbound,
  z.ZodTypeDef,
  CreateNonceResponseBody
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateNonceResponseBody$ {
  /** @deprecated use `CreateNonceResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateNonceResponseBody$inboundSchema;
  /** @deprecated use `CreateNonceResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateNonceResponseBody$outboundSchema;
  /** @deprecated use `CreateNonceResponseBody$Outbound` instead. */
  export type Outbound = CreateNonceResponseBody$Outbound;
}

export function createNonceResponseBodyToJSON(
  createNonceResponseBody: CreateNonceResponseBody,
): string {
  return JSON.stringify(
    CreateNonceResponseBody$outboundSchema.parse(createNonceResponseBody),
  );
}

export function createNonceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateNonceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateNonceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateNonceResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateNonceResponse$inboundSchema: z.ZodType<
  CreateNonceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => CreateNonceResponseBody$inboundSchema),
]);

/** @internal */
export type CreateNonceResponse$Outbound =
  | Err$Outbound
  | CreateNonceResponseBody$Outbound;

/** @internal */
export const CreateNonceResponse$outboundSchema: z.ZodType<
  CreateNonceResponse$Outbound,
  z.ZodTypeDef,
  CreateNonceResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => CreateNonceResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateNonceResponse$ {
  /** @deprecated use `CreateNonceResponse$inboundSchema` instead. */
  export const inboundSchema = CreateNonceResponse$inboundSchema;
  /** @deprecated use `CreateNonceResponse$outboundSchema` instead. */
  export const outboundSchema = CreateNonceResponse$outboundSchema;
  /** @deprecated use `CreateNonceResponse$Outbound` instead. */
  export type Outbound = CreateNonceResponse$Outbound;
}

export function createNonceResponseToJSON(
  createNonceResponse: CreateNonceResponse,
): string {
  return JSON.stringify(
    CreateNonceResponse$outboundSchema.parse(createNonceResponse),
  );
}

export function createNonceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateNonceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateNonceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateNonceResponse' from JSON`,
  );
}
