/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "../components/proposal.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success response wrapper
 */
export type CreateProposalResponseBody = {
  success: true;
  data?: Proposal | undefined;
};

export type CreateProposalResponse = Err | CreateProposalResponseBody;

/** @internal */
export const CreateProposalResponseBody$inboundSchema: z.ZodType<
  CreateProposalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: Proposal$inboundSchema.optional(),
});

/** @internal */
export type CreateProposalResponseBody$Outbound = {
  success: true;
  data?: Proposal$Outbound | undefined;
};

/** @internal */
export const CreateProposalResponseBody$outboundSchema: z.ZodType<
  CreateProposalResponseBody$Outbound,
  z.ZodTypeDef,
  CreateProposalResponseBody
> = z.object({
  success: z.literal(true),
  data: Proposal$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProposalResponseBody$ {
  /** @deprecated use `CreateProposalResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateProposalResponseBody$inboundSchema;
  /** @deprecated use `CreateProposalResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateProposalResponseBody$outboundSchema;
  /** @deprecated use `CreateProposalResponseBody$Outbound` instead. */
  export type Outbound = CreateProposalResponseBody$Outbound;
}

export function createProposalResponseBodyToJSON(
  createProposalResponseBody: CreateProposalResponseBody,
): string {
  return JSON.stringify(
    CreateProposalResponseBody$outboundSchema.parse(createProposalResponseBody),
  );
}

export function createProposalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateProposalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProposalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProposalResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateProposalResponse$inboundSchema: z.ZodType<
  CreateProposalResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => CreateProposalResponseBody$inboundSchema),
]);

/** @internal */
export type CreateProposalResponse$Outbound =
  | Err$Outbound
  | CreateProposalResponseBody$Outbound;

/** @internal */
export const CreateProposalResponse$outboundSchema: z.ZodType<
  CreateProposalResponse$Outbound,
  z.ZodTypeDef,
  CreateProposalResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => CreateProposalResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProposalResponse$ {
  /** @deprecated use `CreateProposalResponse$inboundSchema` instead. */
  export const inboundSchema = CreateProposalResponse$inboundSchema;
  /** @deprecated use `CreateProposalResponse$outboundSchema` instead. */
  export const outboundSchema = CreateProposalResponse$outboundSchema;
  /** @deprecated use `CreateProposalResponse$Outbound` instead. */
  export type Outbound = CreateProposalResponse$Outbound;
}

export function createProposalResponseToJSON(
  createProposalResponse: CreateProposalResponse,
): string {
  return JSON.stringify(
    CreateProposalResponse$outboundSchema.parse(createProposalResponse),
  );
}

export function createProposalResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateProposalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProposalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProposalResponse' from JSON`,
  );
}
