/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Proposal created
 */
export type CreateProposalResponseBody = {
  success: boolean;
  data?: components.Proposal | undefined;
};

/** @internal */
export const CreateProposalResponseBody$inboundSchema: z.ZodType<
  CreateProposalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: components.Proposal$inboundSchema.optional(),
});

/** @internal */
export type CreateProposalResponseBody$Outbound = {
  success: boolean;
  data?: components.Proposal$Outbound | undefined;
};

/** @internal */
export const CreateProposalResponseBody$outboundSchema: z.ZodType<
  CreateProposalResponseBody$Outbound,
  z.ZodTypeDef,
  CreateProposalResponseBody
> = z.object({
  success: z.boolean(),
  data: components.Proposal$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProposalResponseBody$ {
  /** @deprecated use `CreateProposalResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateProposalResponseBody$inboundSchema;
  /** @deprecated use `CreateProposalResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateProposalResponseBody$outboundSchema;
  /** @deprecated use `CreateProposalResponseBody$Outbound` instead. */
  export type Outbound = CreateProposalResponseBody$Outbound;
}

export function createProposalResponseBodyToJSON(
  createProposalResponseBody: CreateProposalResponseBody,
): string {
  return JSON.stringify(
    CreateProposalResponseBody$outboundSchema.parse(createProposalResponseBody),
  );
}

export function createProposalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateProposalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProposalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProposalResponseBody' from JSON`,
  );
}
