/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteProposalRequest = {
  id: number;
};

/**
 * Deleted
 */
export type DeleteProposalResponseBody = {
  success: true;
};

/** @internal */
export const DeleteProposalRequest$inboundSchema: z.ZodType<
  DeleteProposalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteProposalRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteProposalRequest$outboundSchema: z.ZodType<
  DeleteProposalRequest$Outbound,
  z.ZodTypeDef,
  DeleteProposalRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteProposalRequest$ {
  /** @deprecated use `DeleteProposalRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteProposalRequest$inboundSchema;
  /** @deprecated use `DeleteProposalRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteProposalRequest$outboundSchema;
  /** @deprecated use `DeleteProposalRequest$Outbound` instead. */
  export type Outbound = DeleteProposalRequest$Outbound;
}

export function deleteProposalRequestToJSON(
  deleteProposalRequest: DeleteProposalRequest,
): string {
  return JSON.stringify(
    DeleteProposalRequest$outboundSchema.parse(deleteProposalRequest),
  );
}

export function deleteProposalRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteProposalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteProposalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteProposalRequest' from JSON`,
  );
}

/** @internal */
export const DeleteProposalResponseBody$inboundSchema: z.ZodType<
  DeleteProposalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
});

/** @internal */
export type DeleteProposalResponseBody$Outbound = {
  success: true;
};

/** @internal */
export const DeleteProposalResponseBody$outboundSchema: z.ZodType<
  DeleteProposalResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteProposalResponseBody
> = z.object({
  success: z.literal(true),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteProposalResponseBody$ {
  /** @deprecated use `DeleteProposalResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteProposalResponseBody$inboundSchema;
  /** @deprecated use `DeleteProposalResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteProposalResponseBody$outboundSchema;
  /** @deprecated use `DeleteProposalResponseBody$Outbound` instead. */
  export type Outbound = DeleteProposalResponseBody$Outbound;
}

export function deleteProposalResponseBodyToJSON(
  deleteProposalResponseBody: DeleteProposalResponseBody,
): string {
  return JSON.stringify(
    DeleteProposalResponseBody$outboundSchema.parse(deleteProposalResponseBody),
  );
}

export function deleteProposalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteProposalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteProposalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteProposalResponseBody' from JSON`,
  );
}
