/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Image = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type Banner = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type EditOrganizationRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
  image?: Image | Blob | undefined;
  banner?: Banner | Blob | undefined;
  /**
   * JSON array of links
   */
  links?: string | undefined;
};

export type EditOrganizationRequest = {
  id: number;
  requestBody?: EditOrganizationRequestBody | undefined;
};

/** @internal */
export const Image$inboundSchema: z.ZodType<Image, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type Image$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Image$outboundSchema: z.ZodType<
  Image$Outbound,
  z.ZodTypeDef,
  Image
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Image$ {
  /** @deprecated use `Image$inboundSchema` instead. */
  export const inboundSchema = Image$inboundSchema;
  /** @deprecated use `Image$outboundSchema` instead. */
  export const outboundSchema = Image$outboundSchema;
  /** @deprecated use `Image$Outbound` instead. */
  export type Outbound = Image$Outbound;
}

export function imageToJSON(image: Image): string {
  return JSON.stringify(Image$outboundSchema.parse(image));
}

export function imageFromJSON(
  jsonString: string,
): SafeParseResult<Image, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Image$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Image' from JSON`,
  );
}

/** @internal */
export const Banner$inboundSchema: z.ZodType<Banner, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type Banner$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Banner$outboundSchema: z.ZodType<
  Banner$Outbound,
  z.ZodTypeDef,
  Banner
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Banner$ {
  /** @deprecated use `Banner$inboundSchema` instead. */
  export const inboundSchema = Banner$inboundSchema;
  /** @deprecated use `Banner$outboundSchema` instead. */
  export const outboundSchema = Banner$outboundSchema;
  /** @deprecated use `Banner$Outbound` instead. */
  export type Outbound = Banner$Outbound;
}

export function bannerToJSON(banner: Banner): string {
  return JSON.stringify(Banner$outboundSchema.parse(banner));
}

export function bannerFromJSON(
  jsonString: string,
): SafeParseResult<Banner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Banner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Banner' from JSON`,
  );
}

/** @internal */
export const EditOrganizationRequestBody$inboundSchema: z.ZodType<
  EditOrganizationRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  image: z.lazy(() => Image$inboundSchema).optional(),
  banner: z.lazy(() => Banner$inboundSchema).optional(),
  links: z.string().optional(),
});

/** @internal */
export type EditOrganizationRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  image?: Image$Outbound | Blob | undefined;
  banner?: Banner$Outbound | Blob | undefined;
  links?: string | undefined;
};

/** @internal */
export const EditOrganizationRequestBody$outboundSchema: z.ZodType<
  EditOrganizationRequestBody$Outbound,
  z.ZodTypeDef,
  EditOrganizationRequestBody
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  image: z.lazy(() => Image$outboundSchema).or(blobLikeSchema).optional(),
  banner: z.lazy(() => Banner$outboundSchema).or(blobLikeSchema).optional(),
  links: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EditOrganizationRequestBody$ {
  /** @deprecated use `EditOrganizationRequestBody$inboundSchema` instead. */
  export const inboundSchema = EditOrganizationRequestBody$inboundSchema;
  /** @deprecated use `EditOrganizationRequestBody$outboundSchema` instead. */
  export const outboundSchema = EditOrganizationRequestBody$outboundSchema;
  /** @deprecated use `EditOrganizationRequestBody$Outbound` instead. */
  export type Outbound = EditOrganizationRequestBody$Outbound;
}

export function editOrganizationRequestBodyToJSON(
  editOrganizationRequestBody: EditOrganizationRequestBody,
): string {
  return JSON.stringify(
    EditOrganizationRequestBody$outboundSchema.parse(
      editOrganizationRequestBody,
    ),
  );
}

export function editOrganizationRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<EditOrganizationRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditOrganizationRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditOrganizationRequestBody' from JSON`,
  );
}

/** @internal */
export const EditOrganizationRequest$inboundSchema: z.ZodType<
  EditOrganizationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  RequestBody: z.lazy(() => EditOrganizationRequestBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type EditOrganizationRequest$Outbound = {
  id: number;
  RequestBody?: EditOrganizationRequestBody$Outbound | undefined;
};

/** @internal */
export const EditOrganizationRequest$outboundSchema: z.ZodType<
  EditOrganizationRequest$Outbound,
  z.ZodTypeDef,
  EditOrganizationRequest
> = z.object({
  id: z.number().int(),
  requestBody: z.lazy(() => EditOrganizationRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EditOrganizationRequest$ {
  /** @deprecated use `EditOrganizationRequest$inboundSchema` instead. */
  export const inboundSchema = EditOrganizationRequest$inboundSchema;
  /** @deprecated use `EditOrganizationRequest$outboundSchema` instead. */
  export const outboundSchema = EditOrganizationRequest$outboundSchema;
  /** @deprecated use `EditOrganizationRequest$Outbound` instead. */
  export type Outbound = EditOrganizationRequest$Outbound;
}

export function editOrganizationRequestToJSON(
  editOrganizationRequest: EditOrganizationRequest,
): string {
  return JSON.stringify(
    EditOrganizationRequest$outboundSchema.parse(editOrganizationRequest),
  );
}

export function editOrganizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<EditOrganizationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditOrganizationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditOrganizationRequest' from JSON`,
  );
}
