/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetNonceRequestBody = {
  /**
   * The EVM wallet address
   */
  address: string;
};

export type Data = {
  nonce?: number | undefined;
};

/**
 * Nonce generated successfully
 */
export type GetNonceResponseBody = {
  success: boolean;
  data?: Data | undefined;
};

/** @internal */
export const GetNonceRequestBody$inboundSchema: z.ZodType<
  GetNonceRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
});

/** @internal */
export type GetNonceRequestBody$Outbound = {
  address: string;
};

/** @internal */
export const GetNonceRequestBody$outboundSchema: z.ZodType<
  GetNonceRequestBody$Outbound,
  z.ZodTypeDef,
  GetNonceRequestBody
> = z.object({
  address: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetNonceRequestBody$ {
  /** @deprecated use `GetNonceRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetNonceRequestBody$inboundSchema;
  /** @deprecated use `GetNonceRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetNonceRequestBody$outboundSchema;
  /** @deprecated use `GetNonceRequestBody$Outbound` instead. */
  export type Outbound = GetNonceRequestBody$Outbound;
}

export function getNonceRequestBodyToJSON(
  getNonceRequestBody: GetNonceRequestBody,
): string {
  return JSON.stringify(
    GetNonceRequestBody$outboundSchema.parse(getNonceRequestBody),
  );
}

export function getNonceRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetNonceRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNonceRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNonceRequestBody' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    nonce: z.number().int().optional(),
  });

/** @internal */
export type Data$Outbound = {
  nonce?: number | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    nonce: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GetNonceResponseBody$inboundSchema: z.ZodType<
  GetNonceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => Data$inboundSchema).optional(),
});

/** @internal */
export type GetNonceResponseBody$Outbound = {
  success: boolean;
  data?: Data$Outbound | undefined;
};

/** @internal */
export const GetNonceResponseBody$outboundSchema: z.ZodType<
  GetNonceResponseBody$Outbound,
  z.ZodTypeDef,
  GetNonceResponseBody
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => Data$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetNonceResponseBody$ {
  /** @deprecated use `GetNonceResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetNonceResponseBody$inboundSchema;
  /** @deprecated use `GetNonceResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetNonceResponseBody$outboundSchema;
  /** @deprecated use `GetNonceResponseBody$Outbound` instead. */
  export type Outbound = GetNonceResponseBody$Outbound;
}

export function getNonceResponseBodyToJSON(
  getNonceResponseBody: GetNonceResponseBody,
): string {
  return JSON.stringify(
    GetNonceResponseBody$outboundSchema.parse(getNonceResponseBody),
  );
}

export function getNonceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetNonceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNonceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNonceResponseBody' from JSON`,
  );
}
