/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationSecurity = {
  bearerAuth?: string | undefined;
};

export type GetOrganizationRequest = {
  slug: string;
};

export const Type = {
  External: "external",
  Ico: "ico",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type RaiseRaise = {
  id?: number | undefined;
  /**
   * EVM address of the raise contract
   */
  address?: string | null | undefined;
  softCap: number;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: Date | null | undefined;
  endDate?: Date | null | undefined;
  status?: components.RaiseStatus | undefined;
  allocations?: Array<components.RaiseAllocation> | undefined;
  contributions?: Array<components.RaiseContribution> | undefined;
};

export type Data = {
  id?: number | undefined;
  type: Type;
  name: string;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description: string;
  status?: components.OrganizationStatus | undefined;
  links?: Array<components.Link> | undefined;
  contactInformation?: Array<components.ContactInformation> | undefined;
  token?: components.Token | undefined;
  treasury?: components.Treasury | undefined;
  /**
   * Only present for ICO organizations
   */
  raise?: RaiseRaise | null | undefined;
  user?: components.User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals: Array<components.Proposal>;
};

/**
 * Success response wrapper
 */
export type GetOrganizationResponseBody = {
  success: true;
  data: Data;
};

/** @internal */
export const GetOrganizationSecurity$inboundSchema: z.ZodType<
  GetOrganizationSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetOrganizationSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetOrganizationSecurity$outboundSchema: z.ZodType<
  GetOrganizationSecurity$Outbound,
  z.ZodTypeDef,
  GetOrganizationSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationSecurity$ {
  /** @deprecated use `GetOrganizationSecurity$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationSecurity$inboundSchema;
  /** @deprecated use `GetOrganizationSecurity$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationSecurity$outboundSchema;
  /** @deprecated use `GetOrganizationSecurity$Outbound` instead. */
  export type Outbound = GetOrganizationSecurity$Outbound;
}

export function getOrganizationSecurityToJSON(
  getOrganizationSecurity: GetOrganizationSecurity,
): string {
  return JSON.stringify(
    GetOrganizationSecurity$outboundSchema.parse(getOrganizationSecurity),
  );
}

export function getOrganizationSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationSecurity' from JSON`,
  );
}

/** @internal */
export const GetOrganizationRequest$inboundSchema: z.ZodType<
  GetOrganizationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetOrganizationRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodType<
  GetOrganizationRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationRequest$ {
  /** @deprecated use `GetOrganizationRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationRequest$inboundSchema;
  /** @deprecated use `GetOrganizationRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationRequest$outboundSchema;
  /** @deprecated use `GetOrganizationRequest$Outbound` instead. */
  export type Outbound = GetOrganizationRequest$Outbound;
}

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}

export function getOrganizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationRequest' from JSON`,
  );
}

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const RaiseRaise$inboundSchema: z.ZodType<
  RaiseRaise,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  address: z.nullable(z.string()).optional(),
  softCap: z.number(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  endDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  status: components.RaiseStatus$inboundSchema.optional(),
  allocations: z.array(components.RaiseAllocation$inboundSchema).optional(),
  contributions: z.array(components.RaiseContribution$inboundSchema).optional(),
});

/** @internal */
export type RaiseRaise$Outbound = {
  id?: number | undefined;
  address?: string | null | undefined;
  softCap: number;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: string | null | undefined;
  endDate?: string | null | undefined;
  status?: string | undefined;
  allocations?: Array<components.RaiseAllocation$Outbound> | undefined;
  contributions?: Array<components.RaiseContribution$Outbound> | undefined;
};

/** @internal */
export const RaiseRaise$outboundSchema: z.ZodType<
  RaiseRaise$Outbound,
  z.ZodTypeDef,
  RaiseRaise
> = z.object({
  id: z.number().int().optional(),
  address: z.nullable(z.string()).optional(),
  softCap: z.number(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  endDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  status: components.RaiseStatus$outboundSchema.optional(),
  allocations: z.array(components.RaiseAllocation$outboundSchema).optional(),
  contributions: z.array(components.RaiseContribution$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RaiseRaise$ {
  /** @deprecated use `RaiseRaise$inboundSchema` instead. */
  export const inboundSchema = RaiseRaise$inboundSchema;
  /** @deprecated use `RaiseRaise$outboundSchema` instead. */
  export const outboundSchema = RaiseRaise$outboundSchema;
  /** @deprecated use `RaiseRaise$Outbound` instead. */
  export type Outbound = RaiseRaise$Outbound;
}

export function raiseRaiseToJSON(raiseRaise: RaiseRaise): string {
  return JSON.stringify(RaiseRaise$outboundSchema.parse(raiseRaise));
}

export function raiseRaiseFromJSON(
  jsonString: string,
): SafeParseResult<RaiseRaise, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RaiseRaise$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RaiseRaise' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    type: Type$inboundSchema,
    name: z.string(),
    slug: z.string().optional(),
    image: z.string().optional(),
    banner: z.string().optional(),
    description: z.string(),
    status: components.OrganizationStatus$inboundSchema.optional(),
    links: z.array(components.Link$inboundSchema).optional(),
    contactInformation: z.array(components.ContactInformation$inboundSchema)
      .optional(),
    token: components.Token$inboundSchema.optional(),
    treasury: components.Treasury$inboundSchema.optional(),
    raise: z.nullable(z.lazy(() => RaiseRaise$inboundSchema)).optional(),
    user: components.User$inboundSchema.optional(),
    created: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    proposals: z.array(components.Proposal$inboundSchema),
  });

/** @internal */
export type Data$Outbound = {
  id?: number | undefined;
  type: string;
  name: string;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description: string;
  status?: string | undefined;
  links?: Array<components.Link$Outbound> | undefined;
  contactInformation?:
    | Array<components.ContactInformation$Outbound>
    | undefined;
  token?: components.Token$Outbound | undefined;
  treasury?: components.Treasury$Outbound | undefined;
  raise?: RaiseRaise$Outbound | null | undefined;
  user?: components.User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals: Array<components.Proposal$Outbound>;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    id: z.number().int().optional(),
    type: Type$outboundSchema,
    name: z.string(),
    slug: z.string().optional(),
    image: z.string().optional(),
    banner: z.string().optional(),
    description: z.string(),
    status: components.OrganizationStatus$outboundSchema.optional(),
    links: z.array(components.Link$outboundSchema).optional(),
    contactInformation: z.array(components.ContactInformation$outboundSchema)
      .optional(),
    token: components.Token$outboundSchema.optional(),
    treasury: components.Treasury$outboundSchema.optional(),
    raise: z.nullable(z.lazy(() => RaiseRaise$outboundSchema)).optional(),
    user: components.User$outboundSchema.optional(),
    created: z.date().transform(v => v.toISOString()).optional(),
    updated: z.date().transform(v => v.toISOString()).optional(),
    proposals: z.array(components.Proposal$outboundSchema),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GetOrganizationResponseBody$inboundSchema: z.ZodType<
  GetOrganizationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$inboundSchema),
});

/** @internal */
export type GetOrganizationResponseBody$Outbound = {
  success: true;
  data: Data$Outbound;
};

/** @internal */
export const GetOrganizationResponseBody$outboundSchema: z.ZodType<
  GetOrganizationResponseBody$Outbound,
  z.ZodTypeDef,
  GetOrganizationResponseBody
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationResponseBody$ {
  /** @deprecated use `GetOrganizationResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationResponseBody$inboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationResponseBody$outboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$Outbound` instead. */
  export type Outbound = GetOrganizationResponseBody$Outbound;
}

export function getOrganizationResponseBodyToJSON(
  getOrganizationResponseBody: GetOrganizationResponseBody,
): string {
  return JSON.stringify(
    GetOrganizationResponseBody$outboundSchema.parse(
      getOrganizationResponseBody,
    ),
  );
}

export function getOrganizationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponseBody' from JSON`,
  );
}
