/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "../components/contactinformation.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "../components/link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "../components/organizationstatus.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "../components/proposal.js";
import {
  RaiseAllocation,
  RaiseAllocation$inboundSchema,
  RaiseAllocation$Outbound,
  RaiseAllocation$outboundSchema,
} from "../components/raiseallocation.js";
import {
  RaiseContribution,
  RaiseContribution$inboundSchema,
  RaiseContribution$Outbound,
  RaiseContribution$outboundSchema,
} from "../components/raisecontribution.js";
import {
  RaiseStatus,
  RaiseStatus$inboundSchema,
  RaiseStatus$outboundSchema,
} from "../components/raisestatus.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "../components/token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "../components/treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "../components/user.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationSecurity = {
  bearerAuth?: string | undefined;
};

export type GetOrganizationRequest = {
  slug: string;
};

export type DataRaise = {
  id?: number | undefined;
  /**
   * EVM address of the raise contract
   */
  address?: string | null | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: Date | null | undefined;
  endDate?: Date | null | undefined;
  status?: RaiseStatus | undefined;
  allocations?: Array<RaiseAllocation> | undefined;
  contributions?: Array<RaiseContribution> | undefined;
  /**
   * Token allowance amount
   */
  allowance?: number | undefined;
};

export type DataIcoOrganization = {
  type: "ico";
  raise: DataRaise;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals: Array<Proposal>;
};

export type DataExternalOrganization = {
  type: "external";
  token: Token;
  /**
   * Token supply for treasury
   */
  tokenSupply: number;
  /**
   * USDC supply for treasury
   */
  usdcSupply: number;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals: Array<Proposal>;
};

export type GetOrganizationData =
  | (DataExternalOrganization & { type: "external" })
  | (DataIcoOrganization & { type: "ico" });

/**
 * Success response wrapper
 */
export type GetOrganizationResponseBody = {
  success: true;
  data:
    | (DataExternalOrganization & { type: "external" })
    | (DataIcoOrganization & { type: "ico" });
};

export type GetOrganizationResponse = GetOrganizationResponseBody | Err;

/** @internal */
export const GetOrganizationSecurity$inboundSchema: z.ZodType<
  GetOrganizationSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetOrganizationSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetOrganizationSecurity$outboundSchema: z.ZodType<
  GetOrganizationSecurity$Outbound,
  z.ZodTypeDef,
  GetOrganizationSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationSecurity$ {
  /** @deprecated use `GetOrganizationSecurity$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationSecurity$inboundSchema;
  /** @deprecated use `GetOrganizationSecurity$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationSecurity$outboundSchema;
  /** @deprecated use `GetOrganizationSecurity$Outbound` instead. */
  export type Outbound = GetOrganizationSecurity$Outbound;
}

export function getOrganizationSecurityToJSON(
  getOrganizationSecurity: GetOrganizationSecurity,
): string {
  return JSON.stringify(
    GetOrganizationSecurity$outboundSchema.parse(getOrganizationSecurity),
  );
}

export function getOrganizationSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationSecurity' from JSON`,
  );
}

/** @internal */
export const GetOrganizationRequest$inboundSchema: z.ZodType<
  GetOrganizationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetOrganizationRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodType<
  GetOrganizationRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationRequest$ {
  /** @deprecated use `GetOrganizationRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationRequest$inboundSchema;
  /** @deprecated use `GetOrganizationRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationRequest$outboundSchema;
  /** @deprecated use `GetOrganizationRequest$Outbound` instead. */
  export type Outbound = GetOrganizationRequest$Outbound;
}

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}

export function getOrganizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationRequest' from JSON`,
  );
}

/** @internal */
export const DataRaise$inboundSchema: z.ZodType<
  DataRaise,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  address: z.nullable(z.string()).optional(),
  softCap: z.number().optional(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  endDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  status: RaiseStatus$inboundSchema.optional(),
  allocations: z.array(RaiseAllocation$inboundSchema).optional(),
  contributions: z.array(RaiseContribution$inboundSchema).optional(),
  allowance: z.number().optional(),
});

/** @internal */
export type DataRaise$Outbound = {
  id?: number | undefined;
  address?: string | null | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: string | null | undefined;
  endDate?: string | null | undefined;
  status?: string | undefined;
  allocations?: Array<RaiseAllocation$Outbound> | undefined;
  contributions?: Array<RaiseContribution$Outbound> | undefined;
  allowance?: number | undefined;
};

/** @internal */
export const DataRaise$outboundSchema: z.ZodType<
  DataRaise$Outbound,
  z.ZodTypeDef,
  DataRaise
> = z.object({
  id: z.number().int().optional(),
  address: z.nullable(z.string()).optional(),
  softCap: z.number().optional(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  endDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  status: RaiseStatus$outboundSchema.optional(),
  allocations: z.array(RaiseAllocation$outboundSchema).optional(),
  contributions: z.array(RaiseContribution$outboundSchema).optional(),
  allowance: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataRaise$ {
  /** @deprecated use `DataRaise$inboundSchema` instead. */
  export const inboundSchema = DataRaise$inboundSchema;
  /** @deprecated use `DataRaise$outboundSchema` instead. */
  export const outboundSchema = DataRaise$outboundSchema;
  /** @deprecated use `DataRaise$Outbound` instead. */
  export type Outbound = DataRaise$Outbound;
}

export function dataRaiseToJSON(dataRaise: DataRaise): string {
  return JSON.stringify(DataRaise$outboundSchema.parse(dataRaise));
}

export function dataRaiseFromJSON(
  jsonString: string,
): SafeParseResult<DataRaise, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataRaise$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataRaise' from JSON`,
  );
}

/** @internal */
export const DataIcoOrganization$inboundSchema: z.ZodType<
  DataIcoOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("ico"),
  raise: z.lazy(() => DataRaise$inboundSchema),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  proposals: z.array(Proposal$inboundSchema),
});

/** @internal */
export type DataIcoOrganization$Outbound = {
  type: "ico";
  raise: DataRaise$Outbound;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals: Array<Proposal$Outbound>;
};

/** @internal */
export const DataIcoOrganization$outboundSchema: z.ZodType<
  DataIcoOrganization$Outbound,
  z.ZodTypeDef,
  DataIcoOrganization
> = z.object({
  type: z.literal("ico"),
  raise: z.lazy(() => DataRaise$outboundSchema),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  proposals: z.array(Proposal$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataIcoOrganization$ {
  /** @deprecated use `DataIcoOrganization$inboundSchema` instead. */
  export const inboundSchema = DataIcoOrganization$inboundSchema;
  /** @deprecated use `DataIcoOrganization$outboundSchema` instead. */
  export const outboundSchema = DataIcoOrganization$outboundSchema;
  /** @deprecated use `DataIcoOrganization$Outbound` instead. */
  export type Outbound = DataIcoOrganization$Outbound;
}

export function dataIcoOrganizationToJSON(
  dataIcoOrganization: DataIcoOrganization,
): string {
  return JSON.stringify(
    DataIcoOrganization$outboundSchema.parse(dataIcoOrganization),
  );
}

export function dataIcoOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DataIcoOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataIcoOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataIcoOrganization' from JSON`,
  );
}

/** @internal */
export const DataExternalOrganization$inboundSchema: z.ZodType<
  DataExternalOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("external"),
  token: Token$inboundSchema,
  tokenSupply: z.number(),
  usdcSupply: z.number(),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  proposals: z.array(Proposal$inboundSchema),
});

/** @internal */
export type DataExternalOrganization$Outbound = {
  type: "external";
  token: Token$Outbound;
  tokenSupply: number;
  usdcSupply: number;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals: Array<Proposal$Outbound>;
};

/** @internal */
export const DataExternalOrganization$outboundSchema: z.ZodType<
  DataExternalOrganization$Outbound,
  z.ZodTypeDef,
  DataExternalOrganization
> = z.object({
  type: z.literal("external"),
  token: Token$outboundSchema,
  tokenSupply: z.number(),
  usdcSupply: z.number(),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  proposals: z.array(Proposal$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataExternalOrganization$ {
  /** @deprecated use `DataExternalOrganization$inboundSchema` instead. */
  export const inboundSchema = DataExternalOrganization$inboundSchema;
  /** @deprecated use `DataExternalOrganization$outboundSchema` instead. */
  export const outboundSchema = DataExternalOrganization$outboundSchema;
  /** @deprecated use `DataExternalOrganization$Outbound` instead. */
  export type Outbound = DataExternalOrganization$Outbound;
}

export function dataExternalOrganizationToJSON(
  dataExternalOrganization: DataExternalOrganization,
): string {
  return JSON.stringify(
    DataExternalOrganization$outboundSchema.parse(dataExternalOrganization),
  );
}

export function dataExternalOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<DataExternalOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataExternalOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataExternalOrganization' from JSON`,
  );
}

/** @internal */
export const GetOrganizationData$inboundSchema: z.ZodType<
  GetOrganizationData,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DataExternalOrganization$inboundSchema).and(
    z.object({ type: z.literal("external") }).transform((v) => ({
      type: v.type,
    })),
  ),
  z.lazy(() => DataIcoOrganization$inboundSchema).and(
    z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
  ),
]);

/** @internal */
export type GetOrganizationData$Outbound =
  | (DataExternalOrganization$Outbound & { type: "external" })
  | (DataIcoOrganization$Outbound & { type: "ico" });

/** @internal */
export const GetOrganizationData$outboundSchema: z.ZodType<
  GetOrganizationData$Outbound,
  z.ZodTypeDef,
  GetOrganizationData
> = z.union([
  z.lazy(() => DataExternalOrganization$outboundSchema).and(
    z.object({ type: z.literal("external") }).transform((v) => ({
      type: v.type,
    })),
  ),
  z.lazy(() => DataIcoOrganization$outboundSchema).and(
    z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationData$ {
  /** @deprecated use `GetOrganizationData$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationData$inboundSchema;
  /** @deprecated use `GetOrganizationData$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationData$outboundSchema;
  /** @deprecated use `GetOrganizationData$Outbound` instead. */
  export type Outbound = GetOrganizationData$Outbound;
}

export function getOrganizationDataToJSON(
  getOrganizationData: GetOrganizationData,
): string {
  return JSON.stringify(
    GetOrganizationData$outboundSchema.parse(getOrganizationData),
  );
}

export function getOrganizationDataFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationData' from JSON`,
  );
}

/** @internal */
export const GetOrganizationResponseBody$inboundSchema: z.ZodType<
  GetOrganizationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.union([
    z.lazy(() => DataExternalOrganization$inboundSchema).and(
      z.object({ type: z.literal("external") }).transform((v) => ({
        type: v.type,
      })),
    ),
    z.lazy(() => DataIcoOrganization$inboundSchema).and(
      z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
    ),
  ]),
});

/** @internal */
export type GetOrganizationResponseBody$Outbound = {
  success: true;
  data:
    | (DataExternalOrganization$Outbound & { type: "external" })
    | (DataIcoOrganization$Outbound & { type: "ico" });
};

/** @internal */
export const GetOrganizationResponseBody$outboundSchema: z.ZodType<
  GetOrganizationResponseBody$Outbound,
  z.ZodTypeDef,
  GetOrganizationResponseBody
> = z.object({
  success: z.literal(true),
  data: z.union([
    z.lazy(() => DataExternalOrganization$outboundSchema).and(
      z.object({ type: z.literal("external") }).transform((v) => ({
        type: v.type,
      })),
    ),
    z.lazy(() => DataIcoOrganization$outboundSchema).and(
      z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
    ),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationResponseBody$ {
  /** @deprecated use `GetOrganizationResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationResponseBody$inboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationResponseBody$outboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$Outbound` instead. */
  export type Outbound = GetOrganizationResponseBody$Outbound;
}

export function getOrganizationResponseBodyToJSON(
  getOrganizationResponseBody: GetOrganizationResponseBody,
): string {
  return JSON.stringify(
    GetOrganizationResponseBody$outboundSchema.parse(
      getOrganizationResponseBody,
    ),
  );
}

export function getOrganizationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponseBody' from JSON`,
  );
}

/** @internal */
export const GetOrganizationResponse$inboundSchema: z.ZodType<
  GetOrganizationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetOrganizationResponseBody$inboundSchema),
  Err$inboundSchema,
]);

/** @internal */
export type GetOrganizationResponse$Outbound =
  | GetOrganizationResponseBody$Outbound
  | Err$Outbound;

/** @internal */
export const GetOrganizationResponse$outboundSchema: z.ZodType<
  GetOrganizationResponse$Outbound,
  z.ZodTypeDef,
  GetOrganizationResponse
> = z.union([
  z.lazy(() => GetOrganizationResponseBody$outboundSchema),
  Err$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationResponse$ {
  /** @deprecated use `GetOrganizationResponse$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationResponse$inboundSchema;
  /** @deprecated use `GetOrganizationResponse$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationResponse$outboundSchema;
  /** @deprecated use `GetOrganizationResponse$Outbound` instead. */
  export type Outbound = GetOrganizationResponse$Outbound;
}

export function getOrganizationResponseToJSON(
  getOrganizationResponse: GetOrganizationResponse,
): string {
  return JSON.stringify(
    GetOrganizationResponse$outboundSchema.parse(getOrganizationResponse),
  );
}

export function getOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponse' from JSON`,
  );
}
