/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "../components/contactinformation.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "../components/link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "../components/organizationstatus.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "../components/proposal.js";
import {
  Raise,
  Raise$inboundSchema,
  Raise$Outbound,
  Raise$outboundSchema,
} from "../components/raise.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "../components/token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "../components/treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "../components/user.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationSecurity = {
  bearerAuth?: string | undefined;
};

export type GetOrganizationRequest = {
  slug: string;
};

export type IcoOrganization = {
  type: "ico";
  raise: Raise;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals: Array<Proposal>;
};

export type ExternalOrganization = {
  type: "external";
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals: Array<Proposal>;
};

export type GetOrganizationData =
  | (IcoOrganization & { type: "ico" })
  | (ExternalOrganization & { type: "external" });

/**
 * Success response wrapper
 */
export type GetOrganizationResponseBody = {
  success: true;
  data:
    | (IcoOrganization & { type: "ico" })
    | (ExternalOrganization & { type: "external" });
};

export type GetOrganizationResponse = GetOrganizationResponseBody | Err;

/** @internal */
export const GetOrganizationSecurity$inboundSchema: z.ZodType<
  GetOrganizationSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetOrganizationSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetOrganizationSecurity$outboundSchema: z.ZodType<
  GetOrganizationSecurity$Outbound,
  z.ZodTypeDef,
  GetOrganizationSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationSecurity$ {
  /** @deprecated use `GetOrganizationSecurity$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationSecurity$inboundSchema;
  /** @deprecated use `GetOrganizationSecurity$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationSecurity$outboundSchema;
  /** @deprecated use `GetOrganizationSecurity$Outbound` instead. */
  export type Outbound = GetOrganizationSecurity$Outbound;
}

export function getOrganizationSecurityToJSON(
  getOrganizationSecurity: GetOrganizationSecurity,
): string {
  return JSON.stringify(
    GetOrganizationSecurity$outboundSchema.parse(getOrganizationSecurity),
  );
}

export function getOrganizationSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationSecurity' from JSON`,
  );
}

/** @internal */
export const GetOrganizationRequest$inboundSchema: z.ZodType<
  GetOrganizationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetOrganizationRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodType<
  GetOrganizationRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationRequest$ {
  /** @deprecated use `GetOrganizationRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationRequest$inboundSchema;
  /** @deprecated use `GetOrganizationRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationRequest$outboundSchema;
  /** @deprecated use `GetOrganizationRequest$Outbound` instead. */
  export type Outbound = GetOrganizationRequest$Outbound;
}

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}

export function getOrganizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationRequest' from JSON`,
  );
}

/** @internal */
export const IcoOrganization$inboundSchema: z.ZodType<
  IcoOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("ico"),
  raise: Raise$inboundSchema,
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  proposals: z.array(Proposal$inboundSchema),
});

/** @internal */
export type IcoOrganization$Outbound = {
  type: "ico";
  raise: Raise$Outbound;
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals: Array<Proposal$Outbound>;
};

/** @internal */
export const IcoOrganization$outboundSchema: z.ZodType<
  IcoOrganization$Outbound,
  z.ZodTypeDef,
  IcoOrganization
> = z.object({
  type: z.literal("ico"),
  raise: Raise$outboundSchema,
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  proposals: z.array(Proposal$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IcoOrganization$ {
  /** @deprecated use `IcoOrganization$inboundSchema` instead. */
  export const inboundSchema = IcoOrganization$inboundSchema;
  /** @deprecated use `IcoOrganization$outboundSchema` instead. */
  export const outboundSchema = IcoOrganization$outboundSchema;
  /** @deprecated use `IcoOrganization$Outbound` instead. */
  export type Outbound = IcoOrganization$Outbound;
}

export function icoOrganizationToJSON(
  icoOrganization: IcoOrganization,
): string {
  return JSON.stringify(IcoOrganization$outboundSchema.parse(icoOrganization));
}

export function icoOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<IcoOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IcoOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IcoOrganization' from JSON`,
  );
}

/** @internal */
export const ExternalOrganization$inboundSchema: z.ZodType<
  ExternalOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("external"),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  proposals: z.array(Proposal$inboundSchema),
});

/** @internal */
export type ExternalOrganization$Outbound = {
  type: "external";
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals: Array<Proposal$Outbound>;
};

/** @internal */
export const ExternalOrganization$outboundSchema: z.ZodType<
  ExternalOrganization$Outbound,
  z.ZodTypeDef,
  ExternalOrganization
> = z.object({
  type: z.literal("external"),
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  proposals: z.array(Proposal$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExternalOrganization$ {
  /** @deprecated use `ExternalOrganization$inboundSchema` instead. */
  export const inboundSchema = ExternalOrganization$inboundSchema;
  /** @deprecated use `ExternalOrganization$outboundSchema` instead. */
  export const outboundSchema = ExternalOrganization$outboundSchema;
  /** @deprecated use `ExternalOrganization$Outbound` instead. */
  export type Outbound = ExternalOrganization$Outbound;
}

export function externalOrganizationToJSON(
  externalOrganization: ExternalOrganization,
): string {
  return JSON.stringify(
    ExternalOrganization$outboundSchema.parse(externalOrganization),
  );
}

export function externalOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<ExternalOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalOrganization' from JSON`,
  );
}

/** @internal */
export const GetOrganizationData$inboundSchema: z.ZodType<
  GetOrganizationData,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IcoOrganization$inboundSchema).and(
    z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => ExternalOrganization$inboundSchema).and(
    z.object({ type: z.literal("external") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/** @internal */
export type GetOrganizationData$Outbound =
  | (IcoOrganization$Outbound & { type: "ico" })
  | (ExternalOrganization$Outbound & { type: "external" });

/** @internal */
export const GetOrganizationData$outboundSchema: z.ZodType<
  GetOrganizationData$Outbound,
  z.ZodTypeDef,
  GetOrganizationData
> = z.union([
  z.lazy(() => IcoOrganization$outboundSchema).and(
    z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
  ),
  z.lazy(() => ExternalOrganization$outboundSchema).and(
    z.object({ type: z.literal("external") }).transform((v) => ({
      type: v.type,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationData$ {
  /** @deprecated use `GetOrganizationData$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationData$inboundSchema;
  /** @deprecated use `GetOrganizationData$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationData$outboundSchema;
  /** @deprecated use `GetOrganizationData$Outbound` instead. */
  export type Outbound = GetOrganizationData$Outbound;
}

export function getOrganizationDataToJSON(
  getOrganizationData: GetOrganizationData,
): string {
  return JSON.stringify(
    GetOrganizationData$outboundSchema.parse(getOrganizationData),
  );
}

export function getOrganizationDataFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationData' from JSON`,
  );
}

/** @internal */
export const GetOrganizationResponseBody$inboundSchema: z.ZodType<
  GetOrganizationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.union([
    z.lazy(() => IcoOrganization$inboundSchema).and(
      z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => ExternalOrganization$inboundSchema).and(
      z.object({ type: z.literal("external") }).transform((v) => ({
        type: v.type,
      })),
    ),
  ]),
});

/** @internal */
export type GetOrganizationResponseBody$Outbound = {
  success: true;
  data:
    | (IcoOrganization$Outbound & { type: "ico" })
    | (ExternalOrganization$Outbound & { type: "external" });
};

/** @internal */
export const GetOrganizationResponseBody$outboundSchema: z.ZodType<
  GetOrganizationResponseBody$Outbound,
  z.ZodTypeDef,
  GetOrganizationResponseBody
> = z.object({
  success: z.literal(true),
  data: z.union([
    z.lazy(() => IcoOrganization$outboundSchema).and(
      z.object({ type: z.literal("ico") }).transform((v) => ({ type: v.type })),
    ),
    z.lazy(() => ExternalOrganization$outboundSchema).and(
      z.object({ type: z.literal("external") }).transform((v) => ({
        type: v.type,
      })),
    ),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationResponseBody$ {
  /** @deprecated use `GetOrganizationResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationResponseBody$inboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationResponseBody$outboundSchema;
  /** @deprecated use `GetOrganizationResponseBody$Outbound` instead. */
  export type Outbound = GetOrganizationResponseBody$Outbound;
}

export function getOrganizationResponseBodyToJSON(
  getOrganizationResponseBody: GetOrganizationResponseBody,
): string {
  return JSON.stringify(
    GetOrganizationResponseBody$outboundSchema.parse(
      getOrganizationResponseBody,
    ),
  );
}

export function getOrganizationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponseBody' from JSON`,
  );
}

/** @internal */
export const GetOrganizationResponse$inboundSchema: z.ZodType<
  GetOrganizationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetOrganizationResponseBody$inboundSchema),
  Err$inboundSchema,
]);

/** @internal */
export type GetOrganizationResponse$Outbound =
  | GetOrganizationResponseBody$Outbound
  | Err$Outbound;

/** @internal */
export const GetOrganizationResponse$outboundSchema: z.ZodType<
  GetOrganizationResponse$Outbound,
  z.ZodTypeDef,
  GetOrganizationResponse
> = z.union([
  z.lazy(() => GetOrganizationResponseBody$outboundSchema),
  Err$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationResponse$ {
  /** @deprecated use `GetOrganizationResponse$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationResponse$inboundSchema;
  /** @deprecated use `GetOrganizationResponse$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationResponse$outboundSchema;
  /** @deprecated use `GetOrganizationResponse$Outbound` instead. */
  export type Outbound = GetOrganizationResponse$Outbound;
}

export function getOrganizationResponseToJSON(
  getOrganizationResponse: GetOrganizationResponse,
): string {
  return JSON.stringify(
    GetOrganizationResponse$outboundSchema.parse(getOrganizationResponse),
  );
}

export function getOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponse' from JSON`,
  );
}
