/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "../components/proposal.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProposalSecurity = {
  bearerAuth?: string | undefined;
};

export type GetProposalRequest = {
  id: number;
};

/**
 * Success response wrapper
 */
export type GetProposalResponseBody = {
  success: boolean;
  data?: Proposal | undefined;
};

export type GetProposalResponse = Err | GetProposalResponseBody;

/** @internal */
export const GetProposalSecurity$inboundSchema: z.ZodType<
  GetProposalSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetProposalSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetProposalSecurity$outboundSchema: z.ZodType<
  GetProposalSecurity$Outbound,
  z.ZodTypeDef,
  GetProposalSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProposalSecurity$ {
  /** @deprecated use `GetProposalSecurity$inboundSchema` instead. */
  export const inboundSchema = GetProposalSecurity$inboundSchema;
  /** @deprecated use `GetProposalSecurity$outboundSchema` instead. */
  export const outboundSchema = GetProposalSecurity$outboundSchema;
  /** @deprecated use `GetProposalSecurity$Outbound` instead. */
  export type Outbound = GetProposalSecurity$Outbound;
}

export function getProposalSecurityToJSON(
  getProposalSecurity: GetProposalSecurity,
): string {
  return JSON.stringify(
    GetProposalSecurity$outboundSchema.parse(getProposalSecurity),
  );
}

export function getProposalSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetProposalSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProposalSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProposalSecurity' from JSON`,
  );
}

/** @internal */
export const GetProposalRequest$inboundSchema: z.ZodType<
  GetProposalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetProposalRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetProposalRequest$outboundSchema: z.ZodType<
  GetProposalRequest$Outbound,
  z.ZodTypeDef,
  GetProposalRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProposalRequest$ {
  /** @deprecated use `GetProposalRequest$inboundSchema` instead. */
  export const inboundSchema = GetProposalRequest$inboundSchema;
  /** @deprecated use `GetProposalRequest$outboundSchema` instead. */
  export const outboundSchema = GetProposalRequest$outboundSchema;
  /** @deprecated use `GetProposalRequest$Outbound` instead. */
  export type Outbound = GetProposalRequest$Outbound;
}

export function getProposalRequestToJSON(
  getProposalRequest: GetProposalRequest,
): string {
  return JSON.stringify(
    GetProposalRequest$outboundSchema.parse(getProposalRequest),
  );
}

export function getProposalRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProposalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProposalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProposalRequest' from JSON`,
  );
}

/** @internal */
export const GetProposalResponseBody$inboundSchema: z.ZodType<
  GetProposalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: Proposal$inboundSchema.optional(),
});

/** @internal */
export type GetProposalResponseBody$Outbound = {
  success: boolean;
  data?: Proposal$Outbound | undefined;
};

/** @internal */
export const GetProposalResponseBody$outboundSchema: z.ZodType<
  GetProposalResponseBody$Outbound,
  z.ZodTypeDef,
  GetProposalResponseBody
> = z.object({
  success: z.boolean(),
  data: Proposal$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProposalResponseBody$ {
  /** @deprecated use `GetProposalResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetProposalResponseBody$inboundSchema;
  /** @deprecated use `GetProposalResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetProposalResponseBody$outboundSchema;
  /** @deprecated use `GetProposalResponseBody$Outbound` instead. */
  export type Outbound = GetProposalResponseBody$Outbound;
}

export function getProposalResponseBodyToJSON(
  getProposalResponseBody: GetProposalResponseBody,
): string {
  return JSON.stringify(
    GetProposalResponseBody$outboundSchema.parse(getProposalResponseBody),
  );
}

export function getProposalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetProposalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProposalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProposalResponseBody' from JSON`,
  );
}

/** @internal */
export const GetProposalResponse$inboundSchema: z.ZodType<
  GetProposalResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => GetProposalResponseBody$inboundSchema),
]);

/** @internal */
export type GetProposalResponse$Outbound =
  | Err$Outbound
  | GetProposalResponseBody$Outbound;

/** @internal */
export const GetProposalResponse$outboundSchema: z.ZodType<
  GetProposalResponse$Outbound,
  z.ZodTypeDef,
  GetProposalResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => GetProposalResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProposalResponse$ {
  /** @deprecated use `GetProposalResponse$inboundSchema` instead. */
  export const inboundSchema = GetProposalResponse$inboundSchema;
  /** @deprecated use `GetProposalResponse$outboundSchema` instead. */
  export const outboundSchema = GetProposalResponse$outboundSchema;
  /** @deprecated use `GetProposalResponse$Outbound` instead. */
  export type Outbound = GetProposalResponse$Outbound;
}

export function getProposalResponseToJSON(
  getProposalResponse: GetProposalResponse,
): string {
  return JSON.stringify(
    GetProposalResponse$outboundSchema.parse(getProposalResponse),
  );
}

export function getProposalResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProposalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProposalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProposalResponse' from JSON`,
  );
}
