/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserRequest = {
  id: number;
};

/**
 * OK
 */
export type GetUserResponseBody = {
  success: true;
  data: components.User;
};

/** @internal */
export const GetUserRequest$inboundSchema: z.ZodType<
  GetUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetUserRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetUserRequest$outboundSchema: z.ZodType<
  GetUserRequest$Outbound,
  z.ZodTypeDef,
  GetUserRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserRequest$ {
  /** @deprecated use `GetUserRequest$inboundSchema` instead. */
  export const inboundSchema = GetUserRequest$inboundSchema;
  /** @deprecated use `GetUserRequest$outboundSchema` instead. */
  export const outboundSchema = GetUserRequest$outboundSchema;
  /** @deprecated use `GetUserRequest$Outbound` instead. */
  export type Outbound = GetUserRequest$Outbound;
}

export function getUserRequestToJSON(getUserRequest: GetUserRequest): string {
  return JSON.stringify(GetUserRequest$outboundSchema.parse(getUserRequest));
}

export function getUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserRequest' from JSON`,
  );
}

/** @internal */
export const GetUserResponseBody$inboundSchema: z.ZodType<
  GetUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: components.User$inboundSchema,
});

/** @internal */
export type GetUserResponseBody$Outbound = {
  success: true;
  data: components.User$Outbound;
};

/** @internal */
export const GetUserResponseBody$outboundSchema: z.ZodType<
  GetUserResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserResponseBody
> = z.object({
  success: z.literal(true),
  data: components.User$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserResponseBody$ {
  /** @deprecated use `GetUserResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserResponseBody$inboundSchema;
  /** @deprecated use `GetUserResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserResponseBody$outboundSchema;
  /** @deprecated use `GetUserResponseBody$Outbound` instead. */
  export type Outbound = GetUserResponseBody$Outbound;
}

export function getUserResponseBodyToJSON(
  getUserResponseBody: GetUserResponseBody,
): string {
  return JSON.stringify(
    GetUserResponseBody$outboundSchema.parse(getUserResponseBody),
  );
}

export function getUserResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetUserResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserResponseBody' from JSON`,
  );
}
