/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  AuditAction,
  AuditAction$inboundSchema,
  AuditAction$outboundSchema,
} from "../components/auditaction.js";
import {
  AuditLog,
  AuditLog$inboundSchema,
  AuditLog$Outbound,
  AuditLog$outboundSchema,
} from "../components/auditlog.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "../components/pagination.js";
import {
  TargetType,
  TargetType$inboundSchema,
  TargetType$outboundSchema,
} from "../components/targettype.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditLogsRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  action?: AuditAction | undefined;
  targetType?: TargetType | undefined;
  /**
   * Filter by admin who performed the action
   */
  userId?: number | undefined;
};

/**
 * Success response wrapper
 */
export type ListAuditLogsResponseBody = {
  success: true;
  data: Array<AuditLog>;
  /**
   * Pagination parameters for list endpoints. Use page/limit for requests, total is returned in responses.
   */
  pagination: Pagination;
};

/** @internal */
export const ListAuditLogsRequest$inboundSchema: z.ZodType<
  ListAuditLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: AuditAction$inboundSchema.optional(),
  targetType: TargetType$inboundSchema.optional(),
  userId: z.number().int().optional(),
});

/** @internal */
export type ListAuditLogsRequest$Outbound = {
  page: number;
  limit: number;
  action?: string | undefined;
  targetType?: string | undefined;
  userId?: number | undefined;
};

/** @internal */
export const ListAuditLogsRequest$outboundSchema: z.ZodType<
  ListAuditLogsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditLogsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: AuditAction$outboundSchema.optional(),
  targetType: TargetType$outboundSchema.optional(),
  userId: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsRequest$ {
  /** @deprecated use `ListAuditLogsRequest$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsRequest$inboundSchema;
  /** @deprecated use `ListAuditLogsRequest$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsRequest$outboundSchema;
  /** @deprecated use `ListAuditLogsRequest$Outbound` instead. */
  export type Outbound = ListAuditLogsRequest$Outbound;
}

export function listAuditLogsRequestToJSON(
  listAuditLogsRequest: ListAuditLogsRequest,
): string {
  return JSON.stringify(
    ListAuditLogsRequest$outboundSchema.parse(listAuditLogsRequest),
  );
}

export function listAuditLogsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsRequest' from JSON`,
  );
}

/** @internal */
export const ListAuditLogsResponseBody$inboundSchema: z.ZodType<
  ListAuditLogsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(AuditLog$inboundSchema),
  pagination: Pagination$inboundSchema,
});

/** @internal */
export type ListAuditLogsResponseBody$Outbound = {
  success: true;
  data: Array<AuditLog$Outbound>;
  pagination: Pagination$Outbound;
};

/** @internal */
export const ListAuditLogsResponseBody$outboundSchema: z.ZodType<
  ListAuditLogsResponseBody$Outbound,
  z.ZodTypeDef,
  ListAuditLogsResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(AuditLog$outboundSchema),
  pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsResponseBody$ {
  /** @deprecated use `ListAuditLogsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsResponseBody$inboundSchema;
  /** @deprecated use `ListAuditLogsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsResponseBody$outboundSchema;
  /** @deprecated use `ListAuditLogsResponseBody$Outbound` instead. */
  export type Outbound = ListAuditLogsResponseBody$Outbound;
}

export function listAuditLogsResponseBodyToJSON(
  listAuditLogsResponseBody: ListAuditLogsResponseBody,
): string {
  return JSON.stringify(
    ListAuditLogsResponseBody$outboundSchema.parse(listAuditLogsResponseBody),
  );
}

export function listAuditLogsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsResponseBody' from JSON`,
  );
}
