/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListRaisesSecurity = {
  bearer?: string | undefined;
};

export type ListRaisesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * Filter by status (comma-separated)
   */
  status?: string | undefined;
  organizationId?: number | undefined;
};

/**
 * OK
 */
export type ListRaisesResponseBody = {
  success: true;
  data: Array<components.Raise>;
  pagination: components.Pagination;
};

/** @internal */
export const ListRaisesSecurity$inboundSchema: z.ZodType<
  ListRaisesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearer: z.string().optional(),
});

/** @internal */
export type ListRaisesSecurity$Outbound = {
  bearer?: string | undefined;
};

/** @internal */
export const ListRaisesSecurity$outboundSchema: z.ZodType<
  ListRaisesSecurity$Outbound,
  z.ZodTypeDef,
  ListRaisesSecurity
> = z.object({
  bearer: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRaisesSecurity$ {
  /** @deprecated use `ListRaisesSecurity$inboundSchema` instead. */
  export const inboundSchema = ListRaisesSecurity$inboundSchema;
  /** @deprecated use `ListRaisesSecurity$outboundSchema` instead. */
  export const outboundSchema = ListRaisesSecurity$outboundSchema;
  /** @deprecated use `ListRaisesSecurity$Outbound` instead. */
  export type Outbound = ListRaisesSecurity$Outbound;
}

export function listRaisesSecurityToJSON(
  listRaisesSecurity: ListRaisesSecurity,
): string {
  return JSON.stringify(
    ListRaisesSecurity$outboundSchema.parse(listRaisesSecurity),
  );
}

export function listRaisesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListRaisesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRaisesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRaisesSecurity' from JSON`,
  );
}

/** @internal */
export const ListRaisesRequest$inboundSchema: z.ZodType<
  ListRaisesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  status: z.string().optional(),
  organizationId: z.number().int().optional(),
});

/** @internal */
export type ListRaisesRequest$Outbound = {
  page: number;
  limit: number;
  status?: string | undefined;
  organizationId?: number | undefined;
};

/** @internal */
export const ListRaisesRequest$outboundSchema: z.ZodType<
  ListRaisesRequest$Outbound,
  z.ZodTypeDef,
  ListRaisesRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  status: z.string().optional(),
  organizationId: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRaisesRequest$ {
  /** @deprecated use `ListRaisesRequest$inboundSchema` instead. */
  export const inboundSchema = ListRaisesRequest$inboundSchema;
  /** @deprecated use `ListRaisesRequest$outboundSchema` instead. */
  export const outboundSchema = ListRaisesRequest$outboundSchema;
  /** @deprecated use `ListRaisesRequest$Outbound` instead. */
  export type Outbound = ListRaisesRequest$Outbound;
}

export function listRaisesRequestToJSON(
  listRaisesRequest: ListRaisesRequest,
): string {
  return JSON.stringify(
    ListRaisesRequest$outboundSchema.parse(listRaisesRequest),
  );
}

export function listRaisesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListRaisesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRaisesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRaisesRequest' from JSON`,
  );
}

/** @internal */
export const ListRaisesResponseBody$inboundSchema: z.ZodType<
  ListRaisesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(components.Raise$inboundSchema),
  pagination: components.Pagination$inboundSchema,
});

/** @internal */
export type ListRaisesResponseBody$Outbound = {
  success: true;
  data: Array<components.Raise$Outbound>;
  pagination: components.Pagination$Outbound;
};

/** @internal */
export const ListRaisesResponseBody$outboundSchema: z.ZodType<
  ListRaisesResponseBody$Outbound,
  z.ZodTypeDef,
  ListRaisesResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(components.Raise$outboundSchema),
  pagination: components.Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRaisesResponseBody$ {
  /** @deprecated use `ListRaisesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListRaisesResponseBody$inboundSchema;
  /** @deprecated use `ListRaisesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListRaisesResponseBody$outboundSchema;
  /** @deprecated use `ListRaisesResponseBody$Outbound` instead. */
  export type Outbound = ListRaisesResponseBody$Outbound;
}

export function listRaisesResponseBodyToJSON(
  listRaisesResponseBody: ListRaisesResponseBody,
): string {
  return JSON.stringify(
    ListRaisesResponseBody$outboundSchema.parse(listRaisesResponseBody),
  );
}

export function listRaisesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListRaisesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRaisesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRaisesResponseBody' from JSON`,
  );
}
