/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Trade,
  Trade$inboundSchema,
  Trade$Outbound,
  Trade$outboundSchema,
} from "../components/trade.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter by market side
 */
export const Side = {
  Pass: "pass",
  Fail: "fail",
} as const;
/**
 * Filter by market side
 */
export type Side = ClosedEnum<typeof Side>;

export type ListProposalTradesRequest = {
  id: number;
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Filter by market side
   */
  side?: Side | undefined;
};

export type ListProposalTradesPagination = {
  page: number;
  limit: number;
  total: number;
};

/**
 * Success response wrapper
 */
export type ListProposalTradesResponseBody = {
  success: boolean;
  pagination?: ListProposalTradesPagination | undefined;
  data?: Array<Trade> | undefined;
};

export type ListProposalTradesResponse = Err | ListProposalTradesResponseBody;

/** @internal */
export const Side$inboundSchema: z.ZodNativeEnum<typeof Side> = z.nativeEnum(
  Side,
);

/** @internal */
export const Side$outboundSchema: z.ZodNativeEnum<typeof Side> =
  Side$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Side$ {
  /** @deprecated use `Side$inboundSchema` instead. */
  export const inboundSchema = Side$inboundSchema;
  /** @deprecated use `Side$outboundSchema` instead. */
  export const outboundSchema = Side$outboundSchema;
}

/** @internal */
export const ListProposalTradesRequest$inboundSchema: z.ZodType<
  ListProposalTradesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$inboundSchema.optional(),
});

/** @internal */
export type ListProposalTradesRequest$Outbound = {
  id: number;
  page: number;
  limit: number;
  side?: string | undefined;
};

/** @internal */
export const ListProposalTradesRequest$outboundSchema: z.ZodType<
  ListProposalTradesRequest$Outbound,
  z.ZodTypeDef,
  ListProposalTradesRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalTradesRequest$ {
  /** @deprecated use `ListProposalTradesRequest$inboundSchema` instead. */
  export const inboundSchema = ListProposalTradesRequest$inboundSchema;
  /** @deprecated use `ListProposalTradesRequest$outboundSchema` instead. */
  export const outboundSchema = ListProposalTradesRequest$outboundSchema;
  /** @deprecated use `ListProposalTradesRequest$Outbound` instead. */
  export type Outbound = ListProposalTradesRequest$Outbound;
}

export function listProposalTradesRequestToJSON(
  listProposalTradesRequest: ListProposalTradesRequest,
): string {
  return JSON.stringify(
    ListProposalTradesRequest$outboundSchema.parse(listProposalTradesRequest),
  );
}

export function listProposalTradesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalTradesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalTradesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalTradesRequest' from JSON`,
  );
}

/** @internal */
export const ListProposalTradesPagination$inboundSchema: z.ZodType<
  ListProposalTradesPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/** @internal */
export type ListProposalTradesPagination$Outbound = {
  page: number;
  limit: number;
  total: number;
};

/** @internal */
export const ListProposalTradesPagination$outboundSchema: z.ZodType<
  ListProposalTradesPagination$Outbound,
  z.ZodTypeDef,
  ListProposalTradesPagination
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalTradesPagination$ {
  /** @deprecated use `ListProposalTradesPagination$inboundSchema` instead. */
  export const inboundSchema = ListProposalTradesPagination$inboundSchema;
  /** @deprecated use `ListProposalTradesPagination$outboundSchema` instead. */
  export const outboundSchema = ListProposalTradesPagination$outboundSchema;
  /** @deprecated use `ListProposalTradesPagination$Outbound` instead. */
  export type Outbound = ListProposalTradesPagination$Outbound;
}

export function listProposalTradesPaginationToJSON(
  listProposalTradesPagination: ListProposalTradesPagination,
): string {
  return JSON.stringify(
    ListProposalTradesPagination$outboundSchema.parse(
      listProposalTradesPagination,
    ),
  );
}

export function listProposalTradesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalTradesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalTradesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalTradesPagination' from JSON`,
  );
}

/** @internal */
export const ListProposalTradesResponseBody$inboundSchema: z.ZodType<
  ListProposalTradesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListProposalTradesPagination$inboundSchema)
    .optional(),
  data: z.array(Trade$inboundSchema).optional(),
});

/** @internal */
export type ListProposalTradesResponseBody$Outbound = {
  success: boolean;
  pagination?: ListProposalTradesPagination$Outbound | undefined;
  data?: Array<Trade$Outbound> | undefined;
};

/** @internal */
export const ListProposalTradesResponseBody$outboundSchema: z.ZodType<
  ListProposalTradesResponseBody$Outbound,
  z.ZodTypeDef,
  ListProposalTradesResponseBody
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListProposalTradesPagination$outboundSchema)
    .optional(),
  data: z.array(Trade$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalTradesResponseBody$ {
  /** @deprecated use `ListProposalTradesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListProposalTradesResponseBody$inboundSchema;
  /** @deprecated use `ListProposalTradesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListProposalTradesResponseBody$outboundSchema;
  /** @deprecated use `ListProposalTradesResponseBody$Outbound` instead. */
  export type Outbound = ListProposalTradesResponseBody$Outbound;
}

export function listProposalTradesResponseBodyToJSON(
  listProposalTradesResponseBody: ListProposalTradesResponseBody,
): string {
  return JSON.stringify(
    ListProposalTradesResponseBody$outboundSchema.parse(
      listProposalTradesResponseBody,
    ),
  );
}

export function listProposalTradesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalTradesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalTradesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalTradesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListProposalTradesResponse$inboundSchema: z.ZodType<
  ListProposalTradesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => ListProposalTradesResponseBody$inboundSchema),
]);

/** @internal */
export type ListProposalTradesResponse$Outbound =
  | Err$Outbound
  | ListProposalTradesResponseBody$Outbound;

/** @internal */
export const ListProposalTradesResponse$outboundSchema: z.ZodType<
  ListProposalTradesResponse$Outbound,
  z.ZodTypeDef,
  ListProposalTradesResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => ListProposalTradesResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalTradesResponse$ {
  /** @deprecated use `ListProposalTradesResponse$inboundSchema` instead. */
  export const inboundSchema = ListProposalTradesResponse$inboundSchema;
  /** @deprecated use `ListProposalTradesResponse$outboundSchema` instead. */
  export const outboundSchema = ListProposalTradesResponse$outboundSchema;
  /** @deprecated use `ListProposalTradesResponse$Outbound` instead. */
  export type Outbound = ListProposalTradesResponse$Outbound;
}

export function listProposalTradesResponseToJSON(
  listProposalTradesResponse: ListProposalTradesResponse,
): string {
  return JSON.stringify(
    ListProposalTradesResponse$outboundSchema.parse(listProposalTradesResponse),
  );
}

export function listProposalTradesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalTradesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalTradesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalTradesResponse' from JSON`,
  );
}
