/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "../components/pagination.js";
import {
  ProposalStake,
  ProposalStake$inboundSchema,
  ProposalStake$Outbound,
  ProposalStake$outboundSchema,
} from "../components/proposalstake.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListProposalStakesRequest = {
  id: number;
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
};

/**
 * Success response wrapper
 */
export type ListProposalStakesResponseBody = {
  success: true;
  data: Array<ProposalStake>;
  /**
   * Pagination parameters for list endpoints. Use page/limit for requests, total is returned in responses.
   */
  pagination: Pagination;
};

/** @internal */
export const ListProposalStakesRequest$inboundSchema: z.ZodType<
  ListProposalStakesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
});

/** @internal */
export type ListProposalStakesRequest$Outbound = {
  id: number;
  page: number;
  limit: number;
};

/** @internal */
export const ListProposalStakesRequest$outboundSchema: z.ZodType<
  ListProposalStakesRequest$Outbound,
  z.ZodTypeDef,
  ListProposalStakesRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalStakesRequest$ {
  /** @deprecated use `ListProposalStakesRequest$inboundSchema` instead. */
  export const inboundSchema = ListProposalStakesRequest$inboundSchema;
  /** @deprecated use `ListProposalStakesRequest$outboundSchema` instead. */
  export const outboundSchema = ListProposalStakesRequest$outboundSchema;
  /** @deprecated use `ListProposalStakesRequest$Outbound` instead. */
  export type Outbound = ListProposalStakesRequest$Outbound;
}

export function listProposalStakesRequestToJSON(
  listProposalStakesRequest: ListProposalStakesRequest,
): string {
  return JSON.stringify(
    ListProposalStakesRequest$outboundSchema.parse(listProposalStakesRequest),
  );
}

export function listProposalStakesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalStakesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalStakesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalStakesRequest' from JSON`,
  );
}

/** @internal */
export const ListProposalStakesResponseBody$inboundSchema: z.ZodType<
  ListProposalStakesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(ProposalStake$inboundSchema),
  pagination: Pagination$inboundSchema,
});

/** @internal */
export type ListProposalStakesResponseBody$Outbound = {
  success: true;
  data: Array<ProposalStake$Outbound>;
  pagination: Pagination$Outbound;
};

/** @internal */
export const ListProposalStakesResponseBody$outboundSchema: z.ZodType<
  ListProposalStakesResponseBody$Outbound,
  z.ZodTypeDef,
  ListProposalStakesResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(ProposalStake$outboundSchema),
  pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalStakesResponseBody$ {
  /** @deprecated use `ListProposalStakesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListProposalStakesResponseBody$inboundSchema;
  /** @deprecated use `ListProposalStakesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListProposalStakesResponseBody$outboundSchema;
  /** @deprecated use `ListProposalStakesResponseBody$Outbound` instead. */
  export type Outbound = ListProposalStakesResponseBody$Outbound;
}

export function listProposalStakesResponseBodyToJSON(
  listProposalStakesResponseBody: ListProposalStakesResponseBody,
): string {
  return JSON.stringify(
    ListProposalStakesResponseBody$outboundSchema.parse(
      listProposalStakesResponseBody,
    ),
  );
}

export function listProposalStakesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalStakesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalStakesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalStakesResponseBody' from JSON`,
  );
}
