/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListTradesSecurity = {
  bearer?: string | undefined;
};

export const Side = {
  Pass: "pass",
  Fail: "fail",
} as const;
export type Side = ClosedEnum<typeof Side>;

export type ListTradesRequest = {
  id: number;
  page?: number | undefined;
  limit?: number | undefined;
  side?: Side | undefined;
};

/**
 * OK
 */
export type ListTradesResponseBody = {
  success: true;
  data: Array<components.Trade>;
  pagination: components.Pagination;
};

/** @internal */
export const ListTradesSecurity$inboundSchema: z.ZodType<
  ListTradesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearer: z.string().optional(),
});

/** @internal */
export type ListTradesSecurity$Outbound = {
  bearer?: string | undefined;
};

/** @internal */
export const ListTradesSecurity$outboundSchema: z.ZodType<
  ListTradesSecurity$Outbound,
  z.ZodTypeDef,
  ListTradesSecurity
> = z.object({
  bearer: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTradesSecurity$ {
  /** @deprecated use `ListTradesSecurity$inboundSchema` instead. */
  export const inboundSchema = ListTradesSecurity$inboundSchema;
  /** @deprecated use `ListTradesSecurity$outboundSchema` instead. */
  export const outboundSchema = ListTradesSecurity$outboundSchema;
  /** @deprecated use `ListTradesSecurity$Outbound` instead. */
  export type Outbound = ListTradesSecurity$Outbound;
}

export function listTradesSecurityToJSON(
  listTradesSecurity: ListTradesSecurity,
): string {
  return JSON.stringify(
    ListTradesSecurity$outboundSchema.parse(listTradesSecurity),
  );
}

export function listTradesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListTradesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTradesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTradesSecurity' from JSON`,
  );
}

/** @internal */
export const Side$inboundSchema: z.ZodNativeEnum<typeof Side> = z.nativeEnum(
  Side,
);

/** @internal */
export const Side$outboundSchema: z.ZodNativeEnum<typeof Side> =
  Side$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Side$ {
  /** @deprecated use `Side$inboundSchema` instead. */
  export const inboundSchema = Side$inboundSchema;
  /** @deprecated use `Side$outboundSchema` instead. */
  export const outboundSchema = Side$outboundSchema;
}

/** @internal */
export const ListTradesRequest$inboundSchema: z.ZodType<
  ListTradesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$inboundSchema.optional(),
});

/** @internal */
export type ListTradesRequest$Outbound = {
  id: number;
  page: number;
  limit: number;
  side?: string | undefined;
};

/** @internal */
export const ListTradesRequest$outboundSchema: z.ZodType<
  ListTradesRequest$Outbound,
  z.ZodTypeDef,
  ListTradesRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTradesRequest$ {
  /** @deprecated use `ListTradesRequest$inboundSchema` instead. */
  export const inboundSchema = ListTradesRequest$inboundSchema;
  /** @deprecated use `ListTradesRequest$outboundSchema` instead. */
  export const outboundSchema = ListTradesRequest$outboundSchema;
  /** @deprecated use `ListTradesRequest$Outbound` instead. */
  export type Outbound = ListTradesRequest$Outbound;
}

export function listTradesRequestToJSON(
  listTradesRequest: ListTradesRequest,
): string {
  return JSON.stringify(
    ListTradesRequest$outboundSchema.parse(listTradesRequest),
  );
}

export function listTradesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListTradesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTradesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTradesRequest' from JSON`,
  );
}

/** @internal */
export const ListTradesResponseBody$inboundSchema: z.ZodType<
  ListTradesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(components.Trade$inboundSchema),
  pagination: components.Pagination$inboundSchema,
});

/** @internal */
export type ListTradesResponseBody$Outbound = {
  success: true;
  data: Array<components.Trade$Outbound>;
  pagination: components.Pagination$Outbound;
};

/** @internal */
export const ListTradesResponseBody$outboundSchema: z.ZodType<
  ListTradesResponseBody$Outbound,
  z.ZodTypeDef,
  ListTradesResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(components.Trade$outboundSchema),
  pagination: components.Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTradesResponseBody$ {
  /** @deprecated use `ListTradesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListTradesResponseBody$inboundSchema;
  /** @deprecated use `ListTradesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListTradesResponseBody$outboundSchema;
  /** @deprecated use `ListTradesResponseBody$Outbound` instead. */
  export type Outbound = ListTradesResponseBody$Outbound;
}

export function listTradesResponseBodyToJSON(
  listTradesResponseBody: ListTradesResponseBody,
): string {
  return JSON.stringify(
    ListTradesResponseBody$outboundSchema.parse(listTradesResponseBody),
  );
}

export function listTradesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListTradesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTradesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTradesResponseBody' from JSON`,
  );
}
