/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListUsersRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Text to search for across searchable fields
   */
  search?: string | undefined;
  /**
   * Comma-separated list of fields to search. Must be valid searchable fields. If omitted, uses default search fields.
   */
  fields?: string | undefined;
  /**
   * Filter by user role
   */
  role?: components.UserRole | undefined;
};

export type ListUsersPagination = {
  page: number;
  limit: number;
  total: number;
};

/**
 * Success response wrapper
 */
export type ListUsersResponseBody = {
  success: boolean;
  pagination?: ListUsersPagination | undefined;
  data?: Array<components.User> | undefined;
};

/** @internal */
export const ListUsersRequest$inboundSchema: z.ZodType<
  ListUsersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  role: components.UserRole$inboundSchema.optional(),
});

/** @internal */
export type ListUsersRequest$Outbound = {
  page: number;
  limit: number;
  search?: string | undefined;
  fields?: string | undefined;
  role?: string | undefined;
};

/** @internal */
export const ListUsersRequest$outboundSchema: z.ZodType<
  ListUsersRequest$Outbound,
  z.ZodTypeDef,
  ListUsersRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  role: components.UserRole$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsersRequest$ {
  /** @deprecated use `ListUsersRequest$inboundSchema` instead. */
  export const inboundSchema = ListUsersRequest$inboundSchema;
  /** @deprecated use `ListUsersRequest$outboundSchema` instead. */
  export const outboundSchema = ListUsersRequest$outboundSchema;
  /** @deprecated use `ListUsersRequest$Outbound` instead. */
  export type Outbound = ListUsersRequest$Outbound;
}

export function listUsersRequestToJSON(
  listUsersRequest: ListUsersRequest,
): string {
  return JSON.stringify(
    ListUsersRequest$outboundSchema.parse(listUsersRequest),
  );
}

export function listUsersRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListUsersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsersRequest' from JSON`,
  );
}

/** @internal */
export const ListUsersPagination$inboundSchema: z.ZodType<
  ListUsersPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/** @internal */
export type ListUsersPagination$Outbound = {
  page: number;
  limit: number;
  total: number;
};

/** @internal */
export const ListUsersPagination$outboundSchema: z.ZodType<
  ListUsersPagination$Outbound,
  z.ZodTypeDef,
  ListUsersPagination
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsersPagination$ {
  /** @deprecated use `ListUsersPagination$inboundSchema` instead. */
  export const inboundSchema = ListUsersPagination$inboundSchema;
  /** @deprecated use `ListUsersPagination$outboundSchema` instead. */
  export const outboundSchema = ListUsersPagination$outboundSchema;
  /** @deprecated use `ListUsersPagination$Outbound` instead. */
  export type Outbound = ListUsersPagination$Outbound;
}

export function listUsersPaginationToJSON(
  listUsersPagination: ListUsersPagination,
): string {
  return JSON.stringify(
    ListUsersPagination$outboundSchema.parse(listUsersPagination),
  );
}

export function listUsersPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListUsersPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsersPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsersPagination' from JSON`,
  );
}

/** @internal */
export const ListUsersResponseBody$inboundSchema: z.ZodType<
  ListUsersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListUsersPagination$inboundSchema).optional(),
  data: z.array(components.User$inboundSchema).optional(),
});

/** @internal */
export type ListUsersResponseBody$Outbound = {
  success: boolean;
  pagination?: ListUsersPagination$Outbound | undefined;
  data?: Array<components.User$Outbound> | undefined;
};

/** @internal */
export const ListUsersResponseBody$outboundSchema: z.ZodType<
  ListUsersResponseBody$Outbound,
  z.ZodTypeDef,
  ListUsersResponseBody
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListUsersPagination$outboundSchema).optional(),
  data: z.array(components.User$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsersResponseBody$ {
  /** @deprecated use `ListUsersResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListUsersResponseBody$inboundSchema;
  /** @deprecated use `ListUsersResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListUsersResponseBody$outboundSchema;
  /** @deprecated use `ListUsersResponseBody$Outbound` instead. */
  export type Outbound = ListUsersResponseBody$Outbound;
}

export function listUsersResponseBodyToJSON(
  listUsersResponseBody: ListUsersResponseBody,
): string {
  return JSON.stringify(
    ListUsersResponseBody$outboundSchema.parse(listUsersResponseBody),
  );
}

export function listUsersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListUsersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsersResponseBody' from JSON`,
  );
}
