/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  AuditAction,
  AuditAction$inboundSchema,
  AuditAction$outboundSchema,
} from "../components/auditaction.js";
import {
  AuditLog,
  AuditLog$inboundSchema,
  AuditLog$Outbound,
  AuditLog$outboundSchema,
} from "../components/auditlog.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  TargetType,
  TargetType$inboundSchema,
  TargetType$outboundSchema,
} from "../components/targettype.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditLogsRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  action?: AuditAction | undefined;
  targetType?: TargetType | undefined;
  /**
   * Filter by admin who performed the action
   */
  userId?: number | undefined;
};

export type ListAuditLogsPagination = {
  page: number;
  limit: number;
  total: number;
};

/**
 * Success response wrapper
 */
export type ListAuditLogsResponseBody = {
  success: boolean;
  pagination?: ListAuditLogsPagination | undefined;
  data?: Array<AuditLog> | undefined;
};

export type ListAuditLogsResponse = Err | ListAuditLogsResponseBody;

/** @internal */
export const ListAuditLogsRequest$inboundSchema: z.ZodType<
  ListAuditLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: AuditAction$inboundSchema.optional(),
  targetType: TargetType$inboundSchema.optional(),
  userId: z.number().int().optional(),
});

/** @internal */
export type ListAuditLogsRequest$Outbound = {
  page: number;
  limit: number;
  action?: string | undefined;
  targetType?: string | undefined;
  userId?: number | undefined;
};

/** @internal */
export const ListAuditLogsRequest$outboundSchema: z.ZodType<
  ListAuditLogsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditLogsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: AuditAction$outboundSchema.optional(),
  targetType: TargetType$outboundSchema.optional(),
  userId: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsRequest$ {
  /** @deprecated use `ListAuditLogsRequest$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsRequest$inboundSchema;
  /** @deprecated use `ListAuditLogsRequest$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsRequest$outboundSchema;
  /** @deprecated use `ListAuditLogsRequest$Outbound` instead. */
  export type Outbound = ListAuditLogsRequest$Outbound;
}

export function listAuditLogsRequestToJSON(
  listAuditLogsRequest: ListAuditLogsRequest,
): string {
  return JSON.stringify(
    ListAuditLogsRequest$outboundSchema.parse(listAuditLogsRequest),
  );
}

export function listAuditLogsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsRequest' from JSON`,
  );
}

/** @internal */
export const ListAuditLogsPagination$inboundSchema: z.ZodType<
  ListAuditLogsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/** @internal */
export type ListAuditLogsPagination$Outbound = {
  page: number;
  limit: number;
  total: number;
};

/** @internal */
export const ListAuditLogsPagination$outboundSchema: z.ZodType<
  ListAuditLogsPagination$Outbound,
  z.ZodTypeDef,
  ListAuditLogsPagination
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsPagination$ {
  /** @deprecated use `ListAuditLogsPagination$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsPagination$inboundSchema;
  /** @deprecated use `ListAuditLogsPagination$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsPagination$outboundSchema;
  /** @deprecated use `ListAuditLogsPagination$Outbound` instead. */
  export type Outbound = ListAuditLogsPagination$Outbound;
}

export function listAuditLogsPaginationToJSON(
  listAuditLogsPagination: ListAuditLogsPagination,
): string {
  return JSON.stringify(
    ListAuditLogsPagination$outboundSchema.parse(listAuditLogsPagination),
  );
}

export function listAuditLogsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsPagination' from JSON`,
  );
}

/** @internal */
export const ListAuditLogsResponseBody$inboundSchema: z.ZodType<
  ListAuditLogsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListAuditLogsPagination$inboundSchema).optional(),
  data: z.array(AuditLog$inboundSchema).optional(),
});

/** @internal */
export type ListAuditLogsResponseBody$Outbound = {
  success: boolean;
  pagination?: ListAuditLogsPagination$Outbound | undefined;
  data?: Array<AuditLog$Outbound> | undefined;
};

/** @internal */
export const ListAuditLogsResponseBody$outboundSchema: z.ZodType<
  ListAuditLogsResponseBody$Outbound,
  z.ZodTypeDef,
  ListAuditLogsResponseBody
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListAuditLogsPagination$outboundSchema).optional(),
  data: z.array(AuditLog$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsResponseBody$ {
  /** @deprecated use `ListAuditLogsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsResponseBody$inboundSchema;
  /** @deprecated use `ListAuditLogsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsResponseBody$outboundSchema;
  /** @deprecated use `ListAuditLogsResponseBody$Outbound` instead. */
  export type Outbound = ListAuditLogsResponseBody$Outbound;
}

export function listAuditLogsResponseBodyToJSON(
  listAuditLogsResponseBody: ListAuditLogsResponseBody,
): string {
  return JSON.stringify(
    ListAuditLogsResponseBody$outboundSchema.parse(listAuditLogsResponseBody),
  );
}

export function listAuditLogsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAuditLogsResponse$inboundSchema: z.ZodType<
  ListAuditLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Err$inboundSchema,
  z.lazy(() => ListAuditLogsResponseBody$inboundSchema),
]);

/** @internal */
export type ListAuditLogsResponse$Outbound =
  | Err$Outbound
  | ListAuditLogsResponseBody$Outbound;

/** @internal */
export const ListAuditLogsResponse$outboundSchema: z.ZodType<
  ListAuditLogsResponse$Outbound,
  z.ZodTypeDef,
  ListAuditLogsResponse
> = z.union([
  Err$outboundSchema,
  z.lazy(() => ListAuditLogsResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsResponse$ {
  /** @deprecated use `ListAuditLogsResponse$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsResponse$inboundSchema;
  /** @deprecated use `ListAuditLogsResponse$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsResponse$outboundSchema;
  /** @deprecated use `ListAuditLogsResponse$Outbound` instead. */
  export type Outbound = ListAuditLogsResponse$Outbound;
}

export function listAuditLogsResponseToJSON(
  listAuditLogsResponse: ListAuditLogsResponse,
): string {
  return JSON.stringify(
    ListAuditLogsResponse$outboundSchema.parse(listAuditLogsResponse),
  );
}

export function listAuditLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsResponse' from JSON`,
  );
}
