/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListOrganizationsSecurity = {
  bearerAuth?: string | undefined;
};

export type ListOrganizationsRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Text to search for across searchable fields
   */
  search?: string | undefined;
  /**
   * Comma-separated list of fields to search. Must be valid searchable fields. If omitted, uses default search fields.
   */
  fields?: string | undefined;
  /**
   * Filter by organization status. Accepts multiple comma-separated values.
   */
  status?: string | undefined;
};

/** @internal */
export const ListOrganizationsSecurity$inboundSchema: z.ZodType<
  ListOrganizationsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListOrganizationsSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListOrganizationsSecurity$outboundSchema: z.ZodType<
  ListOrganizationsSecurity$Outbound,
  z.ZodTypeDef,
  ListOrganizationsSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListOrganizationsSecurity$ {
  /** @deprecated use `ListOrganizationsSecurity$inboundSchema` instead. */
  export const inboundSchema = ListOrganizationsSecurity$inboundSchema;
  /** @deprecated use `ListOrganizationsSecurity$outboundSchema` instead. */
  export const outboundSchema = ListOrganizationsSecurity$outboundSchema;
  /** @deprecated use `ListOrganizationsSecurity$Outbound` instead. */
  export type Outbound = ListOrganizationsSecurity$Outbound;
}

export function listOrganizationsSecurityToJSON(
  listOrganizationsSecurity: ListOrganizationsSecurity,
): string {
  return JSON.stringify(
    ListOrganizationsSecurity$outboundSchema.parse(listOrganizationsSecurity),
  );
}

export function listOrganizationsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsSecurity' from JSON`,
  );
}

/** @internal */
export const ListOrganizationsRequest$inboundSchema: z.ZodType<
  ListOrganizationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  status: z.string().optional(),
});

/** @internal */
export type ListOrganizationsRequest$Outbound = {
  page: number;
  limit: number;
  search?: string | undefined;
  fields?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const ListOrganizationsRequest$outboundSchema: z.ZodType<
  ListOrganizationsRequest$Outbound,
  z.ZodTypeDef,
  ListOrganizationsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  status: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListOrganizationsRequest$ {
  /** @deprecated use `ListOrganizationsRequest$inboundSchema` instead. */
  export const inboundSchema = ListOrganizationsRequest$inboundSchema;
  /** @deprecated use `ListOrganizationsRequest$outboundSchema` instead. */
  export const outboundSchema = ListOrganizationsRequest$outboundSchema;
  /** @deprecated use `ListOrganizationsRequest$Outbound` instead. */
  export type Outbound = ListOrganizationsRequest$Outbound;
}

export function listOrganizationsRequestToJSON(
  listOrganizationsRequest: ListOrganizationsRequest,
): string {
  return JSON.stringify(
    ListOrganizationsRequest$outboundSchema.parse(listOrganizationsRequest),
  );
}

export function listOrganizationsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsRequest' from JSON`,
  );
}
