/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type ListNoncesResponseBody = {
  success: true;
  data: Array<components.Nonce>;
};

/** @internal */
export const ListNoncesResponseBody$inboundSchema: z.ZodType<
  ListNoncesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(components.Nonce$inboundSchema),
});

/** @internal */
export type ListNoncesResponseBody$Outbound = {
  success: true;
  data: Array<components.Nonce$Outbound>;
};

/** @internal */
export const ListNoncesResponseBody$outboundSchema: z.ZodType<
  ListNoncesResponseBody$Outbound,
  z.ZodTypeDef,
  ListNoncesResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(components.Nonce$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListNoncesResponseBody$ {
  /** @deprecated use `ListNoncesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListNoncesResponseBody$inboundSchema;
  /** @deprecated use `ListNoncesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListNoncesResponseBody$outboundSchema;
  /** @deprecated use `ListNoncesResponseBody$Outbound` instead. */
  export type Outbound = ListNoncesResponseBody$Outbound;
}

export function listNoncesResponseBodyToJSON(
  listNoncesResponseBody: ListNoncesResponseBody,
): string {
  return JSON.stringify(
    ListNoncesResponseBody$outboundSchema.parse(listNoncesResponseBody),
  );
}

export function listNoncesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListNoncesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListNoncesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListNoncesResponseBody' from JSON`,
  );
}
