/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListProposalsSecurity = {
  bearerAuth?: string | undefined;
};

export type ListProposalsRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Text to search for across searchable fields
   */
  search?: string | undefined;
  /**
   * Comma-separated list of fields to search. Must be valid searchable fields. If omitted, uses default search fields.
   */
  fields?: string | undefined;
  /**
   * Filter by proposal status. Accepts multiple comma-separated values. Visibility rules apply: drafts only visible to owner, staking+ visible to all.
   */
  status?: string | undefined;
  /**
   * Filter by organization ID. Accepts multiple comma-separated values.
   */
  organizationId?: string | undefined;
};

export type ListProposalsPagination = {
  page: number;
  limit: number;
  total: number;
};

/**
 * Proposals retrieved
 */
export type ListProposalsResponseBody = {
  success: boolean;
  pagination?: ListProposalsPagination | undefined;
  data?: Array<components.ProposalSummary> | undefined;
};

/** @internal */
export const ListProposalsSecurity$inboundSchema: z.ZodType<
  ListProposalsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListProposalsSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListProposalsSecurity$outboundSchema: z.ZodType<
  ListProposalsSecurity$Outbound,
  z.ZodTypeDef,
  ListProposalsSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalsSecurity$ {
  /** @deprecated use `ListProposalsSecurity$inboundSchema` instead. */
  export const inboundSchema = ListProposalsSecurity$inboundSchema;
  /** @deprecated use `ListProposalsSecurity$outboundSchema` instead. */
  export const outboundSchema = ListProposalsSecurity$outboundSchema;
  /** @deprecated use `ListProposalsSecurity$Outbound` instead. */
  export type Outbound = ListProposalsSecurity$Outbound;
}

export function listProposalsSecurityToJSON(
  listProposalsSecurity: ListProposalsSecurity,
): string {
  return JSON.stringify(
    ListProposalsSecurity$outboundSchema.parse(listProposalsSecurity),
  );
}

export function listProposalsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalsSecurity' from JSON`,
  );
}

/** @internal */
export const ListProposalsRequest$inboundSchema: z.ZodType<
  ListProposalsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  status: z.string().optional(),
  organizationId: z.string().optional(),
});

/** @internal */
export type ListProposalsRequest$Outbound = {
  page: number;
  limit: number;
  search?: string | undefined;
  fields?: string | undefined;
  status?: string | undefined;
  organizationId?: string | undefined;
};

/** @internal */
export const ListProposalsRequest$outboundSchema: z.ZodType<
  ListProposalsRequest$Outbound,
  z.ZodTypeDef,
  ListProposalsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  search: z.string().optional(),
  fields: z.string().optional(),
  status: z.string().optional(),
  organizationId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalsRequest$ {
  /** @deprecated use `ListProposalsRequest$inboundSchema` instead. */
  export const inboundSchema = ListProposalsRequest$inboundSchema;
  /** @deprecated use `ListProposalsRequest$outboundSchema` instead. */
  export const outboundSchema = ListProposalsRequest$outboundSchema;
  /** @deprecated use `ListProposalsRequest$Outbound` instead. */
  export type Outbound = ListProposalsRequest$Outbound;
}

export function listProposalsRequestToJSON(
  listProposalsRequest: ListProposalsRequest,
): string {
  return JSON.stringify(
    ListProposalsRequest$outboundSchema.parse(listProposalsRequest),
  );
}

export function listProposalsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalsRequest' from JSON`,
  );
}

/** @internal */
export const ListProposalsPagination$inboundSchema: z.ZodType<
  ListProposalsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/** @internal */
export type ListProposalsPagination$Outbound = {
  page: number;
  limit: number;
  total: number;
};

/** @internal */
export const ListProposalsPagination$outboundSchema: z.ZodType<
  ListProposalsPagination$Outbound,
  z.ZodTypeDef,
  ListProposalsPagination
> = z.object({
  page: z.number().int(),
  limit: z.number().int(),
  total: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalsPagination$ {
  /** @deprecated use `ListProposalsPagination$inboundSchema` instead. */
  export const inboundSchema = ListProposalsPagination$inboundSchema;
  /** @deprecated use `ListProposalsPagination$outboundSchema` instead. */
  export const outboundSchema = ListProposalsPagination$outboundSchema;
  /** @deprecated use `ListProposalsPagination$Outbound` instead. */
  export type Outbound = ListProposalsPagination$Outbound;
}

export function listProposalsPaginationToJSON(
  listProposalsPagination: ListProposalsPagination,
): string {
  return JSON.stringify(
    ListProposalsPagination$outboundSchema.parse(listProposalsPagination),
  );
}

export function listProposalsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalsPagination' from JSON`,
  );
}

/** @internal */
export const ListProposalsResponseBody$inboundSchema: z.ZodType<
  ListProposalsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListProposalsPagination$inboundSchema).optional(),
  data: z.array(components.ProposalSummary$inboundSchema).optional(),
});

/** @internal */
export type ListProposalsResponseBody$Outbound = {
  success: boolean;
  pagination?: ListProposalsPagination$Outbound | undefined;
  data?: Array<components.ProposalSummary$Outbound> | undefined;
};

/** @internal */
export const ListProposalsResponseBody$outboundSchema: z.ZodType<
  ListProposalsResponseBody$Outbound,
  z.ZodTypeDef,
  ListProposalsResponseBody
> = z.object({
  success: z.boolean(),
  pagination: z.lazy(() => ListProposalsPagination$outboundSchema).optional(),
  data: z.array(components.ProposalSummary$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalsResponseBody$ {
  /** @deprecated use `ListProposalsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListProposalsResponseBody$inboundSchema;
  /** @deprecated use `ListProposalsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListProposalsResponseBody$outboundSchema;
  /** @deprecated use `ListProposalsResponseBody$Outbound` instead. */
  export type Outbound = ListProposalsResponseBody$Outbound;
}

export function listProposalsResponseBodyToJSON(
  listProposalsResponseBody: ListProposalsResponseBody,
): string {
  return JSON.stringify(
    ListProposalsResponseBody$outboundSchema.parse(listProposalsResponseBody),
  );
}

export function listProposalsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalsResponseBody' from JSON`,
  );
}
