/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter by market side
 */
export const Side = {
  Pass: "pass",
  Fail: "fail",
} as const;
/**
 * Filter by market side
 */
export type Side = ClosedEnum<typeof Side>;

export type ListProposalTradesRequest = {
  id: number;
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Filter by market side
   */
  side?: Side | undefined;
};

/** @internal */
export const Side$inboundSchema: z.ZodNativeEnum<typeof Side> = z.nativeEnum(
  Side,
);

/** @internal */
export const Side$outboundSchema: z.ZodNativeEnum<typeof Side> =
  Side$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Side$ {
  /** @deprecated use `Side$inboundSchema` instead. */
  export const inboundSchema = Side$inboundSchema;
  /** @deprecated use `Side$outboundSchema` instead. */
  export const outboundSchema = Side$outboundSchema;
}

/** @internal */
export const ListProposalTradesRequest$inboundSchema: z.ZodType<
  ListProposalTradesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$inboundSchema.optional(),
});

/** @internal */
export type ListProposalTradesRequest$Outbound = {
  id: number;
  page: number;
  limit: number;
  side?: string | undefined;
};

/** @internal */
export const ListProposalTradesRequest$outboundSchema: z.ZodType<
  ListProposalTradesRequest$Outbound,
  z.ZodTypeDef,
  ListProposalTradesRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  side: Side$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProposalTradesRequest$ {
  /** @deprecated use `ListProposalTradesRequest$inboundSchema` instead. */
  export const inboundSchema = ListProposalTradesRequest$inboundSchema;
  /** @deprecated use `ListProposalTradesRequest$outboundSchema` instead. */
  export const outboundSchema = ListProposalTradesRequest$outboundSchema;
  /** @deprecated use `ListProposalTradesRequest$Outbound` instead. */
  export type Outbound = ListProposalTradesRequest$Outbound;
}

export function listProposalTradesRequestToJSON(
  listProposalTradesRequest: ListProposalTradesRequest,
): string {
  return JSON.stringify(
    ListProposalTradesRequest$outboundSchema.parse(listProposalTradesRequest),
  );
}

export function listProposalTradesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListProposalTradesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProposalTradesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProposalTradesRequest' from JSON`,
  );
}
