/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditLogsRequest = {
  /**
   * Page number (1-indexed)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  action?: components.AuditAction | undefined;
  targetType?: components.TargetType | undefined;
  /**
   * Filter by admin who performed the action
   */
  userId?: number | undefined;
};

/** @internal */
export const ListAuditLogsRequest$inboundSchema: z.ZodType<
  ListAuditLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: components.AuditAction$inboundSchema.optional(),
  targetType: components.TargetType$inboundSchema.optional(),
  userId: z.number().int().optional(),
});

/** @internal */
export type ListAuditLogsRequest$Outbound = {
  page: number;
  limit: number;
  action?: string | undefined;
  targetType?: string | undefined;
  userId?: number | undefined;
};

/** @internal */
export const ListAuditLogsRequest$outboundSchema: z.ZodType<
  ListAuditLogsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditLogsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
  action: components.AuditAction$outboundSchema.optional(),
  targetType: components.TargetType$outboundSchema.optional(),
  userId: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAuditLogsRequest$ {
  /** @deprecated use `ListAuditLogsRequest$inboundSchema` instead. */
  export const inboundSchema = ListAuditLogsRequest$inboundSchema;
  /** @deprecated use `ListAuditLogsRequest$outboundSchema` instead. */
  export const outboundSchema = ListAuditLogsRequest$outboundSchema;
  /** @deprecated use `ListAuditLogsRequest$Outbound` instead. */
  export type Outbound = ListAuditLogsRequest$Outbound;
}

export function listAuditLogsRequestToJSON(
  listAuditLogsRequest: ListAuditLogsRequest,
): string {
  return JSON.stringify(
    ListAuditLogsRequest$outboundSchema.parse(listAuditLogsRequest),
  );
}

export function listAuditLogsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditLogsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditLogsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditLogsRequest' from JSON`,
  );
}
