/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListContributionsSecurity = {
  bearer?: string | undefined;
};

export type ListContributionsRequest = {
  id: number;
  page?: number | undefined;
  limit?: number | undefined;
};

/**
 * OK
 */
export type ListContributionsResponseBody = {
  success: true;
  data: Array<components.RaiseContribution>;
  pagination: components.Pagination;
};

/** @internal */
export const ListContributionsSecurity$inboundSchema: z.ZodType<
  ListContributionsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearer: z.string().optional(),
});

/** @internal */
export type ListContributionsSecurity$Outbound = {
  bearer?: string | undefined;
};

/** @internal */
export const ListContributionsSecurity$outboundSchema: z.ZodType<
  ListContributionsSecurity$Outbound,
  z.ZodTypeDef,
  ListContributionsSecurity
> = z.object({
  bearer: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListContributionsSecurity$ {
  /** @deprecated use `ListContributionsSecurity$inboundSchema` instead. */
  export const inboundSchema = ListContributionsSecurity$inboundSchema;
  /** @deprecated use `ListContributionsSecurity$outboundSchema` instead. */
  export const outboundSchema = ListContributionsSecurity$outboundSchema;
  /** @deprecated use `ListContributionsSecurity$Outbound` instead. */
  export type Outbound = ListContributionsSecurity$Outbound;
}

export function listContributionsSecurityToJSON(
  listContributionsSecurity: ListContributionsSecurity,
): string {
  return JSON.stringify(
    ListContributionsSecurity$outboundSchema.parse(listContributionsSecurity),
  );
}

export function listContributionsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListContributionsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContributionsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContributionsSecurity' from JSON`,
  );
}

/** @internal */
export const ListContributionsRequest$inboundSchema: z.ZodType<
  ListContributionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
});

/** @internal */
export type ListContributionsRequest$Outbound = {
  id: number;
  page: number;
  limit: number;
};

/** @internal */
export const ListContributionsRequest$outboundSchema: z.ZodType<
  ListContributionsRequest$Outbound,
  z.ZodTypeDef,
  ListContributionsRequest
> = z.object({
  id: z.number().int(),
  page: z.number().int().default(1),
  limit: z.number().int().default(20),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListContributionsRequest$ {
  /** @deprecated use `ListContributionsRequest$inboundSchema` instead. */
  export const inboundSchema = ListContributionsRequest$inboundSchema;
  /** @deprecated use `ListContributionsRequest$outboundSchema` instead. */
  export const outboundSchema = ListContributionsRequest$outboundSchema;
  /** @deprecated use `ListContributionsRequest$Outbound` instead. */
  export type Outbound = ListContributionsRequest$Outbound;
}

export function listContributionsRequestToJSON(
  listContributionsRequest: ListContributionsRequest,
): string {
  return JSON.stringify(
    ListContributionsRequest$outboundSchema.parse(listContributionsRequest),
  );
}

export function listContributionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListContributionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContributionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContributionsRequest' from JSON`,
  );
}

/** @internal */
export const ListContributionsResponseBody$inboundSchema: z.ZodType<
  ListContributionsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(components.RaiseContribution$inboundSchema),
  pagination: components.Pagination$inboundSchema,
});

/** @internal */
export type ListContributionsResponseBody$Outbound = {
  success: true;
  data: Array<components.RaiseContribution$Outbound>;
  pagination: components.Pagination$Outbound;
};

/** @internal */
export const ListContributionsResponseBody$outboundSchema: z.ZodType<
  ListContributionsResponseBody$Outbound,
  z.ZodTypeDef,
  ListContributionsResponseBody
> = z.object({
  success: z.literal(true),
  data: z.array(components.RaiseContribution$outboundSchema),
  pagination: components.Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListContributionsResponseBody$ {
  /** @deprecated use `ListContributionsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListContributionsResponseBody$inboundSchema;
  /** @deprecated use `ListContributionsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListContributionsResponseBody$outboundSchema;
  /** @deprecated use `ListContributionsResponseBody$Outbound` instead. */
  export type Outbound = ListContributionsResponseBody$Outbound;
}

export function listContributionsResponseBodyToJSON(
  listContributionsResponseBody: ListContributionsResponseBody,
): string {
  return JSON.stringify(
    ListContributionsResponseBody$outboundSchema.parse(
      listContributionsResponseBody,
    ),
  );
}

export function listContributionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListContributionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContributionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContributionsResponseBody' from JSON`,
  );
}
