/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginRequestBody = {
  /**
   * The EVM wallet address
   */
  address: string;
  /**
   * The nonce used in the signed message
   */
  nonce: number;
  /**
   * The signature generated by the wallet
   */
  signature: string;
};

/** @internal */
export const LoginRequestBody$inboundSchema: z.ZodType<
  LoginRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
  nonce: z.number().int(),
  signature: z.string(),
});

/** @internal */
export type LoginRequestBody$Outbound = {
  address: string;
  nonce: number;
  signature: string;
};

/** @internal */
export const LoginRequestBody$outboundSchema: z.ZodType<
  LoginRequestBody$Outbound,
  z.ZodTypeDef,
  LoginRequestBody
> = z.object({
  address: z.string(),
  nonce: z.number().int(),
  signature: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginRequestBody$ {
  /** @deprecated use `LoginRequestBody$inboundSchema` instead. */
  export const inboundSchema = LoginRequestBody$inboundSchema;
  /** @deprecated use `LoginRequestBody$outboundSchema` instead. */
  export const outboundSchema = LoginRequestBody$outboundSchema;
  /** @deprecated use `LoginRequestBody$Outbound` instead. */
  export type Outbound = LoginRequestBody$Outbound;
}

export function loginRequestBodyToJSON(
  loginRequestBody: LoginRequestBody,
): string {
  return JSON.stringify(
    LoginRequestBody$outboundSchema.parse(loginRequestBody),
  );
}

export function loginRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<LoginRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginRequestBody' from JSON`,
  );
}
