/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LogoutRequestBody = {
  all?: boolean | undefined;
};

/**
 * Logged out
 */
export type LogoutResponseBody = {
  success: true;
};

/** @internal */
export const LogoutRequestBody$inboundSchema: z.ZodType<
  LogoutRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  all: z.boolean().default(false),
});

/** @internal */
export type LogoutRequestBody$Outbound = {
  all: boolean;
};

/** @internal */
export const LogoutRequestBody$outboundSchema: z.ZodType<
  LogoutRequestBody$Outbound,
  z.ZodTypeDef,
  LogoutRequestBody
> = z.object({
  all: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LogoutRequestBody$ {
  /** @deprecated use `LogoutRequestBody$inboundSchema` instead. */
  export const inboundSchema = LogoutRequestBody$inboundSchema;
  /** @deprecated use `LogoutRequestBody$outboundSchema` instead. */
  export const outboundSchema = LogoutRequestBody$outboundSchema;
  /** @deprecated use `LogoutRequestBody$Outbound` instead. */
  export type Outbound = LogoutRequestBody$Outbound;
}

export function logoutRequestBodyToJSON(
  logoutRequestBody: LogoutRequestBody,
): string {
  return JSON.stringify(
    LogoutRequestBody$outboundSchema.parse(logoutRequestBody),
  );
}

export function logoutRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<LogoutRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogoutRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogoutRequestBody' from JSON`,
  );
}

/** @internal */
export const LogoutResponseBody$inboundSchema: z.ZodType<
  LogoutResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
});

/** @internal */
export type LogoutResponseBody$Outbound = {
  success: true;
};

/** @internal */
export const LogoutResponseBody$outboundSchema: z.ZodType<
  LogoutResponseBody$Outbound,
  z.ZodTypeDef,
  LogoutResponseBody
> = z.object({
  success: z.literal(true),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LogoutResponseBody$ {
  /** @deprecated use `LogoutResponseBody$inboundSchema` instead. */
  export const inboundSchema = LogoutResponseBody$inboundSchema;
  /** @deprecated use `LogoutResponseBody$outboundSchema` instead. */
  export const outboundSchema = LogoutResponseBody$outboundSchema;
  /** @deprecated use `LogoutResponseBody$Outbound` instead. */
  export type Outbound = LogoutResponseBody$Outbound;
}

export function logoutResponseBodyToJSON(
  logoutResponseBody: LogoutResponseBody,
): string {
  return JSON.stringify(
    LogoutResponseBody$outboundSchema.parse(logoutResponseBody),
  );
}

export function logoutResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LogoutResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogoutResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogoutResponseBody' from JSON`,
  );
}
