/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Err,
  Err$inboundSchema,
  Err$Outbound,
  Err$outboundSchema,
} from "../components/err.js";
import {
  Ok,
  Ok$inboundSchema,
  Ok$Outbound,
  Ok$outboundSchema,
} from "../components/ok.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LogoutRequestBody = {
  /**
   * If true, logout from all devices
   */
  deactivateAllNonces?: boolean | undefined;
};

export type LogoutResponse = Err | Ok;

/** @internal */
export const LogoutRequestBody$inboundSchema: z.ZodType<
  LogoutRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  deactivateAllNonces: z.boolean().default(false),
});

/** @internal */
export type LogoutRequestBody$Outbound = {
  deactivateAllNonces: boolean;
};

/** @internal */
export const LogoutRequestBody$outboundSchema: z.ZodType<
  LogoutRequestBody$Outbound,
  z.ZodTypeDef,
  LogoutRequestBody
> = z.object({
  deactivateAllNonces: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LogoutRequestBody$ {
  /** @deprecated use `LogoutRequestBody$inboundSchema` instead. */
  export const inboundSchema = LogoutRequestBody$inboundSchema;
  /** @deprecated use `LogoutRequestBody$outboundSchema` instead. */
  export const outboundSchema = LogoutRequestBody$outboundSchema;
  /** @deprecated use `LogoutRequestBody$Outbound` instead. */
  export type Outbound = LogoutRequestBody$Outbound;
}

export function logoutRequestBodyToJSON(
  logoutRequestBody: LogoutRequestBody,
): string {
  return JSON.stringify(
    LogoutRequestBody$outboundSchema.parse(logoutRequestBody),
  );
}

export function logoutRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<LogoutRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogoutRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogoutRequestBody' from JSON`,
  );
}

/** @internal */
export const LogoutResponse$inboundSchema: z.ZodType<
  LogoutResponse,
  z.ZodTypeDef,
  unknown
> = z.union([Err$inboundSchema, Ok$inboundSchema]);

/** @internal */
export type LogoutResponse$Outbound = Err$Outbound | Ok$Outbound;

/** @internal */
export const LogoutResponse$outboundSchema: z.ZodType<
  LogoutResponse$Outbound,
  z.ZodTypeDef,
  LogoutResponse
> = z.union([Err$outboundSchema, Ok$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LogoutResponse$ {
  /** @deprecated use `LogoutResponse$inboundSchema` instead. */
  export const inboundSchema = LogoutResponse$inboundSchema;
  /** @deprecated use `LogoutResponse$outboundSchema` instead. */
  export const outboundSchema = LogoutResponse$outboundSchema;
  /** @deprecated use `LogoutResponse$Outbound` instead. */
  export type Outbound = LogoutResponse$Outbound;
}

export function logoutResponseToJSON(logoutResponse: LogoutResponse): string {
  return JSON.stringify(LogoutResponse$outboundSchema.parse(logoutResponse));
}

export function logoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<LogoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogoutResponse' from JSON`,
  );
}
