/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateUserRequestBody = {
  name?: string | undefined;
  imageUrl?: string | undefined;
};

export type UpdateUserRequest = {
  id: number;
  requestBody?: UpdateUserRequestBody | undefined;
};

/**
 * Updated
 */
export type UpdateUserResponseBody = {
  success: true;
  data: components.User;
};

/** @internal */
export const UpdateUserRequestBody$inboundSchema: z.ZodType<
  UpdateUserRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  imageUrl: z.string().optional(),
});

/** @internal */
export type UpdateUserRequestBody$Outbound = {
  name?: string | undefined;
  imageUrl?: string | undefined;
};

/** @internal */
export const UpdateUserRequestBody$outboundSchema: z.ZodType<
  UpdateUserRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateUserRequestBody
> = z.object({
  name: z.string().optional(),
  imageUrl: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserRequestBody$ {
  /** @deprecated use `UpdateUserRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateUserRequestBody$inboundSchema;
  /** @deprecated use `UpdateUserRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateUserRequestBody$outboundSchema;
  /** @deprecated use `UpdateUserRequestBody$Outbound` instead. */
  export type Outbound = UpdateUserRequestBody$Outbound;
}

export function updateUserRequestBodyToJSON(
  updateUserRequestBody: UpdateUserRequestBody,
): string {
  return JSON.stringify(
    UpdateUserRequestBody$outboundSchema.parse(updateUserRequestBody),
  );
}

export function updateUserRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUserRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUserRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUserRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateUserRequest$inboundSchema: z.ZodType<
  UpdateUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  RequestBody: z.lazy(() => UpdateUserRequestBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateUserRequest$Outbound = {
  id: number;
  RequestBody?: UpdateUserRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdateUserRequest$outboundSchema: z.ZodType<
  UpdateUserRequest$Outbound,
  z.ZodTypeDef,
  UpdateUserRequest
> = z.object({
  id: z.number().int(),
  requestBody: z.lazy(() => UpdateUserRequestBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserRequest$ {
  /** @deprecated use `UpdateUserRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateUserRequest$inboundSchema;
  /** @deprecated use `UpdateUserRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateUserRequest$outboundSchema;
  /** @deprecated use `UpdateUserRequest$Outbound` instead. */
  export type Outbound = UpdateUserRequest$Outbound;
}

export function updateUserRequestToJSON(
  updateUserRequest: UpdateUserRequest,
): string {
  return JSON.stringify(
    UpdateUserRequest$outboundSchema.parse(updateUserRequest),
  );
}

export function updateUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUserRequest' from JSON`,
  );
}

/** @internal */
export const UpdateUserResponseBody$inboundSchema: z.ZodType<
  UpdateUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: components.User$inboundSchema,
});

/** @internal */
export type UpdateUserResponseBody$Outbound = {
  success: true;
  data: components.User$Outbound;
};

/** @internal */
export const UpdateUserResponseBody$outboundSchema: z.ZodType<
  UpdateUserResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateUserResponseBody
> = z.object({
  success: z.literal(true),
  data: components.User$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserResponseBody$ {
  /** @deprecated use `UpdateUserResponseBody$inboundSchema` instead. */
  export const inboundSchema = UpdateUserResponseBody$inboundSchema;
  /** @deprecated use `UpdateUserResponseBody$outboundSchema` instead. */
  export const outboundSchema = UpdateUserResponseBody$outboundSchema;
  /** @deprecated use `UpdateUserResponseBody$Outbound` instead. */
  export type Outbound = UpdateUserResponseBody$Outbound;
}

export function updateUserResponseBodyToJSON(
  updateUserResponseBody: UpdateUserResponseBody,
): string {
  return JSON.stringify(
    UpdateUserResponseBody$outboundSchema.parse(updateUserResponseBody),
  );
}

export function updateUserResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUserResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUserResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUserResponseBody' from JSON`,
  );
}
