/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateProposalRequest = {
  id: number;
  updateProposal?: components.UpdateProposal | undefined;
};

/**
 * Updated
 */
export type UpdateProposalResponseBody = {
  success: true;
  data: components.Proposal;
};

/** @internal */
export const UpdateProposalRequest$inboundSchema: z.ZodType<
  UpdateProposalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  UpdateProposal: components.UpdateProposal$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "UpdateProposal": "updateProposal",
  });
});

/** @internal */
export type UpdateProposalRequest$Outbound = {
  id: number;
  UpdateProposal?: components.UpdateProposal$Outbound | undefined;
};

/** @internal */
export const UpdateProposalRequest$outboundSchema: z.ZodType<
  UpdateProposalRequest$Outbound,
  z.ZodTypeDef,
  UpdateProposalRequest
> = z.object({
  id: z.number().int(),
  updateProposal: components.UpdateProposal$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    updateProposal: "UpdateProposal",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateProposalRequest$ {
  /** @deprecated use `UpdateProposalRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateProposalRequest$inboundSchema;
  /** @deprecated use `UpdateProposalRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateProposalRequest$outboundSchema;
  /** @deprecated use `UpdateProposalRequest$Outbound` instead. */
  export type Outbound = UpdateProposalRequest$Outbound;
}

export function updateProposalRequestToJSON(
  updateProposalRequest: UpdateProposalRequest,
): string {
  return JSON.stringify(
    UpdateProposalRequest$outboundSchema.parse(updateProposalRequest),
  );
}

export function updateProposalRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProposalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProposalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProposalRequest' from JSON`,
  );
}

/** @internal */
export const UpdateProposalResponseBody$inboundSchema: z.ZodType<
  UpdateProposalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: components.Proposal$inboundSchema,
});

/** @internal */
export type UpdateProposalResponseBody$Outbound = {
  success: true;
  data: components.Proposal$Outbound;
};

/** @internal */
export const UpdateProposalResponseBody$outboundSchema: z.ZodType<
  UpdateProposalResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateProposalResponseBody
> = z.object({
  success: z.literal(true),
  data: components.Proposal$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateProposalResponseBody$ {
  /** @deprecated use `UpdateProposalResponseBody$inboundSchema` instead. */
  export const inboundSchema = UpdateProposalResponseBody$inboundSchema;
  /** @deprecated use `UpdateProposalResponseBody$outboundSchema` instead. */
  export const outboundSchema = UpdateProposalResponseBody$outboundSchema;
  /** @deprecated use `UpdateProposalResponseBody$Outbound` instead. */
  export type Outbound = UpdateProposalResponseBody$Outbound;
}

export function updateProposalResponseBodyToJSON(
  updateProposalResponseBody: UpdateProposalResponseBody,
): string {
  return JSON.stringify(
    UpdateProposalResponseBody$outboundSchema.parse(updateProposalResponseBody),
  );
}

export function updateProposalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProposalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProposalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProposalResponseBody' from JSON`,
  );
}
