/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ContactType = {
  Email: "email",
  Telegram: "telegram",
  Discord: "discord",
} as const;
export type ContactType = ClosedEnum<typeof ContactType>;

/** @internal */
export const ContactType$inboundSchema: z.ZodNativeEnum<typeof ContactType> = z
  .nativeEnum(ContactType);

/** @internal */
export const ContactType$outboundSchema: z.ZodNativeEnum<typeof ContactType> =
  ContactType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactType$ {
  /** @deprecated use `ContactType$inboundSchema` instead. */
  export const inboundSchema = ContactType$inboundSchema;
  /** @deprecated use `ContactType$outboundSchema` instead. */
  export const outboundSchema = ContactType$outboundSchema;
}
