/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActionType,
  ActionType$inboundSchema,
  ActionType$outboundSchema,
} from "./actiontype.js";

export type CreateProposalRequestActionData = {};

export type Actions = {
  actionType: ActionType;
  actionData: CreateProposalRequestActionData;
};

export type CreateProposalRequest = {
  organizationId: number;
  title: string;
  description: string;
  actions: Array<Actions>;
};

/** @internal */
export const CreateProposalRequestActionData$inboundSchema: z.ZodType<
  CreateProposalRequestActionData,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CreateProposalRequestActionData$Outbound = {};

/** @internal */
export const CreateProposalRequestActionData$outboundSchema: z.ZodType<
  CreateProposalRequestActionData$Outbound,
  z.ZodTypeDef,
  CreateProposalRequestActionData
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProposalRequestActionData$ {
  /** @deprecated use `CreateProposalRequestActionData$inboundSchema` instead. */
  export const inboundSchema = CreateProposalRequestActionData$inboundSchema;
  /** @deprecated use `CreateProposalRequestActionData$outboundSchema` instead. */
  export const outboundSchema = CreateProposalRequestActionData$outboundSchema;
  /** @deprecated use `CreateProposalRequestActionData$Outbound` instead. */
  export type Outbound = CreateProposalRequestActionData$Outbound;
}

export function createProposalRequestActionDataToJSON(
  createProposalRequestActionData: CreateProposalRequestActionData,
): string {
  return JSON.stringify(
    CreateProposalRequestActionData$outboundSchema.parse(
      createProposalRequestActionData,
    ),
  );
}

export function createProposalRequestActionDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateProposalRequestActionData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProposalRequestActionData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProposalRequestActionData' from JSON`,
  );
}

/** @internal */
export const Actions$inboundSchema: z.ZodType<Actions, z.ZodTypeDef, unknown> =
  z.object({
    actionType: ActionType$inboundSchema,
    actionData: z.lazy(() => CreateProposalRequestActionData$inboundSchema),
  });

/** @internal */
export type Actions$Outbound = {
  actionType: string;
  actionData: CreateProposalRequestActionData$Outbound;
};

/** @internal */
export const Actions$outboundSchema: z.ZodType<
  Actions$Outbound,
  z.ZodTypeDef,
  Actions
> = z.object({
  actionType: ActionType$outboundSchema,
  actionData: z.lazy(() => CreateProposalRequestActionData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Actions$ {
  /** @deprecated use `Actions$inboundSchema` instead. */
  export const inboundSchema = Actions$inboundSchema;
  /** @deprecated use `Actions$outboundSchema` instead. */
  export const outboundSchema = Actions$outboundSchema;
  /** @deprecated use `Actions$Outbound` instead. */
  export type Outbound = Actions$Outbound;
}

export function actionsToJSON(actions: Actions): string {
  return JSON.stringify(Actions$outboundSchema.parse(actions));
}

export function actionsFromJSON(
  jsonString: string,
): SafeParseResult<Actions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Actions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Actions' from JSON`,
  );
}

/** @internal */
export const CreateProposalRequest$inboundSchema: z.ZodType<
  CreateProposalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.number().int(),
  title: z.string(),
  description: z.string(),
  actions: z.array(z.lazy(() => Actions$inboundSchema)),
});

/** @internal */
export type CreateProposalRequest$Outbound = {
  organizationId: number;
  title: string;
  description: string;
  actions: Array<Actions$Outbound>;
};

/** @internal */
export const CreateProposalRequest$outboundSchema: z.ZodType<
  CreateProposalRequest$Outbound,
  z.ZodTypeDef,
  CreateProposalRequest
> = z.object({
  organizationId: z.number().int(),
  title: z.string(),
  description: z.string(),
  actions: z.array(z.lazy(() => Actions$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProposalRequest$ {
  /** @deprecated use `CreateProposalRequest$inboundSchema` instead. */
  export const inboundSchema = CreateProposalRequest$inboundSchema;
  /** @deprecated use `CreateProposalRequest$outboundSchema` instead. */
  export const outboundSchema = CreateProposalRequest$outboundSchema;
  /** @deprecated use `CreateProposalRequest$Outbound` instead. */
  export type Outbound = CreateProposalRequest$Outbound;
}

export function createProposalRequestToJSON(
  createProposalRequest: CreateProposalRequest,
): string {
  return JSON.stringify(
    CreateProposalRequest$outboundSchema.parse(createProposalRequest),
  );
}

export function createProposalRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateProposalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProposalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProposalRequest' from JSON`,
  );
}
