/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ErrCode,
  ErrCode$inboundSchema,
  ErrCode$outboundSchema,
} from "./errcode.js";
import {
  FieldError,
  FieldError$inboundSchema,
  FieldError$Outbound,
  FieldError$outboundSchema,
} from "./fielderror.js";

export type ErrorT = {
  /**
   * All error codes that can be returned from the backend
   */
  code: ErrCode;
  message: string;
  /**
   * Field-level validation errors (only present for VALIDATION_ERROR)
   */
  fields?: Array<FieldError> | undefined;
};

/**
 * Error response returned when an operation fails
 */
export type Err = {
  success: false;
  error: ErrorT;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    code: ErrCode$inboundSchema,
    message: z.string(),
    fields: z.array(FieldError$inboundSchema).optional(),
  });

/** @internal */
export type ErrorT$Outbound = {
  code: string;
  message: string;
  fields?: Array<FieldError$Outbound> | undefined;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  code: ErrCode$outboundSchema,
  message: z.string(),
  fields: z.array(FieldError$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorT$ {
  /** @deprecated use `ErrorT$inboundSchema` instead. */
  export const inboundSchema = ErrorT$inboundSchema;
  /** @deprecated use `ErrorT$outboundSchema` instead. */
  export const outboundSchema = ErrorT$outboundSchema;
  /** @deprecated use `ErrorT$Outbound` instead. */
  export type Outbound = ErrorT$Outbound;
}

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const Err$inboundSchema: z.ZodType<Err, z.ZodTypeDef, unknown> = z
  .object({
    success: z.literal(false),
    error: z.lazy(() => ErrorT$inboundSchema),
  });

/** @internal */
export type Err$Outbound = {
  success: false;
  error: ErrorT$Outbound;
};

/** @internal */
export const Err$outboundSchema: z.ZodType<Err$Outbound, z.ZodTypeDef, Err> = z
  .object({
    success: z.literal(false),
    error: z.lazy(() => ErrorT$outboundSchema),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Err$ {
  /** @deprecated use `Err$inboundSchema` instead. */
  export const inboundSchema = Err$inboundSchema;
  /** @deprecated use `Err$outboundSchema` instead. */
  export const outboundSchema = Err$outboundSchema;
  /** @deprecated use `Err$Outbound` instead. */
  export type Outbound = Err$Outbound;
}

export function errToJSON(err: Err): string {
  return JSON.stringify(Err$outboundSchema.parse(err));
}

export function errFromJSON(
  jsonString: string,
): SafeParseResult<Err, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Err$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Err' from JSON`,
  );
}
