/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * All error codes that can be returned from the backend
 */
export const ErrCode = {
  InternalServerError: "INTERNAL_SERVER_ERROR",
  ValidationError: "VALIDATION_ERROR",
  InvalidSignature: "INVALID_SIGNATURE",
  InvalidActionData: "INVALID_ACTION_DATA",
  EmptyActions: "EMPTY_ACTIONS",
  InvalidStatusTransition: "INVALID_STATUS_TRANSITION",
  InvalidOrgType: "INVALID_ORG_TYPE",
  InsufficientTokenBalance: "INSUFFICIENT_TOKEN_BALANCE",
  InvalidToken: "INVALID_TOKEN",
  ExpiredToken: "EXPIRED_TOKEN",
  InactiveNonce: "INACTIVE_NONCE",
  NotAuthorized: "NOT_AUTHORIZED",
  UserNotFound: "USER_NOT_FOUND",
  NonceNotFound: "NONCE_NOT_FOUND",
  OrganizationNotFound: "ORGANIZATION_NOT_FOUND",
  ProposalNotFound: "PROPOSAL_NOT_FOUND",
  RaiseNotFound: "RAISE_NOT_FOUND",
  ProposalAlreadyActive: "PROPOSAL_ALREADY_ACTIVE",
} as const;
/**
 * All error codes that can be returned from the backend
 */
export type ErrCode = ClosedEnum<typeof ErrCode>;

/** @internal */
export const ErrCode$inboundSchema: z.ZodNativeEnum<typeof ErrCode> = z
  .nativeEnum(ErrCode);

/** @internal */
export const ErrCode$outboundSchema: z.ZodNativeEnum<typeof ErrCode> =
  ErrCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrCode$ {
  /** @deprecated use `ErrCode$inboundSchema` instead. */
  export const inboundSchema = ErrCode$inboundSchema;
  /** @deprecated use `ErrCode$outboundSchema` instead. */
  export const outboundSchema = ErrCode$outboundSchema;
}
