/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LinkType,
  LinkType$inboundSchema,
  LinkType$outboundSchema,
} from "./linktype.js";

export type LinkRequest = {
  type: LinkType;
  url: string;
};

/** @internal */
export const LinkRequest$inboundSchema: z.ZodType<
  LinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: LinkType$inboundSchema,
  url: z.string(),
});

/** @internal */
export type LinkRequest$Outbound = {
  type: string;
  url: string;
};

/** @internal */
export const LinkRequest$outboundSchema: z.ZodType<
  LinkRequest$Outbound,
  z.ZodTypeDef,
  LinkRequest
> = z.object({
  type: LinkType$outboundSchema,
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkRequest$ {
  /** @deprecated use `LinkRequest$inboundSchema` instead. */
  export const inboundSchema = LinkRequest$inboundSchema;
  /** @deprecated use `LinkRequest$outboundSchema` instead. */
  export const outboundSchema = LinkRequest$outboundSchema;
  /** @deprecated use `LinkRequest$Outbound` instead. */
  export type Outbound = LinkRequest$Outbound;
}

export function linkRequestToJSON(linkRequest: LinkRequest): string {
  return JSON.stringify(LinkRequest$outboundSchema.parse(linkRequest));
}

export function linkRequestFromJSON(
  jsonString: string,
): SafeParseResult<LinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkRequest' from JSON`,
  );
}
