/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const LinkType = {
  Website: "website",
  Twitter: "twitter",
  Discord: "discord",
  Telegram: "telegram",
  Other: "other",
} as const;
export type LinkType = ClosedEnum<typeof LinkType>;

/** @internal */
export const LinkType$inboundSchema: z.ZodNativeEnum<typeof LinkType> = z
  .nativeEnum(LinkType);

/** @internal */
export const LinkType$outboundSchema: z.ZodNativeEnum<typeof LinkType> =
  LinkType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkType$ {
  /** @deprecated use `LinkType$inboundSchema` instead. */
  export const inboundSchema = LinkType$inboundSchema;
  /** @deprecated use `LinkType$outboundSchema` instead. */
  export const outboundSchema = LinkType$outboundSchema;
}
