/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MarketSide = {
  Pass: "pass",
  Fail: "fail",
} as const;
export type MarketSide = ClosedEnum<typeof MarketSide>;

/** @internal */
export const MarketSide$inboundSchema: z.ZodNativeEnum<typeof MarketSide> = z
  .nativeEnum(MarketSide);

/** @internal */
export const MarketSide$outboundSchema: z.ZodNativeEnum<typeof MarketSide> =
  MarketSide$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MarketSide$ {
  /** @deprecated use `MarketSide$inboundSchema` instead. */
  export const inboundSchema = MarketSide$inboundSchema;
  /** @deprecated use `MarketSide$outboundSchema` instead. */
  export const outboundSchema = MarketSide$outboundSchema;
}
