/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Data = {
  nonce: number;
};

/**
 * Success response wrapper
 */
export type NonceResponse = {
  success: true;
  data: Data;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    nonce: z.number().int(),
  });

/** @internal */
export type Data$Outbound = {
  nonce: number;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    nonce: z.number().int(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const NonceResponse$inboundSchema: z.ZodType<
  NonceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$inboundSchema),
});

/** @internal */
export type NonceResponse$Outbound = {
  success: true;
  data: Data$Outbound;
};

/** @internal */
export const NonceResponse$outboundSchema: z.ZodType<
  NonceResponse$Outbound,
  z.ZodTypeDef,
  NonceResponse
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => Data$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NonceResponse$ {
  /** @deprecated use `NonceResponse$inboundSchema` instead. */
  export const inboundSchema = NonceResponse$inboundSchema;
  /** @deprecated use `NonceResponse$outboundSchema` instead. */
  export const outboundSchema = NonceResponse$outboundSchema;
  /** @deprecated use `NonceResponse$Outbound` instead. */
  export type Outbound = NonceResponse$Outbound;
}

export function nonceResponseToJSON(nonceResponse: NonceResponse): string {
  return JSON.stringify(NonceResponse$outboundSchema.parse(nonceResponse));
}

export function nonceResponseFromJSON(
  jsonString: string,
): SafeParseResult<NonceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NonceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NonceResponse' from JSON`,
  );
}
