/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success response wrapper
 */
export type Ok = {
  success: boolean;
};

/** @internal */
export const Ok$inboundSchema: z.ZodType<Ok, z.ZodTypeDef, unknown> = z.object({
  success: z.boolean(),
});

/** @internal */
export type Ok$Outbound = {
  success: boolean;
};

/** @internal */
export const Ok$outboundSchema: z.ZodType<Ok$Outbound, z.ZodTypeDef, Ok> = z
  .object({
    success: z.boolean(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ok$ {
  /** @deprecated use `Ok$inboundSchema` instead. */
  export const inboundSchema = Ok$inboundSchema;
  /** @deprecated use `Ok$outboundSchema` instead. */
  export const outboundSchema = Ok$outboundSchema;
  /** @deprecated use `Ok$Outbound` instead. */
  export type Outbound = Ok$Outbound;
}

export function okToJSON(ok: Ok): string {
  return JSON.stringify(Ok$outboundSchema.parse(ok));
}

export function okFromJSON(
  jsonString: string,
): SafeParseResult<Ok, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ok$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ok' from JSON`,
  );
}
