/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "./contactinformation.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "./organizationstatus.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "./proposal.js";
import {
  Raise,
  Raise$inboundSchema,
  Raise$Outbound,
  Raise$outboundSchema,
} from "./raise.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "./token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "./treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "./user.js";

export const Type = {
  External: "external",
  Ico: "ico",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type Organization = {
  created?: Date | undefined;
  updated?: Date | undefined;
  id: number;
  type: Type;
  name: string;
  slug: string;
  imageUrl?: string | undefined;
  bannerUrl?: string | undefined;
  description: string;
  status: OrganizationStatus;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  raise?: Raise | undefined;
  proposals?: Array<Proposal> | undefined;
  user?: User | undefined;
  userId: number;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const Organization$inboundSchema: z.ZodType<
  Organization,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  id: z.number().int(),
  type: Type$inboundSchema,
  name: z.string(),
  slug: z.string(),
  imageUrl: z.string().optional(),
  bannerUrl: z.string().optional(),
  description: z.string(),
  status: OrganizationStatus$inboundSchema,
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  raise: Raise$inboundSchema.optional(),
  proposals: z.array(Proposal$inboundSchema).optional(),
  user: User$inboundSchema.optional(),
  userId: z.number().int(),
});

/** @internal */
export type Organization$Outbound = {
  created?: string | undefined;
  updated?: string | undefined;
  id: number;
  type: string;
  name: string;
  slug: string;
  imageUrl?: string | undefined;
  bannerUrl?: string | undefined;
  description: string;
  status: string;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  raise?: Raise$Outbound | undefined;
  proposals?: Array<Proposal$Outbound> | undefined;
  user?: User$Outbound | undefined;
  userId: number;
};

/** @internal */
export const Organization$outboundSchema: z.ZodType<
  Organization$Outbound,
  z.ZodTypeDef,
  Organization
> = z.object({
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  id: z.number().int(),
  type: Type$outboundSchema,
  name: z.string(),
  slug: z.string(),
  imageUrl: z.string().optional(),
  bannerUrl: z.string().optional(),
  description: z.string(),
  status: OrganizationStatus$outboundSchema,
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  raise: Raise$outboundSchema.optional(),
  proposals: z.array(Proposal$outboundSchema).optional(),
  user: User$outboundSchema.optional(),
  userId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Organization$ {
  /** @deprecated use `Organization$inboundSchema` instead. */
  export const inboundSchema = Organization$inboundSchema;
  /** @deprecated use `Organization$outboundSchema` instead. */
  export const outboundSchema = Organization$outboundSchema;
  /** @deprecated use `Organization$Outbound` instead. */
  export type Outbound = Organization$Outbound;
}

export function organizationToJSON(organization: Organization): string {
  return JSON.stringify(Organization$outboundSchema.parse(organization));
}

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
