/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "./contactinformation.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "./organizationstatus.js";
import {
  RaiseAllocation,
  RaiseAllocation$inboundSchema,
  RaiseAllocation$Outbound,
  RaiseAllocation$outboundSchema,
} from "./raiseallocation.js";
import {
  RaiseContribution,
  RaiseContribution$inboundSchema,
  RaiseContribution$Outbound,
  RaiseContribution$outboundSchema,
} from "./raisecontribution.js";
import {
  RaiseStatus,
  RaiseStatus$inboundSchema,
  RaiseStatus$outboundSchema,
} from "./raisestatus.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "./token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "./treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "./user.js";

export const Type = {
  External: "external",
  Ico: "ico",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type Raise = {
  id?: number | undefined;
  /**
   * EVM address of the raise contract
   */
  address?: string | null | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: Date | null | undefined;
  endDate?: Date | null | undefined;
  status?: RaiseStatus | undefined;
  allocations?: Array<RaiseAllocation> | undefined;
  contributions?: Array<RaiseContribution> | undefined;
};

export type Organization = {
  id?: number | undefined;
  type?: Type | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  /**
   * Only present for ICO organizations
   */
  raise?: Raise | null | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const Raise$inboundSchema: z.ZodType<Raise, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    address: z.nullable(z.string()).optional(),
    softCap: z.number().optional(),
    acceptedAmount: z.number().optional(),
    balance: z.number().optional(),
    startDate: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    endDate: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    status: RaiseStatus$inboundSchema.optional(),
    allocations: z.array(RaiseAllocation$inboundSchema).optional(),
    contributions: z.array(RaiseContribution$inboundSchema).optional(),
  });

/** @internal */
export type Raise$Outbound = {
  id?: number | undefined;
  address?: string | null | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: string | null | undefined;
  endDate?: string | null | undefined;
  status?: string | undefined;
  allocations?: Array<RaiseAllocation$Outbound> | undefined;
  contributions?: Array<RaiseContribution$Outbound> | undefined;
};

/** @internal */
export const Raise$outboundSchema: z.ZodType<
  Raise$Outbound,
  z.ZodTypeDef,
  Raise
> = z.object({
  id: z.number().int().optional(),
  address: z.nullable(z.string()).optional(),
  softCap: z.number().optional(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  endDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  status: RaiseStatus$outboundSchema.optional(),
  allocations: z.array(RaiseAllocation$outboundSchema).optional(),
  contributions: z.array(RaiseContribution$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Raise$ {
  /** @deprecated use `Raise$inboundSchema` instead. */
  export const inboundSchema = Raise$inboundSchema;
  /** @deprecated use `Raise$outboundSchema` instead. */
  export const outboundSchema = Raise$outboundSchema;
  /** @deprecated use `Raise$Outbound` instead. */
  export type Outbound = Raise$Outbound;
}

export function raiseToJSON(raise: Raise): string {
  return JSON.stringify(Raise$outboundSchema.parse(raise));
}

export function raiseFromJSON(
  jsonString: string,
): SafeParseResult<Raise, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Raise$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Raise' from JSON`,
  );
}

/** @internal */
export const Organization$inboundSchema: z.ZodType<
  Organization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  type: Type$inboundSchema.optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  raise: z.nullable(z.lazy(() => Raise$inboundSchema)).optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type Organization$Outbound = {
  id?: number | undefined;
  type?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  raise?: Raise$Outbound | null | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const Organization$outboundSchema: z.ZodType<
  Organization$Outbound,
  z.ZodTypeDef,
  Organization
> = z.object({
  id: z.number().int().optional(),
  type: Type$outboundSchema.optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  raise: z.nullable(z.lazy(() => Raise$outboundSchema)).optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Organization$ {
  /** @deprecated use `Organization$inboundSchema` instead. */
  export const inboundSchema = Organization$inboundSchema;
  /** @deprecated use `Organization$outboundSchema` instead. */
  export const outboundSchema = Organization$outboundSchema;
  /** @deprecated use `Organization$Outbound` instead. */
  export type Outbound = Organization$Outbound;
}

export function organizationToJSON(organization: Organization): string {
  return JSON.stringify(Organization$outboundSchema.parse(organization));
}

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
