/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BaseProposal,
  BaseProposal$inboundSchema,
  BaseProposal$Outbound,
  BaseProposal$outboundSchema,
} from "./baseproposal.js";
import {
  ContactInformation,
  ContactInformation$inboundSchema,
  ContactInformation$Outbound,
  ContactInformation$outboundSchema,
} from "./contactinformation.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";
import {
  OrganizationStatus,
  OrganizationStatus$inboundSchema,
  OrganizationStatus$outboundSchema,
} from "./organizationstatus.js";
import {
  OrganizationType,
  OrganizationType$inboundSchema,
  OrganizationType$outboundSchema,
} from "./organizationtype.js";
import {
  Raise,
  Raise$inboundSchema,
  Raise$Outbound,
  Raise$outboundSchema,
} from "./raise.js";
import {
  Token,
  Token$inboundSchema,
  Token$Outbound,
  Token$outboundSchema,
} from "./token.js";
import {
  Treasury,
  Treasury$inboundSchema,
  Treasury$Outbound,
  Treasury$outboundSchema,
} from "./treasury.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "./user.js";

export type OrganizationDetail = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  type?: OrganizationType | undefined;
  status?: OrganizationStatus | undefined;
  links?: Array<Link> | undefined;
  contactInformation?: Array<ContactInformation> | undefined;
  token?: Token | undefined;
  treasury?: Treasury | undefined;
  user?: User | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
  proposals?: Array<BaseProposal> | undefined;
  raise?: Raise | undefined;
};

/** @internal */
export const OrganizationDetail$inboundSchema: z.ZodType<
  OrganizationDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  type: OrganizationType$inboundSchema.optional(),
  status: OrganizationStatus$inboundSchema.optional(),
  links: z.array(Link$inboundSchema).optional(),
  contactInformation: z.array(ContactInformation$inboundSchema).optional(),
  token: Token$inboundSchema.optional(),
  treasury: Treasury$inboundSchema.optional(),
  user: User$inboundSchema.optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  proposals: z.array(BaseProposal$inboundSchema).optional(),
  raise: Raise$inboundSchema.optional(),
});

/** @internal */
export type OrganizationDetail$Outbound = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  image?: string | undefined;
  banner?: string | undefined;
  description?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  links?: Array<Link$Outbound> | undefined;
  contactInformation?: Array<ContactInformation$Outbound> | undefined;
  token?: Token$Outbound | undefined;
  treasury?: Treasury$Outbound | undefined;
  user?: User$Outbound | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  proposals?: Array<BaseProposal$Outbound> | undefined;
  raise?: Raise$Outbound | undefined;
};

/** @internal */
export const OrganizationDetail$outboundSchema: z.ZodType<
  OrganizationDetail$Outbound,
  z.ZodTypeDef,
  OrganizationDetail
> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  image: z.string().optional(),
  banner: z.string().optional(),
  description: z.string().optional(),
  type: OrganizationType$outboundSchema.optional(),
  status: OrganizationStatus$outboundSchema.optional(),
  links: z.array(Link$outboundSchema).optional(),
  contactInformation: z.array(ContactInformation$outboundSchema).optional(),
  token: Token$outboundSchema.optional(),
  treasury: Treasury$outboundSchema.optional(),
  user: User$outboundSchema.optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
  proposals: z.array(BaseProposal$outboundSchema).optional(),
  raise: Raise$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationDetail$ {
  /** @deprecated use `OrganizationDetail$inboundSchema` instead. */
  export const inboundSchema = OrganizationDetail$inboundSchema;
  /** @deprecated use `OrganizationDetail$outboundSchema` instead. */
  export const outboundSchema = OrganizationDetail$outboundSchema;
  /** @deprecated use `OrganizationDetail$Outbound` instead. */
  export type Outbound = OrganizationDetail$Outbound;
}

export function organizationDetailToJSON(
  organizationDetail: OrganizationDetail,
): string {
  return JSON.stringify(
    OrganizationDetail$outboundSchema.parse(organizationDetail),
  );
}

export function organizationDetailFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDetail' from JSON`,
  );
}
