/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "./pagination.js";
import {
  ProposalStake,
  ProposalStake$inboundSchema,
  ProposalStake$Outbound,
  ProposalStake$outboundSchema,
} from "./proposalstake.js";

/**
 * Success response wrapper
 */
export type PaginatedStakes = {
  success: true;
  data: Array<ProposalStake>;
  /**
   * Pagination parameters for list endpoints. Use page/limit for requests, total is returned in responses.
   */
  pagination: Pagination;
};

/** @internal */
export const PaginatedStakes$inboundSchema: z.ZodType<
  PaginatedStakes,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(ProposalStake$inboundSchema),
  pagination: Pagination$inboundSchema,
});

/** @internal */
export type PaginatedStakes$Outbound = {
  success: true;
  data: Array<ProposalStake$Outbound>;
  pagination: Pagination$Outbound;
};

/** @internal */
export const PaginatedStakes$outboundSchema: z.ZodType<
  PaginatedStakes$Outbound,
  z.ZodTypeDef,
  PaginatedStakes
> = z.object({
  success: z.literal(true),
  data: z.array(ProposalStake$outboundSchema),
  pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaginatedStakes$ {
  /** @deprecated use `PaginatedStakes$inboundSchema` instead. */
  export const inboundSchema = PaginatedStakes$inboundSchema;
  /** @deprecated use `PaginatedStakes$outboundSchema` instead. */
  export const outboundSchema = PaginatedStakes$outboundSchema;
  /** @deprecated use `PaginatedStakes$Outbound` instead. */
  export type Outbound = PaginatedStakes$Outbound;
}

export function paginatedStakesToJSON(
  paginatedStakes: PaginatedStakes,
): string {
  return JSON.stringify(PaginatedStakes$outboundSchema.parse(paginatedStakes));
}

export function paginatedStakesFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedStakes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedStakes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedStakes' from JSON`,
  );
}
