/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditLog,
  AuditLog$inboundSchema,
  AuditLog$Outbound,
  AuditLog$outboundSchema,
} from "./auditlog.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "./pagination.js";

/**
 * Success response wrapper
 */
export type PaginatedAuditLogs = {
  success: true;
  data: Array<AuditLog>;
  /**
   * Pagination parameters for list endpoints. Use page/limit for requests, total is returned in responses.
   */
  pagination: Pagination;
};

/** @internal */
export const PaginatedAuditLogs$inboundSchema: z.ZodType<
  PaginatedAuditLogs,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(AuditLog$inboundSchema),
  pagination: Pagination$inboundSchema,
});

/** @internal */
export type PaginatedAuditLogs$Outbound = {
  success: true;
  data: Array<AuditLog$Outbound>;
  pagination: Pagination$Outbound;
};

/** @internal */
export const PaginatedAuditLogs$outboundSchema: z.ZodType<
  PaginatedAuditLogs$Outbound,
  z.ZodTypeDef,
  PaginatedAuditLogs
> = z.object({
  success: z.literal(true),
  data: z.array(AuditLog$outboundSchema),
  pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaginatedAuditLogs$ {
  /** @deprecated use `PaginatedAuditLogs$inboundSchema` instead. */
  export const inboundSchema = PaginatedAuditLogs$inboundSchema;
  /** @deprecated use `PaginatedAuditLogs$outboundSchema` instead. */
  export const outboundSchema = PaginatedAuditLogs$outboundSchema;
  /** @deprecated use `PaginatedAuditLogs$Outbound` instead. */
  export type Outbound = PaginatedAuditLogs$Outbound;
}

export function paginatedAuditLogsToJSON(
  paginatedAuditLogs: PaginatedAuditLogs,
): string {
  return JSON.stringify(
    PaginatedAuditLogs$outboundSchema.parse(paginatedAuditLogs),
  );
}

export function paginatedAuditLogsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedAuditLogs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedAuditLogs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedAuditLogs' from JSON`,
  );
}
