/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Pagination,
  Pagination$inboundSchema,
  Pagination$Outbound,
  Pagination$outboundSchema,
} from "./pagination.js";
import {
  Proposal,
  Proposal$inboundSchema,
  Proposal$Outbound,
  Proposal$outboundSchema,
} from "./proposal.js";

/**
 * Success response wrapper
 */
export type PaginatedProposals = {
  success: true;
  data: Array<Proposal>;
  /**
   * Pagination parameters for list endpoints. Use page/limit for requests, total is returned in responses.
   */
  pagination: Pagination;
};

/** @internal */
export const PaginatedProposals$inboundSchema: z.ZodType<
  PaginatedProposals,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.array(Proposal$inboundSchema),
  pagination: Pagination$inboundSchema,
});

/** @internal */
export type PaginatedProposals$Outbound = {
  success: true;
  data: Array<Proposal$Outbound>;
  pagination: Pagination$Outbound;
};

/** @internal */
export const PaginatedProposals$outboundSchema: z.ZodType<
  PaginatedProposals$Outbound,
  z.ZodTypeDef,
  PaginatedProposals
> = z.object({
  success: z.literal(true),
  data: z.array(Proposal$outboundSchema),
  pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaginatedProposals$ {
  /** @deprecated use `PaginatedProposals$inboundSchema` instead. */
  export const inboundSchema = PaginatedProposals$inboundSchema;
  /** @deprecated use `PaginatedProposals$outboundSchema` instead. */
  export const outboundSchema = PaginatedProposals$outboundSchema;
  /** @deprecated use `PaginatedProposals$Outbound` instead. */
  export type Outbound = PaginatedProposals$Outbound;
}

export function paginatedProposalsToJSON(
  paginatedProposals: PaginatedProposals,
): string {
  return JSON.stringify(
    PaginatedProposals$outboundSchema.parse(paginatedProposals),
  );
}

export function paginatedProposalsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedProposals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedProposals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedProposals' from JSON`,
  );
}
