/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ProposalOutcome = {
  Pass: "pass",
  Fail: "fail",
} as const;
export type ProposalOutcome = ClosedEnum<typeof ProposalOutcome>;

/** @internal */
export const ProposalOutcome$inboundSchema: z.ZodNativeEnum<
  typeof ProposalOutcome
> = z.nativeEnum(ProposalOutcome);

/** @internal */
export const ProposalOutcome$outboundSchema: z.ZodNativeEnum<
  typeof ProposalOutcome
> = ProposalOutcome$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalOutcome$ {
  /** @deprecated use `ProposalOutcome$inboundSchema` instead. */
  export const inboundSchema = ProposalOutcome$inboundSchema;
  /** @deprecated use `ProposalOutcome$outboundSchema` instead. */
  export const outboundSchema = ProposalOutcome$outboundSchema;
}
