/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ProposalStatus = {
  Draft: "draft",
  Staking: "staking",
  Active: "active",
  Resolved: "resolved",
  Executed: "executed",
  Cancelled: "cancelled",
} as const;
export type ProposalStatus = ClosedEnum<typeof ProposalStatus>;

/** @internal */
export const ProposalStatus$inboundSchema: z.ZodNativeEnum<
  typeof ProposalStatus
> = z.nativeEnum(ProposalStatus);

/** @internal */
export const ProposalStatus$outboundSchema: z.ZodNativeEnum<
  typeof ProposalStatus
> = ProposalStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalStatus$ {
  /** @deprecated use `ProposalStatus$inboundSchema` instead. */
  export const inboundSchema = ProposalStatus$inboundSchema;
  /** @deprecated use `ProposalStatus$outboundSchema` instead. */
  export const outboundSchema = ProposalStatus$outboundSchema;
}
