/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateMetadataAction = {
  actionType: "update_metadata";
  /**
   * Valid IPFS CID or URL
   */
  uri: string;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

export const Action = {
  Add: "add",
  Remove: "remove",
} as const;
export type Action = ClosedEnum<typeof Action>;

export type AdjustLpAction = {
  actionType: "adjust_lp";
  action: Action;
  /**
   * At least one of tokenAmount or usdcAmount required
   */
  tokenAmount?: number | undefined;
  /**
   * At least one of tokenAmount or usdcAmount required
   */
  usdcAmount?: number | undefined;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

export type BurnTokensAction = {
  actionType: "burn_tokens";
  amount: number;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

export type MintTokensAction = {
  actionType: "mint_tokens";
  amount: number;
  /**
   * Optional, defaults to treasury
   */
  recipientAddress?: string | undefined;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

export type TreasurySpendAction = {
  actionType: "treasury_spend";
  /**
   * Valid wallet address
   */
  recipientAddress: string;
  amount: number;
  /**
   * Token address or 'USDC'
   */
  token: string;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: Date | undefined;
  updated?: Date | undefined;
};

export type ProposalAction =
  | (TreasurySpendAction & { actionType: "treasury_spend" })
  | (MintTokensAction & { actionType: "mint_tokens" })
  | (BurnTokensAction & { actionType: "burn_tokens" })
  | (AdjustLpAction & { actionType: "adjust_lp" })
  | (UpdateMetadataAction & { actionType: "update_metadata" });

export type ProposalActionUpdateMetadataAction = {
  actionType: "update_metadata";
  /**
   * Valid IPFS CID or URL
   */
  uri: string;
  order?: number | undefined;
};

export type ProposalActionAdjustLpAction = {
  actionType: "adjust_lp";
  action: Action;
  /**
   * At least one of tokenAmount or usdcAmount required
   */
  tokenAmount?: number | undefined;
  /**
   * At least one of tokenAmount or usdcAmount required
   */
  usdcAmount?: number | undefined;
  order?: number | undefined;
};

export type ProposalActionBurnTokensAction = {
  actionType: "burn_tokens";
  amount: number;
  order?: number | undefined;
};

export type ProposalActionMintTokensAction = {
  actionType: "mint_tokens";
  amount: number;
  /**
   * Optional, defaults to treasury
   */
  recipientAddress?: string | undefined;
  order?: number | undefined;
};

export type ProposalActionTreasurySpendAction = {
  actionType: "treasury_spend";
  /**
   * Valid wallet address
   */
  recipientAddress: string;
  amount: number;
  /**
   * Token address or 'USDC'
   */
  token: string;
  order?: number | undefined;
};

export type ProposalActionRequest =
  | (ProposalActionTreasurySpendAction & { actionType: "treasury_spend" })
  | (ProposalActionMintTokensAction & { actionType: "mint_tokens" })
  | (ProposalActionBurnTokensAction & { actionType: "burn_tokens" })
  | (ProposalActionAdjustLpAction & { actionType: "adjust_lp" })
  | (ProposalActionUpdateMetadataAction & { actionType: "update_metadata" });

/** @internal */
export const UpdateMetadataAction$inboundSchema: z.ZodType<
  UpdateMetadataAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("update_metadata"),
  uri: z.string(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type UpdateMetadataAction$Outbound = {
  actionType: "update_metadata";
  uri: string;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const UpdateMetadataAction$outboundSchema: z.ZodType<
  UpdateMetadataAction$Outbound,
  z.ZodTypeDef,
  UpdateMetadataAction
> = z.object({
  actionType: z.literal("update_metadata"),
  uri: z.string(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMetadataAction$ {
  /** @deprecated use `UpdateMetadataAction$inboundSchema` instead. */
  export const inboundSchema = UpdateMetadataAction$inboundSchema;
  /** @deprecated use `UpdateMetadataAction$outboundSchema` instead. */
  export const outboundSchema = UpdateMetadataAction$outboundSchema;
  /** @deprecated use `UpdateMetadataAction$Outbound` instead. */
  export type Outbound = UpdateMetadataAction$Outbound;
}

export function updateMetadataActionToJSON(
  updateMetadataAction: UpdateMetadataAction,
): string {
  return JSON.stringify(
    UpdateMetadataAction$outboundSchema.parse(updateMetadataAction),
  );
}

export function updateMetadataActionFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMetadataAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMetadataAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMetadataAction' from JSON`,
  );
}

/** @internal */
export const Action$inboundSchema: z.ZodNativeEnum<typeof Action> = z
  .nativeEnum(Action);

/** @internal */
export const Action$outboundSchema: z.ZodNativeEnum<typeof Action> =
  Action$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Action$ {
  /** @deprecated use `Action$inboundSchema` instead. */
  export const inboundSchema = Action$inboundSchema;
  /** @deprecated use `Action$outboundSchema` instead. */
  export const outboundSchema = Action$outboundSchema;
}

/** @internal */
export const AdjustLpAction$inboundSchema: z.ZodType<
  AdjustLpAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("adjust_lp"),
  action: Action$inboundSchema,
  tokenAmount: z.number().optional(),
  usdcAmount: z.number().optional(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type AdjustLpAction$Outbound = {
  actionType: "adjust_lp";
  action: string;
  tokenAmount?: number | undefined;
  usdcAmount?: number | undefined;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const AdjustLpAction$outboundSchema: z.ZodType<
  AdjustLpAction$Outbound,
  z.ZodTypeDef,
  AdjustLpAction
> = z.object({
  actionType: z.literal("adjust_lp"),
  action: Action$outboundSchema,
  tokenAmount: z.number().optional(),
  usdcAmount: z.number().optional(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdjustLpAction$ {
  /** @deprecated use `AdjustLpAction$inboundSchema` instead. */
  export const inboundSchema = AdjustLpAction$inboundSchema;
  /** @deprecated use `AdjustLpAction$outboundSchema` instead. */
  export const outboundSchema = AdjustLpAction$outboundSchema;
  /** @deprecated use `AdjustLpAction$Outbound` instead. */
  export type Outbound = AdjustLpAction$Outbound;
}

export function adjustLpActionToJSON(adjustLpAction: AdjustLpAction): string {
  return JSON.stringify(AdjustLpAction$outboundSchema.parse(adjustLpAction));
}

export function adjustLpActionFromJSON(
  jsonString: string,
): SafeParseResult<AdjustLpAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdjustLpAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdjustLpAction' from JSON`,
  );
}

/** @internal */
export const BurnTokensAction$inboundSchema: z.ZodType<
  BurnTokensAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("burn_tokens"),
  amount: z.number(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type BurnTokensAction$Outbound = {
  actionType: "burn_tokens";
  amount: number;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const BurnTokensAction$outboundSchema: z.ZodType<
  BurnTokensAction$Outbound,
  z.ZodTypeDef,
  BurnTokensAction
> = z.object({
  actionType: z.literal("burn_tokens"),
  amount: z.number(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BurnTokensAction$ {
  /** @deprecated use `BurnTokensAction$inboundSchema` instead. */
  export const inboundSchema = BurnTokensAction$inboundSchema;
  /** @deprecated use `BurnTokensAction$outboundSchema` instead. */
  export const outboundSchema = BurnTokensAction$outboundSchema;
  /** @deprecated use `BurnTokensAction$Outbound` instead. */
  export type Outbound = BurnTokensAction$Outbound;
}

export function burnTokensActionToJSON(
  burnTokensAction: BurnTokensAction,
): string {
  return JSON.stringify(
    BurnTokensAction$outboundSchema.parse(burnTokensAction),
  );
}

export function burnTokensActionFromJSON(
  jsonString: string,
): SafeParseResult<BurnTokensAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BurnTokensAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BurnTokensAction' from JSON`,
  );
}

/** @internal */
export const MintTokensAction$inboundSchema: z.ZodType<
  MintTokensAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("mint_tokens"),
  amount: z.number(),
  recipientAddress: z.string().optional(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type MintTokensAction$Outbound = {
  actionType: "mint_tokens";
  amount: number;
  recipientAddress?: string | undefined;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const MintTokensAction$outboundSchema: z.ZodType<
  MintTokensAction$Outbound,
  z.ZodTypeDef,
  MintTokensAction
> = z.object({
  actionType: z.literal("mint_tokens"),
  amount: z.number(),
  recipientAddress: z.string().optional(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MintTokensAction$ {
  /** @deprecated use `MintTokensAction$inboundSchema` instead. */
  export const inboundSchema = MintTokensAction$inboundSchema;
  /** @deprecated use `MintTokensAction$outboundSchema` instead. */
  export const outboundSchema = MintTokensAction$outboundSchema;
  /** @deprecated use `MintTokensAction$Outbound` instead. */
  export type Outbound = MintTokensAction$Outbound;
}

export function mintTokensActionToJSON(
  mintTokensAction: MintTokensAction,
): string {
  return JSON.stringify(
    MintTokensAction$outboundSchema.parse(mintTokensAction),
  );
}

export function mintTokensActionFromJSON(
  jsonString: string,
): SafeParseResult<MintTokensAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MintTokensAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MintTokensAction' from JSON`,
  );
}

/** @internal */
export const TreasurySpendAction$inboundSchema: z.ZodType<
  TreasurySpendAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("treasury_spend"),
  recipientAddress: z.string(),
  amount: z.number(),
  token: z.string(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type TreasurySpendAction$Outbound = {
  actionType: "treasury_spend";
  recipientAddress: string;
  amount: number;
  token: string;
  id?: number | undefined;
  proposalId?: number | undefined;
  order?: number | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const TreasurySpendAction$outboundSchema: z.ZodType<
  TreasurySpendAction$Outbound,
  z.ZodTypeDef,
  TreasurySpendAction
> = z.object({
  actionType: z.literal("treasury_spend"),
  recipientAddress: z.string(),
  amount: z.number(),
  token: z.string(),
  id: z.number().int().optional(),
  proposalId: z.number().int().optional(),
  order: z.number().int().optional(),
  created: z.date().transform(v => v.toISOString()).optional(),
  updated: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TreasurySpendAction$ {
  /** @deprecated use `TreasurySpendAction$inboundSchema` instead. */
  export const inboundSchema = TreasurySpendAction$inboundSchema;
  /** @deprecated use `TreasurySpendAction$outboundSchema` instead. */
  export const outboundSchema = TreasurySpendAction$outboundSchema;
  /** @deprecated use `TreasurySpendAction$Outbound` instead. */
  export type Outbound = TreasurySpendAction$Outbound;
}

export function treasurySpendActionToJSON(
  treasurySpendAction: TreasurySpendAction,
): string {
  return JSON.stringify(
    TreasurySpendAction$outboundSchema.parse(treasurySpendAction),
  );
}

export function treasurySpendActionFromJSON(
  jsonString: string,
): SafeParseResult<TreasurySpendAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TreasurySpendAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TreasurySpendAction' from JSON`,
  );
}

/** @internal */
export const ProposalAction$inboundSchema: z.ZodType<
  ProposalAction,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => TreasurySpendAction$inboundSchema).and(
    z.object({ actionType: z.literal("treasury_spend") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => MintTokensAction$inboundSchema).and(
    z.object({ actionType: z.literal("mint_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => BurnTokensAction$inboundSchema).and(
    z.object({ actionType: z.literal("burn_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => AdjustLpAction$inboundSchema).and(
    z.object({ actionType: z.literal("adjust_lp") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => UpdateMetadataAction$inboundSchema).and(
    z.object({ actionType: z.literal("update_metadata") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
]);

/** @internal */
export type ProposalAction$Outbound =
  | (TreasurySpendAction$Outbound & { actionType: "treasury_spend" })
  | (MintTokensAction$Outbound & { actionType: "mint_tokens" })
  | (BurnTokensAction$Outbound & { actionType: "burn_tokens" })
  | (AdjustLpAction$Outbound & { actionType: "adjust_lp" })
  | (UpdateMetadataAction$Outbound & { actionType: "update_metadata" });

/** @internal */
export const ProposalAction$outboundSchema: z.ZodType<
  ProposalAction$Outbound,
  z.ZodTypeDef,
  ProposalAction
> = z.union([
  z.lazy(() => TreasurySpendAction$outboundSchema).and(
    z.object({ actionType: z.literal("treasury_spend") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => MintTokensAction$outboundSchema).and(
    z.object({ actionType: z.literal("mint_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => BurnTokensAction$outboundSchema).and(
    z.object({ actionType: z.literal("burn_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => AdjustLpAction$outboundSchema).and(
    z.object({ actionType: z.literal("adjust_lp") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => UpdateMetadataAction$outboundSchema).and(
    z.object({ actionType: z.literal("update_metadata") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalAction$ {
  /** @deprecated use `ProposalAction$inboundSchema` instead. */
  export const inboundSchema = ProposalAction$inboundSchema;
  /** @deprecated use `ProposalAction$outboundSchema` instead. */
  export const outboundSchema = ProposalAction$outboundSchema;
  /** @deprecated use `ProposalAction$Outbound` instead. */
  export type Outbound = ProposalAction$Outbound;
}

export function proposalActionToJSON(proposalAction: ProposalAction): string {
  return JSON.stringify(ProposalAction$outboundSchema.parse(proposalAction));
}

export function proposalActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionUpdateMetadataAction$inboundSchema: z.ZodType<
  ProposalActionUpdateMetadataAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("update_metadata"),
  uri: z.string(),
  order: z.number().int().optional(),
});

/** @internal */
export type ProposalActionUpdateMetadataAction$Outbound = {
  actionType: "update_metadata";
  uri: string;
  order?: number | undefined;
};

/** @internal */
export const ProposalActionUpdateMetadataAction$outboundSchema: z.ZodType<
  ProposalActionUpdateMetadataAction$Outbound,
  z.ZodTypeDef,
  ProposalActionUpdateMetadataAction
> = z.object({
  actionType: z.literal("update_metadata"),
  uri: z.string(),
  order: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionUpdateMetadataAction$ {
  /** @deprecated use `ProposalActionUpdateMetadataAction$inboundSchema` instead. */
  export const inboundSchema = ProposalActionUpdateMetadataAction$inboundSchema;
  /** @deprecated use `ProposalActionUpdateMetadataAction$outboundSchema` instead. */
  export const outboundSchema =
    ProposalActionUpdateMetadataAction$outboundSchema;
  /** @deprecated use `ProposalActionUpdateMetadataAction$Outbound` instead. */
  export type Outbound = ProposalActionUpdateMetadataAction$Outbound;
}

export function proposalActionUpdateMetadataActionToJSON(
  proposalActionUpdateMetadataAction: ProposalActionUpdateMetadataAction,
): string {
  return JSON.stringify(
    ProposalActionUpdateMetadataAction$outboundSchema.parse(
      proposalActionUpdateMetadataAction,
    ),
  );
}

export function proposalActionUpdateMetadataActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionUpdateMetadataAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ProposalActionUpdateMetadataAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionUpdateMetadataAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionAdjustLpAction$inboundSchema: z.ZodType<
  ProposalActionAdjustLpAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("adjust_lp"),
  action: Action$inboundSchema,
  tokenAmount: z.number().optional(),
  usdcAmount: z.number().optional(),
  order: z.number().int().optional(),
});

/** @internal */
export type ProposalActionAdjustLpAction$Outbound = {
  actionType: "adjust_lp";
  action: string;
  tokenAmount?: number | undefined;
  usdcAmount?: number | undefined;
  order?: number | undefined;
};

/** @internal */
export const ProposalActionAdjustLpAction$outboundSchema: z.ZodType<
  ProposalActionAdjustLpAction$Outbound,
  z.ZodTypeDef,
  ProposalActionAdjustLpAction
> = z.object({
  actionType: z.literal("adjust_lp"),
  action: Action$outboundSchema,
  tokenAmount: z.number().optional(),
  usdcAmount: z.number().optional(),
  order: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionAdjustLpAction$ {
  /** @deprecated use `ProposalActionAdjustLpAction$inboundSchema` instead. */
  export const inboundSchema = ProposalActionAdjustLpAction$inboundSchema;
  /** @deprecated use `ProposalActionAdjustLpAction$outboundSchema` instead. */
  export const outboundSchema = ProposalActionAdjustLpAction$outboundSchema;
  /** @deprecated use `ProposalActionAdjustLpAction$Outbound` instead. */
  export type Outbound = ProposalActionAdjustLpAction$Outbound;
}

export function proposalActionAdjustLpActionToJSON(
  proposalActionAdjustLpAction: ProposalActionAdjustLpAction,
): string {
  return JSON.stringify(
    ProposalActionAdjustLpAction$outboundSchema.parse(
      proposalActionAdjustLpAction,
    ),
  );
}

export function proposalActionAdjustLpActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionAdjustLpAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalActionAdjustLpAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionAdjustLpAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionBurnTokensAction$inboundSchema: z.ZodType<
  ProposalActionBurnTokensAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("burn_tokens"),
  amount: z.number(),
  order: z.number().int().optional(),
});

/** @internal */
export type ProposalActionBurnTokensAction$Outbound = {
  actionType: "burn_tokens";
  amount: number;
  order?: number | undefined;
};

/** @internal */
export const ProposalActionBurnTokensAction$outboundSchema: z.ZodType<
  ProposalActionBurnTokensAction$Outbound,
  z.ZodTypeDef,
  ProposalActionBurnTokensAction
> = z.object({
  actionType: z.literal("burn_tokens"),
  amount: z.number(),
  order: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionBurnTokensAction$ {
  /** @deprecated use `ProposalActionBurnTokensAction$inboundSchema` instead. */
  export const inboundSchema = ProposalActionBurnTokensAction$inboundSchema;
  /** @deprecated use `ProposalActionBurnTokensAction$outboundSchema` instead. */
  export const outboundSchema = ProposalActionBurnTokensAction$outboundSchema;
  /** @deprecated use `ProposalActionBurnTokensAction$Outbound` instead. */
  export type Outbound = ProposalActionBurnTokensAction$Outbound;
}

export function proposalActionBurnTokensActionToJSON(
  proposalActionBurnTokensAction: ProposalActionBurnTokensAction,
): string {
  return JSON.stringify(
    ProposalActionBurnTokensAction$outboundSchema.parse(
      proposalActionBurnTokensAction,
    ),
  );
}

export function proposalActionBurnTokensActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionBurnTokensAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalActionBurnTokensAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionBurnTokensAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionMintTokensAction$inboundSchema: z.ZodType<
  ProposalActionMintTokensAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("mint_tokens"),
  amount: z.number(),
  recipientAddress: z.string().optional(),
  order: z.number().int().optional(),
});

/** @internal */
export type ProposalActionMintTokensAction$Outbound = {
  actionType: "mint_tokens";
  amount: number;
  recipientAddress?: string | undefined;
  order?: number | undefined;
};

/** @internal */
export const ProposalActionMintTokensAction$outboundSchema: z.ZodType<
  ProposalActionMintTokensAction$Outbound,
  z.ZodTypeDef,
  ProposalActionMintTokensAction
> = z.object({
  actionType: z.literal("mint_tokens"),
  amount: z.number(),
  recipientAddress: z.string().optional(),
  order: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionMintTokensAction$ {
  /** @deprecated use `ProposalActionMintTokensAction$inboundSchema` instead. */
  export const inboundSchema = ProposalActionMintTokensAction$inboundSchema;
  /** @deprecated use `ProposalActionMintTokensAction$outboundSchema` instead. */
  export const outboundSchema = ProposalActionMintTokensAction$outboundSchema;
  /** @deprecated use `ProposalActionMintTokensAction$Outbound` instead. */
  export type Outbound = ProposalActionMintTokensAction$Outbound;
}

export function proposalActionMintTokensActionToJSON(
  proposalActionMintTokensAction: ProposalActionMintTokensAction,
): string {
  return JSON.stringify(
    ProposalActionMintTokensAction$outboundSchema.parse(
      proposalActionMintTokensAction,
    ),
  );
}

export function proposalActionMintTokensActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionMintTokensAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalActionMintTokensAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionMintTokensAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionTreasurySpendAction$inboundSchema: z.ZodType<
  ProposalActionTreasurySpendAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionType: z.literal("treasury_spend"),
  recipientAddress: z.string(),
  amount: z.number(),
  token: z.string(),
  order: z.number().int().optional(),
});

/** @internal */
export type ProposalActionTreasurySpendAction$Outbound = {
  actionType: "treasury_spend";
  recipientAddress: string;
  amount: number;
  token: string;
  order?: number | undefined;
};

/** @internal */
export const ProposalActionTreasurySpendAction$outboundSchema: z.ZodType<
  ProposalActionTreasurySpendAction$Outbound,
  z.ZodTypeDef,
  ProposalActionTreasurySpendAction
> = z.object({
  actionType: z.literal("treasury_spend"),
  recipientAddress: z.string(),
  amount: z.number(),
  token: z.string(),
  order: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionTreasurySpendAction$ {
  /** @deprecated use `ProposalActionTreasurySpendAction$inboundSchema` instead. */
  export const inboundSchema = ProposalActionTreasurySpendAction$inboundSchema;
  /** @deprecated use `ProposalActionTreasurySpendAction$outboundSchema` instead. */
  export const outboundSchema =
    ProposalActionTreasurySpendAction$outboundSchema;
  /** @deprecated use `ProposalActionTreasurySpendAction$Outbound` instead. */
  export type Outbound = ProposalActionTreasurySpendAction$Outbound;
}

export function proposalActionTreasurySpendActionToJSON(
  proposalActionTreasurySpendAction: ProposalActionTreasurySpendAction,
): string {
  return JSON.stringify(
    ProposalActionTreasurySpendAction$outboundSchema.parse(
      proposalActionTreasurySpendAction,
    ),
  );
}

export function proposalActionTreasurySpendActionFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionTreasurySpendAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalActionTreasurySpendAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionTreasurySpendAction' from JSON`,
  );
}

/** @internal */
export const ProposalActionRequest$inboundSchema: z.ZodType<
  ProposalActionRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ProposalActionTreasurySpendAction$inboundSchema).and(
    z.object({ actionType: z.literal("treasury_spend") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionMintTokensAction$inboundSchema).and(
    z.object({ actionType: z.literal("mint_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionBurnTokensAction$inboundSchema).and(
    z.object({ actionType: z.literal("burn_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionAdjustLpAction$inboundSchema).and(
    z.object({ actionType: z.literal("adjust_lp") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionUpdateMetadataAction$inboundSchema).and(
    z.object({ actionType: z.literal("update_metadata") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
]);

/** @internal */
export type ProposalActionRequest$Outbound =
  | (ProposalActionTreasurySpendAction$Outbound & {
    actionType: "treasury_spend";
  })
  | (ProposalActionMintTokensAction$Outbound & { actionType: "mint_tokens" })
  | (ProposalActionBurnTokensAction$Outbound & { actionType: "burn_tokens" })
  | (ProposalActionAdjustLpAction$Outbound & { actionType: "adjust_lp" })
  | (ProposalActionUpdateMetadataAction$Outbound & {
    actionType: "update_metadata";
  });

/** @internal */
export const ProposalActionRequest$outboundSchema: z.ZodType<
  ProposalActionRequest$Outbound,
  z.ZodTypeDef,
  ProposalActionRequest
> = z.union([
  z.lazy(() => ProposalActionTreasurySpendAction$outboundSchema).and(
    z.object({ actionType: z.literal("treasury_spend") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionMintTokensAction$outboundSchema).and(
    z.object({ actionType: z.literal("mint_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionBurnTokensAction$outboundSchema).and(
    z.object({ actionType: z.literal("burn_tokens") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionAdjustLpAction$outboundSchema).and(
    z.object({ actionType: z.literal("adjust_lp") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
  z.lazy(() => ProposalActionUpdateMetadataAction$outboundSchema).and(
    z.object({ actionType: z.literal("update_metadata") }).transform((v) => ({
      actionType: v.actionType,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProposalActionRequest$ {
  /** @deprecated use `ProposalActionRequest$inboundSchema` instead. */
  export const inboundSchema = ProposalActionRequest$inboundSchema;
  /** @deprecated use `ProposalActionRequest$outboundSchema` instead. */
  export const outboundSchema = ProposalActionRequest$outboundSchema;
  /** @deprecated use `ProposalActionRequest$Outbound` instead. */
  export type Outbound = ProposalActionRequest$Outbound;
}

export function proposalActionRequestToJSON(
  proposalActionRequest: ProposalActionRequest,
): string {
  return JSON.stringify(
    ProposalActionRequest$outboundSchema.parse(proposalActionRequest),
  );
}

export function proposalActionRequestFromJSON(
  jsonString: string,
): SafeParseResult<ProposalActionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalActionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalActionRequest' from JSON`,
  );
}
