/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DecisionMarket,
  DecisionMarket$inboundSchema,
  DecisionMarket$Outbound,
  DecisionMarket$outboundSchema,
} from "./decisionmarket.js";
import {
  ProposalAction,
  ProposalAction$inboundSchema,
  ProposalAction$Outbound,
  ProposalAction$outboundSchema,
} from "./proposalaction.js";
import {
  ProposalStatus,
  ProposalStatus$inboundSchema,
  ProposalStatus$outboundSchema,
} from "./proposalstatus.js";

export const Outcome = {
  Pass: "pass",
  Fail: "fail",
} as const;
export type Outcome = ClosedEnum<typeof Outcome>;

export type Proposal = {
  id: number;
  organizationId: number;
  userId: number;
  title: string;
  description: string;
  status: ProposalStatus;
  outcome?: Outcome | undefined;
  lpAllocation?: number | undefined;
  tokensForLp?: number | undefined;
  usdcForLp?: number | undefined;
  stakingThreshold?: number | undefined;
  passThresholdBps?: number | undefined;
  totalStaked?: number | undefined;
  tradingStartsAt?: Date | undefined;
  tradingEndsAt?: Date | undefined;
  resolvedAt?: Date | undefined;
  executedAt?: Date | undefined;
  actions?: Array<ProposalAction> | undefined;
  decisionMarkets?: Array<DecisionMarket> | undefined;
  created: Date;
  updated: Date;
};

/** @internal */
export const Outcome$inboundSchema: z.ZodNativeEnum<typeof Outcome> = z
  .nativeEnum(Outcome);

/** @internal */
export const Outcome$outboundSchema: z.ZodNativeEnum<typeof Outcome> =
  Outcome$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Outcome$ {
  /** @deprecated use `Outcome$inboundSchema` instead. */
  export const inboundSchema = Outcome$inboundSchema;
  /** @deprecated use `Outcome$outboundSchema` instead. */
  export const outboundSchema = Outcome$outboundSchema;
}

/** @internal */
export const Proposal$inboundSchema: z.ZodType<
  Proposal,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  organizationId: z.number().int(),
  userId: z.number().int(),
  title: z.string(),
  description: z.string(),
  status: ProposalStatus$inboundSchema,
  outcome: Outcome$inboundSchema.optional(),
  lpAllocation: z.number().int().optional(),
  tokensForLp: z.number().optional(),
  usdcForLp: z.number().optional(),
  stakingThreshold: z.number().optional(),
  passThresholdBps: z.number().int().optional(),
  totalStaked: z.number().optional(),
  tradingStartsAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  tradingEndsAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  resolvedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  executedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  actions: z.array(ProposalAction$inboundSchema).optional(),
  decisionMarkets: z.array(DecisionMarket$inboundSchema).optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

/** @internal */
export type Proposal$Outbound = {
  id: number;
  organizationId: number;
  userId: number;
  title: string;
  description: string;
  status: string;
  outcome?: string | undefined;
  lpAllocation?: number | undefined;
  tokensForLp?: number | undefined;
  usdcForLp?: number | undefined;
  stakingThreshold?: number | undefined;
  passThresholdBps?: number | undefined;
  totalStaked?: number | undefined;
  tradingStartsAt?: string | undefined;
  tradingEndsAt?: string | undefined;
  resolvedAt?: string | undefined;
  executedAt?: string | undefined;
  actions?: Array<ProposalAction$Outbound> | undefined;
  decisionMarkets?: Array<DecisionMarket$Outbound> | undefined;
  created: string;
  updated: string;
};

/** @internal */
export const Proposal$outboundSchema: z.ZodType<
  Proposal$Outbound,
  z.ZodTypeDef,
  Proposal
> = z.object({
  id: z.number().int(),
  organizationId: z.number().int(),
  userId: z.number().int(),
  title: z.string(),
  description: z.string(),
  status: ProposalStatus$outboundSchema,
  outcome: Outcome$outboundSchema.optional(),
  lpAllocation: z.number().int().optional(),
  tokensForLp: z.number().optional(),
  usdcForLp: z.number().optional(),
  stakingThreshold: z.number().optional(),
  passThresholdBps: z.number().int().optional(),
  totalStaked: z.number().optional(),
  tradingStartsAt: z.date().transform(v => v.toISOString()).optional(),
  tradingEndsAt: z.date().transform(v => v.toISOString()).optional(),
  resolvedAt: z.date().transform(v => v.toISOString()).optional(),
  executedAt: z.date().transform(v => v.toISOString()).optional(),
  actions: z.array(ProposalAction$outboundSchema).optional(),
  decisionMarkets: z.array(DecisionMarket$outboundSchema).optional(),
  created: z.date().transform(v => v.toISOString()),
  updated: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Proposal$ {
  /** @deprecated use `Proposal$inboundSchema` instead. */
  export const inboundSchema = Proposal$inboundSchema;
  /** @deprecated use `Proposal$outboundSchema` instead. */
  export const outboundSchema = Proposal$outboundSchema;
  /** @deprecated use `Proposal$Outbound` instead. */
  export type Outbound = Proposal$Outbound;
}

export function proposalToJSON(proposal: Proposal): string {
  return JSON.stringify(Proposal$outboundSchema.parse(proposal));
}

export function proposalFromJSON(
  jsonString: string,
): SafeParseResult<Proposal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Proposal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Proposal' from JSON`,
  );
}
