/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RaiseStatus,
  RaiseStatus$inboundSchema,
  RaiseStatus$outboundSchema,
} from "./raisestatus.js";

export type Raise = {
  id?: number | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  status?: RaiseStatus | undefined;
};

/** @internal */
export const Raise$inboundSchema: z.ZodType<Raise, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    softCap: z.number().optional(),
    acceptedAmount: z.number().optional(),
    balance: z.number().optional(),
    startDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    endDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    status: RaiseStatus$inboundSchema.optional(),
  });

/** @internal */
export type Raise$Outbound = {
  id?: number | undefined;
  softCap?: number | undefined;
  acceptedAmount?: number | undefined;
  balance?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const Raise$outboundSchema: z.ZodType<
  Raise$Outbound,
  z.ZodTypeDef,
  Raise
> = z.object({
  id: z.number().int().optional(),
  softCap: z.number().optional(),
  acceptedAmount: z.number().optional(),
  balance: z.number().optional(),
  startDate: z.date().transform(v => v.toISOString()).optional(),
  endDate: z.date().transform(v => v.toISOString()).optional(),
  status: RaiseStatus$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Raise$ {
  /** @deprecated use `Raise$inboundSchema` instead. */
  export const inboundSchema = Raise$inboundSchema;
  /** @deprecated use `Raise$outboundSchema` instead. */
  export const outboundSchema = Raise$outboundSchema;
  /** @deprecated use `Raise$Outbound` instead. */
  export type Outbound = Raise$Outbound;
}

export function raiseToJSON(raise: Raise): string {
  return JSON.stringify(Raise$outboundSchema.parse(raise));
}

export function raiseFromJSON(
  jsonString: string,
): SafeParseResult<Raise, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Raise$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Raise' from JSON`,
  );
}
