/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const RaiseStatus = {
  Pending: "pending",
  Active: "active",
  Finalizing: "finalizing",
  Completed: "completed",
  Failed: "failed",
} as const;
export type RaiseStatus = ClosedEnum<typeof RaiseStatus>;

/** @internal */
export const RaiseStatus$inboundSchema: z.ZodNativeEnum<typeof RaiseStatus> = z
  .nativeEnum(RaiseStatus);

/** @internal */
export const RaiseStatus$outboundSchema: z.ZodNativeEnum<typeof RaiseStatus> =
  RaiseStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RaiseStatus$ {
  /** @deprecated use `RaiseStatus$inboundSchema` instead. */
  export const inboundSchema = RaiseStatus$inboundSchema;
  /** @deprecated use `RaiseStatus$outboundSchema` instead. */
  export const outboundSchema = RaiseStatus$outboundSchema;
}
