/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RaiseContribution = {
  id: number;
  raiseId: number;
  address: string;
  amountInvested: number;
  created: Date;
  updated: Date;
};

/** @internal */
export const RaiseContribution$inboundSchema: z.ZodType<
  RaiseContribution,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  raiseId: z.number().int(),
  address: z.string(),
  amountInvested: z.number(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

/** @internal */
export type RaiseContribution$Outbound = {
  id: number;
  raiseId: number;
  address: string;
  amountInvested: number;
  created: string;
  updated: string;
};

/** @internal */
export const RaiseContribution$outboundSchema: z.ZodType<
  RaiseContribution$Outbound,
  z.ZodTypeDef,
  RaiseContribution
> = z.object({
  id: z.number().int(),
  raiseId: z.number().int(),
  address: z.string(),
  amountInvested: z.number(),
  created: z.date().transform(v => v.toISOString()),
  updated: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RaiseContribution$ {
  /** @deprecated use `RaiseContribution$inboundSchema` instead. */
  export const inboundSchema = RaiseContribution$inboundSchema;
  /** @deprecated use `RaiseContribution$outboundSchema` instead. */
  export const outboundSchema = RaiseContribution$outboundSchema;
  /** @deprecated use `RaiseContribution$Outbound` instead. */
  export type Outbound = RaiseContribution$Outbound;
}

export function raiseContributionToJSON(
  raiseContribution: RaiseContribution,
): string {
  return JSON.stringify(
    RaiseContribution$outboundSchema.parse(raiseContribution),
  );
}

export function raiseContributionFromJSON(
  jsonString: string,
): SafeParseResult<RaiseContribution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RaiseContribution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RaiseContribution' from JSON`,
  );
}
