/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TargetType = {
  User: "user",
  Organization: "organization",
  Proposal: "proposal",
  Raise: "raise",
} as const;
export type TargetType = ClosedEnum<typeof TargetType>;

/** @internal */
export const TargetType$inboundSchema: z.ZodNativeEnum<typeof TargetType> = z
  .nativeEnum(TargetType);

/** @internal */
export const TargetType$outboundSchema: z.ZodNativeEnum<typeof TargetType> =
  TargetType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TargetType$ {
  /** @deprecated use `TargetType$inboundSchema` instead. */
  export const inboundSchema = TargetType$inboundSchema;
  /** @deprecated use `TargetType$outboundSchema` instead. */
  export const outboundSchema = TargetType$outboundSchema;
}
