/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TokenResponseData = {
  /**
   * JWT access token
   */
  token: string;
};

/**
 * Success response wrapper
 */
export type TokenResponse = {
  success: true;
  data: TokenResponseData;
};

/** @internal */
export const TokenResponseData$inboundSchema: z.ZodType<
  TokenResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
});

/** @internal */
export type TokenResponseData$Outbound = {
  token: string;
};

/** @internal */
export const TokenResponseData$outboundSchema: z.ZodType<
  TokenResponseData$Outbound,
  z.ZodTypeDef,
  TokenResponseData
> = z.object({
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TokenResponseData$ {
  /** @deprecated use `TokenResponseData$inboundSchema` instead. */
  export const inboundSchema = TokenResponseData$inboundSchema;
  /** @deprecated use `TokenResponseData$outboundSchema` instead. */
  export const outboundSchema = TokenResponseData$outboundSchema;
  /** @deprecated use `TokenResponseData$Outbound` instead. */
  export type Outbound = TokenResponseData$Outbound;
}

export function tokenResponseDataToJSON(
  tokenResponseData: TokenResponseData,
): string {
  return JSON.stringify(
    TokenResponseData$outboundSchema.parse(tokenResponseData),
  );
}

export function tokenResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<TokenResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenResponseData' from JSON`,
  );
}

/** @internal */
export const TokenResponse$inboundSchema: z.ZodType<
  TokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => TokenResponseData$inboundSchema),
});

/** @internal */
export type TokenResponse$Outbound = {
  success: true;
  data: TokenResponseData$Outbound;
};

/** @internal */
export const TokenResponse$outboundSchema: z.ZodType<
  TokenResponse$Outbound,
  z.ZodTypeDef,
  TokenResponse
> = z.object({
  success: z.literal(true),
  data: z.lazy(() => TokenResponseData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TokenResponse$ {
  /** @deprecated use `TokenResponse$inboundSchema` instead. */
  export const inboundSchema = TokenResponse$inboundSchema;
  /** @deprecated use `TokenResponse$outboundSchema` instead. */
  export const outboundSchema = TokenResponse$outboundSchema;
  /** @deprecated use `TokenResponse$Outbound` instead. */
  export type Outbound = TokenResponse$Outbound;
}

export function tokenResponseToJSON(tokenResponse: TokenResponse): string {
  return JSON.stringify(TokenResponse$outboundSchema.parse(tokenResponse));
}

export function tokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<TokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenResponse' from JSON`,
  );
}
