/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TradeDirection = {
  Buy: "buy",
  Sell: "sell",
} as const;
export type TradeDirection = ClosedEnum<typeof TradeDirection>;

/** @internal */
export const TradeDirection$inboundSchema: z.ZodNativeEnum<
  typeof TradeDirection
> = z.nativeEnum(TradeDirection);

/** @internal */
export const TradeDirection$outboundSchema: z.ZodNativeEnum<
  typeof TradeDirection
> = TradeDirection$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TradeDirection$ {
  /** @deprecated use `TradeDirection$inboundSchema` instead. */
  export const inboundSchema = TradeDirection$inboundSchema;
  /** @deprecated use `TradeDirection$outboundSchema` instead. */
  export const outboundSchema = TradeDirection$outboundSchema;
}
