/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MarketSide,
  MarketSide$inboundSchema,
  MarketSide$outboundSchema,
} from "./marketside.js";
import {
  TradeDirection,
  TradeDirection$inboundSchema,
  TradeDirection$outboundSchema,
} from "./tradedirection.js";

export type Trade = {
  id: number;
  side: MarketSide;
  address: string;
  direction: TradeDirection;
  amount: number;
  price: number;
  txHash: string;
  created: Date;
};

/** @internal */
export const Trade$inboundSchema: z.ZodType<Trade, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int(),
    side: MarketSide$inboundSchema,
    address: z.string(),
    direction: TradeDirection$inboundSchema,
    amount: z.number(),
    price: z.number(),
    txHash: z.string(),
    created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  });

/** @internal */
export type Trade$Outbound = {
  id: number;
  side: string;
  address: string;
  direction: string;
  amount: number;
  price: number;
  txHash: string;
  created: string;
};

/** @internal */
export const Trade$outboundSchema: z.ZodType<
  Trade$Outbound,
  z.ZodTypeDef,
  Trade
> = z.object({
  id: z.number().int(),
  side: MarketSide$outboundSchema,
  address: z.string(),
  direction: TradeDirection$outboundSchema,
  amount: z.number(),
  price: z.number(),
  txHash: z.string(),
  created: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Trade$ {
  /** @deprecated use `Trade$inboundSchema` instead. */
  export const inboundSchema = Trade$inboundSchema;
  /** @deprecated use `Trade$outboundSchema` instead. */
  export const outboundSchema = Trade$outboundSchema;
  /** @deprecated use `Trade$Outbound` instead. */
  export type Outbound = Trade$Outbound;
}

export function tradeToJSON(trade: Trade): string {
  return JSON.stringify(Trade$outboundSchema.parse(trade));
}

export function tradeFromJSON(
  jsonString: string,
): SafeParseResult<Trade, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Trade$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Trade' from JSON`,
  );
}
