/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TreasuryStatus,
  TreasuryStatus$inboundSchema,
  TreasuryStatus$outboundSchema,
} from "./treasurystatus.js";

export type Treasury = {
  id?: number | undefined;
  /**
   * The required monthly budget for the project's operations
   */
  monthlyBudget: number;
  /**
   * EVM address of the treasury contract
   */
  address?: string | undefined;
  /**
   * Amount of Organization Tokens that the treasury has used to provide liquidity. If status is 'pending', this will be the amount planned for the liquidity pool.
   */
  tokenSupplyLp?: number | undefined;
  /**
   * Amount of USDC Tokens that the treasury has used to provide liquidity. If status is 'pending', this will be the amount planned for the liquidity pool.
   */
  usdcSupplyLp?: number | undefined;
  /**
   * Amount of Organization Tokens in the treasury reserve
   */
  tokenReserve?: number | undefined;
  /**
   * Amount of USDC Tokens in the treasury reserve
   */
  usdcReserve?: number | undefined;
  status?: TreasuryStatus | undefined;
};

/** @internal */
export const Treasury$inboundSchema: z.ZodType<
  Treasury,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  monthlyBudget: z.number(),
  address: z.string().optional(),
  tokenSupplyLp: z.number().optional(),
  usdcSupplyLp: z.number().optional(),
  tokenReserve: z.number().optional(),
  usdcReserve: z.number().optional(),
  status: TreasuryStatus$inboundSchema.optional(),
});

/** @internal */
export type Treasury$Outbound = {
  id?: number | undefined;
  monthlyBudget: number;
  address?: string | undefined;
  tokenSupplyLp?: number | undefined;
  usdcSupplyLp?: number | undefined;
  tokenReserve?: number | undefined;
  usdcReserve?: number | undefined;
  status?: string | undefined;
};

/** @internal */
export const Treasury$outboundSchema: z.ZodType<
  Treasury$Outbound,
  z.ZodTypeDef,
  Treasury
> = z.object({
  id: z.number().int().optional(),
  monthlyBudget: z.number(),
  address: z.string().optional(),
  tokenSupplyLp: z.number().optional(),
  usdcSupplyLp: z.number().optional(),
  tokenReserve: z.number().optional(),
  usdcReserve: z.number().optional(),
  status: TreasuryStatus$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Treasury$ {
  /** @deprecated use `Treasury$inboundSchema` instead. */
  export const inboundSchema = Treasury$inboundSchema;
  /** @deprecated use `Treasury$outboundSchema` instead. */
  export const outboundSchema = Treasury$outboundSchema;
  /** @deprecated use `Treasury$Outbound` instead. */
  export type Outbound = Treasury$Outbound;
}

export function treasuryToJSON(treasury: Treasury): string {
  return JSON.stringify(Treasury$outboundSchema.parse(treasury));
}

export function treasuryFromJSON(
  jsonString: string,
): SafeParseResult<Treasury, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Treasury$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Treasury' from JSON`,
  );
}
