/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TreasuryStatus = {
  Pending: "pending",
  Active: "active",
} as const;
export type TreasuryStatus = ClosedEnum<typeof TreasuryStatus>;

/** @internal */
export const TreasuryStatus$inboundSchema: z.ZodNativeEnum<
  typeof TreasuryStatus
> = z.nativeEnum(TreasuryStatus);

/** @internal */
export const TreasuryStatus$outboundSchema: z.ZodNativeEnum<
  typeof TreasuryStatus
> = TreasuryStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TreasuryStatus$ {
  /** @deprecated use `TreasuryStatus$inboundSchema` instead. */
  export const inboundSchema = TreasuryStatus$inboundSchema;
  /** @deprecated use `TreasuryStatus$outboundSchema` instead. */
  export const outboundSchema = TreasuryStatus$outboundSchema;
}
