/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProposalAction,
  ProposalAction$inboundSchema,
  ProposalAction$Outbound,
  ProposalAction$outboundSchema,
} from "./proposalaction.js";

/**
 * Set to 'staking' to submit draft
 */
export const UpdateProposalStatus = {
  Staking: "staking",
} as const;
/**
 * Set to 'staking' to submit draft
 */
export type UpdateProposalStatus = ClosedEnum<typeof UpdateProposalStatus>;

export type UpdateProposal = {
  title?: string | undefined;
  description?: string | undefined;
  actions?: Array<ProposalAction> | undefined;
  /**
   * Set to 'staking' to submit draft
   */
  status?: UpdateProposalStatus | undefined;
};

/** @internal */
export const UpdateProposalStatus$inboundSchema: z.ZodNativeEnum<
  typeof UpdateProposalStatus
> = z.nativeEnum(UpdateProposalStatus);

/** @internal */
export const UpdateProposalStatus$outboundSchema: z.ZodNativeEnum<
  typeof UpdateProposalStatus
> = UpdateProposalStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateProposalStatus$ {
  /** @deprecated use `UpdateProposalStatus$inboundSchema` instead. */
  export const inboundSchema = UpdateProposalStatus$inboundSchema;
  /** @deprecated use `UpdateProposalStatus$outboundSchema` instead. */
  export const outboundSchema = UpdateProposalStatus$outboundSchema;
}

/** @internal */
export const UpdateProposal$inboundSchema: z.ZodType<
  UpdateProposal,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  actions: z.array(ProposalAction$inboundSchema).optional(),
  status: UpdateProposalStatus$inboundSchema.optional(),
});

/** @internal */
export type UpdateProposal$Outbound = {
  title?: string | undefined;
  description?: string | undefined;
  actions?: Array<ProposalAction$Outbound> | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdateProposal$outboundSchema: z.ZodType<
  UpdateProposal$Outbound,
  z.ZodTypeDef,
  UpdateProposal
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  actions: z.array(ProposalAction$outboundSchema).optional(),
  status: UpdateProposalStatus$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateProposal$ {
  /** @deprecated use `UpdateProposal$inboundSchema` instead. */
  export const inboundSchema = UpdateProposal$inboundSchema;
  /** @deprecated use `UpdateProposal$outboundSchema` instead. */
  export const outboundSchema = UpdateProposal$outboundSchema;
  /** @deprecated use `UpdateProposal$Outbound` instead. */
  export type Outbound = UpdateProposal$Outbound;
}

export function updateProposalToJSON(updateProposal: UpdateProposal): string {
  return JSON.stringify(UpdateProposal$outboundSchema.parse(updateProposal));
}

export function updateProposalFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProposal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProposal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProposal' from JSON`,
  );
}
